import { getLlmAdapter } from "@/lib/ai/adapters/get-llm-adapter";
import { buildClinicSummaryPrompt } from "@/lib/ai/prompts/clinic-summary-prompt";
import { AiNotConfiguredError, InsufficientDataError, type ClinicSummaryResult } from "@/lib/ai/types";
import type { ReviewWithScores } from "@/types";

const MIN_REVIEWS_FOR_SUMMARY = 3;

function parseJsonResponse(raw: string): ClinicSummaryResult | null {
  try {
    const cleaned = raw
      .trim()
      .replace(/^```(?:json)?\s*/i, "")
      .replace(/\s*```$/, "")
      .trim();
    const parsed = JSON.parse(cleaned);
    if (
      typeof parsed.strengths === "string" &&
      typeof parsed.weaknesses === "string" &&
      typeof parsed.recommendation === "string"
    ) {
      return { ...parsed, basedOnReviewCount: 0 };
    }
    return null;
  } catch {
    return null;
  }
}

export async function generateClinicSummary(
  reviews: ReviewWithScores[]
): Promise<ClinicSummaryResult> {
  if (reviews.length < MIN_REVIEWS_FOR_SUMMARY) {
    throw new InsufficientDataError(
      `AI özeti için en az ${MIN_REVIEWS_FOR_SUMMARY} onaylı değerlendirme gerekiyor (şu an ${reviews.length}).`
    );
  }

  const adapter = getLlmAdapter();
  if (!adapter) {
    throw new AiNotConfiguredError();
  }

  const { system, prompt } = buildClinicSummaryPrompt(reviews);

  try {
    const raw = await adapter.complete({ system, prompt, maxTokens: 600 });
    const parsed = parseJsonResponse(raw);

    if (!parsed) {
      console.error("[clinic-ai-summary] invalid LLM response", {
        responsePreview: raw.slice(0, 500),
      });
      throw new Error("AI servisi geçerli özet formatı döndürmedi.");
    }

    console.info("[clinic-ai-summary] generated by configured LLM", {
      reviewCount: reviews.length,
    });

    return { ...parsed, basedOnReviewCount: reviews.length };
  } catch (error) {
    console.error("[clinic-ai-summary] LLM request failed", error);
    throw error;
  }
}
