-- Türkiye'nin 81 ilindeki kamu hastaneleri için ülke geneli başlangıç kataloğu.
-- Kaynak taban: MHRS kamu sağlık tesisi verisi; projedeki daha yeni il kayıtları korunur.
-- Ağız ve diş sağlığı merkezleri bu tıp kliniği kataloğuna dahil değildir.
-- Standart klinik şablonu, projedeki mevcut il ekleme migrasyonlarıyla aynıdır.
-- İdempotenttir; aynı kurum/klinik ikinci kez eklenmez.

with hospital_seed(name, city, district, hospital_type) as (
  values
    ('Adana Ceyhan Devlet Hastanesi', 'Adana', 'Ceyhan', 'state_hospital'),
    ('Adana Dr. Ekrem Tok Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Adana', 'Çukurova', 'state_hospital'),
    ('Adana İmamoğlu Devlet Hastanesi', 'Adana', 'İmamoğlu', 'state_hospital'),
    ('Adana Karaisalı Devlet Hastanesi', 'Adana', 'Karaisalı', 'state_hospital'),
    ('Adana Kozan Devlet Hastanesi', 'Adana', 'Kozan', 'state_hospital'),
    ('Adana Pozantı 80.Yıl Devlet Hastanesi', 'Adana', 'Pozantı', 'state_hospital'),
    ('Adana Çukurova Dr. Aşkım Tüfekçi Devlet Hastanesi', 'Adana', 'Seyhan', 'state_hospital'),
    ('Adana Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Adana', 'Seyhan', 'state_hospital'),
    ('Adana Tufanbeyli Devlet Hastanesi', 'Adana', 'Tufanbeyli', 'state_hospital'),
    ('Adana Devlet Hastanesi', 'Adana', 'Yüreğir', 'state_hospital'),
    ('Adana Numune Eğitim Ve Araştırma Hastanesi', 'Adana', 'Yüreğir', 'training_and_research_hospital'),
    ('Afyonkarahisar Dr. Halil İbrahim Özsoy Bolvadin Devlet Hastanesi', 'Afyonkarahisar', 'Bolvadin', 'state_hospital'),
    ('Afyonkarahisar Çay Devlet Hastanesi', 'Afyonkarahisar', 'Çay', 'state_hospital'),
    ('Afyonkarahisar Dinar Devlet Hastanesi', 'Afyonkarahisar', 'Dinar', 'state_hospital'),
    ('Afyonkarahisar Emirdağ Devlet Hastanesi', 'Afyonkarahisar', 'Emirdağ', 'state_hospital'),
    ('Afyonkarahisar İscehisar Devlet Hastanesi', 'Afyonkarahisar', 'İscehisar', 'state_hospital'),
    ('Afyonkarahisar Devlet Hastanesi', 'Afyonkarahisar', 'Merkez', 'state_hospital'),
    ('Afyonkarahisar Zübeyde Hanım Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Afyonkarahisar', 'Merkez', 'state_hospital'),
    ('Afyonkarahisar Sandıklı Devlet Hastanesi', 'Afyonkarahisar', 'Sandıklı', 'state_hospital'),
    ('Afyonkarahisar Sinanpaşa İlçe Hastanesi', 'Afyonkarahisar', 'Sinanpaşa', 'state_hospital'),
    ('Afyonkarahisar Şuhut Devlet Hastanesi', 'Afyonkarahisar', 'Şuhut', 'state_hospital'),
    ('Ağrı Diyadin Devlet Hastanesi', 'Ağrı', 'Diyadin', 'state_hospital'),
    ('Ağrı Dr. Yaşar Eryılmaz Doğubeyazıt Devlet Hastanesi', 'Ağrı', 'Doğubeyazıt', 'state_hospital'),
    ('Ağrı Eleşkirt Devlet Hastanesi', 'Ağrı', 'Eleşkirt', 'state_hospital'),
    ('Ağrı Hamur İlçe Devlet Hastanesi', 'Ağrı', 'Hamur', 'state_hospital'),
    ('Ağrı Devlet Hastanesi', 'Ağrı', 'Merkez', 'state_hospital'),
    ('Ağrı Patnos Devlet Hastanesi', 'Ağrı', 'Patnos', 'state_hospital'),
    ('Ağrı Taşlıçay İlçe Devlet Hastanesi', 'Ağrı', 'Taşlıçay', 'state_hospital'),
    ('Ağrı Tutak Devlet Hastanesi', 'Ağrı', 'Tutak', 'state_hospital'),
    ('Aksaray Eskil Devlet Hastanesi', 'Aksaray', 'Esk�l', 'state_hospital'),
    ('Aksaray G�la�a� �l�e Hastanesi', 'Aksaray', 'G�la�a�', 'state_hospital'),
    ('Aksaray Devlet Hastanesi', 'Aksaray', 'Merkez', 'state_hospital'),
    ('Aksaray Ortak�y Devlet Hastanesi', 'Aksaray', 'Ortak�y', 'state_hospital'),
    ('Amasya Gümüşhacıköy Devlet Hastanesi', 'Amasya', 'Gümüşhacıköy', 'state_hospital'),
    ('Amasya Sabuncuoğlu Şerefeddin Devlet Hastanesi', 'Amasya', 'Merkez', 'state_hospital'),
    ('Amasya Merzifon Kara Mustafa Paşa Devlet Hastanesi', 'Amasya', 'Merzifon', 'state_hospital'),
    ('Amasya Suluova Devlet Hastanesi', 'Amasya', 'Suluova', 'state_hospital'),
    ('Amasya Taşova Devlet Hastanesi', 'Amasya', 'Taşova', 'state_hospital'),
    ('Antalya Akseki Devlet Hastanesi', 'Antalya', 'Akseki', 'state_hospital'),
    ('Antalya Alanya Devlet Hastanesi', 'Antalya', 'Alanya', 'state_hospital'),
    ('Antalya Demre Devlet Hastanesi', 'Antalya', 'Demre', 'state_hospital'),
    ('Antalya Elmalı Devlet Hastanesi', 'Antalya', 'Elmalı', 'state_hospital'),
    ('Antalya Finike Devlet Hastanesi', 'Antalya', 'Finike', 'state_hospital'),
    ('Antalya Gazipaşa Devlet Hastanesi', 'Antalya', 'Gazipaşa', 'state_hospital'),
    ('Antalya Kaş Devlet Hastanesi', 'Antalya', 'Kaş', 'state_hospital'),
    ('Antalya Kemer Devlet Hastanesi', 'Antalya', 'Kemer', 'state_hospital'),
    ('Antalya Korkuteli Devlet Hastanesi', 'Antalya', 'Korkuteli', 'state_hospital'),
    ('Antalya Kumluca Devlet Hastanesi', 'Antalya', 'Kumluca', 'state_hospital'),
    ('Antalya Manavgat Devlet Hastanesi', 'Antalya', 'Manavgat', 'state_hospital'),
    ('Antalya Atatürk Devlet Hastanesi', 'Antalya', 'Muratpaşa', 'state_hospital'),
    ('Antalya Eğitim Ve Araştırma Hastanesi', 'Antalya', 'Muratpaşa', 'training_and_research_hospital'),
    ('Antalya Serik Devlet Hastanesi', 'Antalya', 'Serik', 'state_hospital'),
    ('Ardahan G�le Devlet Hastanesi', 'Ardahan', 'G�le', 'state_hospital'),
    ('Ardahan Devlet Hastanesi', 'Ardahan', 'Merkez', 'state_hospital'),
    ('Aydın Çine Devlet Hastanesi', 'Aydın', 'Çine', 'state_hospital'),
    ('Aydın Didim Devlet Hastanesi', 'Aydın', 'Didim', 'state_hospital'),
    ('Aydın Germencik Devlet Hastanesi', 'Aydın', 'Germencik', 'state_hospital'),
    ('Aydın Kuşadası Devlet Hastanesi', 'Aydın', 'Kuşadası', 'state_hospital'),
    ('Aydın Atatürk Devlet Hastanesi', 'Aydın', 'Merkez', 'state_hospital'),
    ('Aydın Devlet Hastanesi', 'Aydın', 'Merkez', 'state_hospital'),
    ('Aydın Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Aydın', 'Merkez', 'state_hospital'),
    ('Aydın Nazilli Devlet Hastanesi', 'Aydın', 'Nazilli', 'state_hospital'),
    ('Aydın Söke Fehime Faik Kocagöz Devlet Hastanesi', 'Aydın', 'Söke', 'state_hospital'),
    ('Balıkesir Ayvalık Devlet Hastanesi', 'Balıkesir', 'Ayvalık', 'state_hospital'),
    ('Balıkesir Bandırma Devlet Hastanesi', 'Balıkesir', 'Bandırma', 'state_hospital'),
    ('Balıkesir Bigadiç Devlet Hastanesi', 'Balıkesir', 'Bigadiç', 'state_hospital'),
    ('Balıkesir Burhaniye Devlet Hastanesi', 'Balıkesir', 'Burhaniye', 'state_hospital'),
    ('Balıkesir Dursunbey Devlet Hastanesi', 'Balıkesir', 'Dursunbey', 'state_hospital'),
    ('Balıkesir Edremit Devlet Hastanesi', 'Balıkesir', 'Edremit', 'state_hospital'),
    ('Balıkesir Erdek Neyyire Sıtkı Devlet Hastanesi', 'Balıkesir', 'Erdek', 'state_hospital'),
    ('Balıkesir Gönen Devlet Hastanesi', 'Balıkesir', 'Gönen', 'state_hospital'),
    ('Balıkesir Havran Devlet Hastanesi', 'Balıkesir', 'Havran', 'state_hospital'),
    ('Balıkesir İvrindi Devlet Hastanesi', 'Balıkesir', 'İvrindi', 'state_hospital'),
    ('Balıkesir Manyas Devlet Hastanesi', 'Balıkesir', 'Manyas', 'state_hospital'),
    ('Balıkesir Atatürk Devlet Hastanesi', 'Balıkesir', 'Merkez', 'state_hospital'),
    ('Balıkesir Devlet Hastanesi', 'Balıkesir', 'Merkez', 'state_hospital'),
    ('Balıkesir Göğüs Hastalıkları Hastanesi', 'Balıkesir', 'Merkez', 'state_hospital'),
    ('Balıkesir Savaştepe Devlet Hastanesi', 'Balıkesir', 'Savaştepe', 'state_hospital'),
    ('Balıkesir Sındırgı Devlet Hastanesi', 'Balıkesir', 'Sındırgı', 'state_hospital'),
    ('Balıkesir Susurluk Devlet Hastanesi', 'Balıkesir', 'Susurluk', 'state_hospital'),
    ('Bart�n Devlet Hastanesi', 'Bartın', 'Merkez', 'state_hospital'),
    ('Batman Gerc�� Devlet Hastanesi', 'Batman', 'Gerc��', 'state_hospital'),
    ('Batman Kozluk Devlet Hastanesi', 'Batman', 'Kozluk', 'state_hospital'),
    ('Batman B�lge Devlet Hastanesi', 'Batman', 'Merkez', 'state_hospital'),
    ('Batman Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Batman', 'Merkez', 'state_hospital'),
    ('Batman Sason Devlet Hastanesi', 'Batman', 'Sason', 'state_hospital'),
    ('Bayburt Devlet Hastanesi', 'Bayburt', 'Merkez', 'state_hospital'),
    ('Bingöl Genç Devlet Hastanesi', 'Bingöl', 'Genç', 'state_hospital'),
    ('Bingöl Karlıova İlçe Hastanesi', 'Bingöl', 'Karlıova', 'state_hospital'),
    ('Bingöl Devlet Hastanesi', 'Bingöl', 'Merkez', 'state_hospital'),
    ('Bingöl Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Bingöl', 'Merkez', 'state_hospital'),
    ('Bingöl Solhan Devlet Hastanesi', 'Bingöl', 'Solhan', 'state_hospital'),
    ('Bitlis Adilcevaz Onkoloji Hastanesi', 'Bitlis', 'Adilcevaz', 'state_hospital'),
    ('Bitlis Ahlat Devlet Hastanesi', 'Bitlis', 'Ahlat', 'state_hospital'),
    ('Bitlis Güroymak Devlet Hastanesi', 'Bitlis', 'Güroymak', 'state_hospital'),
    ('Bitlis Hizan İlçe Hastanesi', 'Bitlis', 'Hizan', 'state_hospital'),
    ('Bitlis Devlet Hastanesi', 'Bitlis', 'Merkez', 'state_hospital'),
    ('Bitlis Mutki İlçe Hastanesi', 'Bitlis', 'Mutki', 'state_hospital'),
    ('Bitlis Tatvan Devlet Hastanesi', 'Bitlis', 'Tatvan', 'state_hospital'),
    ('Bolu Gerede Devlet Hastanesi', 'Bolu', 'Gerede', 'state_hospital'),
    ('Bolu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Bolu', 'Merkez', 'state_hospital'),
    ('Bolu İzzet Baysal Devlet Hastanesi', 'Bolu', 'Merkez', 'state_hospital'),
    ('Bolu İzzet Baysal Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Bolu', 'Merkez', 'state_hospital'),
    ('Bolu Mudurnu İlçe Hastanesi', 'Bolu', 'Mudurnu', 'state_hospital'),
    ('Burdur Bucak Devlet Hastanesi', 'Burdur', 'Bucak', 'state_hospital'),
    ('Burdur Gölhisar Devlet Hastanesi', 'Burdur', 'Gölhisar', 'state_hospital'),
    ('Burdur Devlet Hastanesi', 'Burdur', 'Merkez', 'state_hospital'),
    ('Burdur Yeşilova Devlet Hastanesi', 'Burdur', 'Yeşilova', 'state_hospital'),
    ('Bursa Gemlik Muammer Ağım Devlet Hastanesi', 'Bursa', 'Gemlik', 'state_hospital'),
    ('Bursa İnegöl Devlet Hastanesi', 'Bursa', 'İnegöl', 'state_hospital'),
    ('Bursa İznik Devlet Hastanesi', 'Bursa', 'İznik', 'state_hospital'),
    ('Bursa Karacabey Devlet Hastanesi', 'Bursa', 'Karacabey', 'state_hospital'),
    ('Bursa M.Kemalpaşa Devlet Hastanesi', 'Bursa', 'M.kemalpaşa', 'state_hospital'),
    ('Bursa Mudanya Şaziye Rüştü Devlet Hastanesi', 'Bursa', 'Mudanya', 'state_hospital'),
    ('Bursa Dörtçelik Çocuk Hastalıkları Hastanesi', 'Bursa', 'Nilüfer', 'state_hospital'),
    ('Bursa Orhaneli Devlet Hastanesi', 'Bursa', 'Orhaneli', 'state_hospital'),
    ('Bursa Orhangazi Devlet Hastanesi', 'Bursa', 'Orhangazi', 'state_hospital'),
    ('Bursa Ali Osman Sönmez Onkoloji Hastanesi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Çekirge Devlet Hastanesi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Devlet Hastanesi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Dr. Ayten Bozkaya Spastik Çocuklar Hastanesi Ve Rehabilitasyon Merkezi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Zübeyde Hanım Doğumevi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Yenişehir Devlet Hastanesi', 'Bursa', 'Yenişehir', 'state_hospital'),
    ('Bursa Prof.Dr. Türkan Akyol Göğüs Hastalıkları Hastanesi', 'Bursa', 'Yıldırım', 'state_hospital'),
    ('Bursa Şevket Yılmaz Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım', 'training_and_research_hospital'),
    ('Bursa Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım', 'training_and_research_hospital'),
    ('Çanakkale Ayvacık Devlet Hastanesi', 'Çanakkale', 'Ayvacık', 'state_hospital'),
    ('Çanakkale Bayramiç Devlet Hastanesi', 'Çanakkale', 'Bayramiç', 'state_hospital'),
    ('Çanakkale Biga Devlet Hastanesi', 'Çanakkale', 'Biga', 'state_hospital'),
    ('Çanakkale Çan Devlet Hastanesi', 'Çanakkale', 'Çan', 'state_hospital'),
    ('Çanakkale Ezine Devlet Hastanesi', 'Çanakkale', 'Ezine', 'state_hospital'),
    ('Çanakkale Gelibolu Devlet Hastanesi', 'Çanakkale', 'Gelibolu', 'state_hospital'),
    ('Çanakkale Gökçeada Devlet Hastanesi', 'Çanakkale', 'Gökçeada', 'state_hospital'),
    ('Çanakkale Lapseki Devlet Hastanesi', 'Çanakkale', 'Lapseki', 'state_hospital'),
    ('Çanakkale Devlet Hastanesi', 'Çanakkale', 'Merkez', 'state_hospital'),
    ('Çanakkale Yenice Devlet Hastanesi', 'Çanakkale', 'Yenice', 'state_hospital'),
    ('Çankırı Çerkeş Devlet Hastanesi', 'Çankırı', 'Çerkeş', 'state_hospital'),
    ('Çankırı Ilgaz Devlet Hastanesi', 'Çankırı', 'Ilgaz', 'state_hospital'),
    ('Çankırı Kurşunlu İlçe Hastanesi', 'Çankırı', 'Kurşunlu', 'state_hospital'),
    ('Çankırı Devlet Hastanesi', 'Çankırı', 'Merkez', 'state_hospital'),
    ('Çorum Alaca Devlet Hastanesi', 'Çorum', 'Alaca', 'state_hospital'),
    ('Çorum Bayat Devlet Hastanesi', 'Çorum', 'Bayat', 'state_hospital'),
    ('Çorum İskilip Devlet Hastanesi', 'Çorum', 'İskilip', 'state_hospital'),
    ('Çorum Kargı Devlet Hastanesi', 'Çorum', 'Kargı', 'state_hospital'),
    ('Çorum Mecitözü Devlet Hastanesi', 'Çorum', 'Mecitözü', 'state_hospital'),
    ('Çorum Göğüs Hastalıkları Hastanesi', 'Çorum', 'Merkez', 'state_hospital'),
    ('Çorum T.C. Sağlık Bakanlığı Hitit Üniversitesi Çorum Eğitim Ve Araştırma Hastanesi', 'Çorum', 'Merkez', 'university_hospital'),
    ('Çorum Osmancık Devlet Hastanesi', 'Çorum', 'Osmancık', 'state_hospital'),
    ('Çorum Sungurlu Devlet Hastanesi', 'Çorum', 'Sungurlu', 'state_hospital'),
    ('Denizli Acıpayam Devlet Hastanesi', 'Denizli', 'Acıpayam', 'state_hospital'),
    ('Denizli Buldan Göğüs Hastalıkları Hastanesi', 'Denizli', 'Buldan', 'state_hospital'),
    ('Denizli Çal Devlet Hastanesi', 'Denizli', 'Çal', 'state_hospital'),
    ('Denizli Çameli Devlet Hastanesi', 'Denizli', 'Çameli', 'state_hospital'),
    ('Denizli Çivril Devlet Hastanesi', 'Denizli', 'Çivril', 'state_hospital'),
    ('Denizli Honaz Devlet Hastanesi', 'Denizli', 'Honaz', 'state_hospital'),
    ('Denizli Kale Devlet Hastanesi', 'Denizli', 'Kale', 'state_hospital'),
    ('Denizli Devlet Hastanesi', 'Denizli', 'Merkez', 'state_hospital'),
    ('Denizli Servergazi Devlet Hastanesi', 'Denizli', 'Merkez', 'state_hospital'),
    ('Denizli Sarayköy Devlet Hastanesi', 'Denizli', 'Sarayköy', 'state_hospital'),
    ('Denizli Tavas Devlet Hastanesi', 'Denizli', 'Tavas', 'state_hospital'),
    ('Diyarbakır Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Bağlar', 'state_hospital'),
    ('Diyarbakır Bismil Devlet Hastanesi', 'Diyarbakır', 'Bismil', 'state_hospital'),
    ('Diyarbakır Çermik Devlet Hastanesi', 'Diyarbakır', 'Çermik', 'state_hospital'),
    ('Diyarbakır Çınar İlçe Hastanesi', 'Diyarbakır', 'Çınar', 'state_hospital'),
    ('Diyarbakır Dicle İlçe Hastanesi', 'Diyarbakır', 'Dicle', 'state_hospital'),
    ('Diyarbakır Eğil İlçe Hastanesi', 'Diyarbakır', 'Eğil', 'state_hospital'),
    ('Diyarbakır Ergani Devlet Hastanesi', 'Diyarbakır', 'Ergani', 'state_hospital'),
    ('Diyarbakır Hani İlçe Hastanesi', 'Diyarbakır', 'Hani', 'state_hospital'),
    ('Diyarbakır Eğitim Ve Araştırma Hastanesi', 'Diyarbakır', 'Kayapınar', 'training_and_research_hospital'),
    ('Diyarbakır Kulp İlçe Hastanesi', 'Diyarbakır', 'Kulp', 'state_hospital'),
    ('Diyarbakır Lice Halis Toprak Vakfı İlçe Hastanesi', 'Diyarbakır', 'Lice', 'state_hospital'),
    ('Diyarbakır Silvan Dr. Yusuf Azizoğlu Devlet Hastanesi', 'Diyarbakır', 'Silvan', 'state_hospital'),
    ('Diyarbakır Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Yenişehir', 'state_hospital'),
    ('Diyarbakır Devlet Hastanesi', 'Diyarbakır', 'Yenişehir', 'state_hospital'),
    ('D�zce Ak�akoca Devlet Hastanesi', 'Düzce', 'Ak�akoca', 'state_hospital'),
    ('D�zce Atat�rk Devlet Hastanesi', 'Düzce', 'Merkez', 'state_hospital'),
    ('Edirne Keşan Devlet Hastanesi', 'Edirne', 'Keşan', 'state_hospital'),
    ('Edirne Devlet Hastanesi', 'Edirne', 'Merkez', 'state_hospital'),
    ('Edirne Uzunköprü Devlet Hastanesi', 'Edirne', 'Uzunköprü', 'state_hospital'),
    ('Elazığ Karakoçan Devlet Hastanesi', 'Elazığ', 'Karakoçan', 'state_hospital'),
    ('Elazığ Kovancılar Devlet Hastanesi', 'Elazığ', 'Kovancılar', 'state_hospital'),
    ('Elazığ Maden Devlet Hastanesi', 'Elazığ', 'Maden', 'state_hospital'),
    ('Elazığ Eğitim Ve Araştırma Hastanesi', 'Elazığ', 'Merkez', 'training_and_research_hospital'),
    ('Elazığ Harput Devlet Hastanesi', 'Elazığ', 'Merkez', 'state_hospital'),
    ('Elazığ Ruh Sağlıgı Ve Hastalıkları Hastanesi', 'Elazığ', 'Merkez', 'state_hospital'),
    ('Elazığ Palu Devlet Hastanesi', 'Elazığ', 'Palu', 'state_hospital'),
    ('Erzincan Mengücek Gazi Eğitim Ve Araştırma Hastanesi', 'Erzincan', 'Mengücek', 'training_and_research_hospital'),
    ('Erzincan Refahiye Dr. Fahrettin Uğur İlçe Hastanesi', 'Erzincan', 'Refahiye', 'state_hospital'),
    ('Erzincan Tercan Devlet Hastanesi', 'Erzincan', 'Tercan', 'state_hospital'),
    ('Erzurum Aşkale İlçe Hastanesi', 'Erzurum', 'Aşkale', 'state_hospital'),
    ('Erzurum Çat İlçe Hastanesi', 'Erzurum', 'Çat', 'state_hospital'),
    ('Erzurum Hınıs Devlet Hastanesi', 'Erzurum', 'Hınıs', 'state_hospital'),
    ('Erzurum Horasan Devlet Hastanesi', 'Erzurum', 'Horasan', 'state_hospital'),
    ('Erzurum İspir Devlet Hastanesi', 'Erzurum', 'İspir', 'state_hospital'),
    ('Erzurum Karaçoban İlçe Hastanesi', 'Erzurum', 'Karaçoban', 'state_hospital'),
    ('Erzurum Türk Eczacıları Birliği Karayazı İlçe Hastanesi', 'Erzurum', 'Karayazı', 'state_hospital'),
    ('Erzurum Oltu Devlet Hastanesi', 'Erzurum', 'Oltu', 'state_hospital'),
    ('Erzurum Nenehatun Kadın Doğum Hastanesi', 'Erzurum', 'Palandöken', 'state_hospital'),
    ('Erzurum Pasinler İbrahim Hakkı Devlet Hastanesi', 'Erzurum', 'Pasinler', 'state_hospital'),
    ('Erzurum Tekman Devlet Hastanesi', 'Erzurum', 'Tekman', 'state_hospital'),
    ('Erzurum Tortum İlçe Hastanesi', 'Erzurum', 'Tortum', 'state_hospital'),
    ('Erzurum Bölge Eğitim Ve Araştırma Hastanesi', 'Erzurum', 'Yakutiye', 'training_and_research_hospital'),
    ('Erzurum Palandöken Devlet Hastanesi', 'Erzurum', 'Yakutiye', 'state_hospital'),
    ('Eskişehir Çifteler Devlet Hastanesi', 'Eskişehir', 'Çifteler', 'state_hospital'),
    ('Eskişehir Günyüzü İlçe Hastanesi', 'Eskişehir', 'Günyüzü', 'state_hospital'),
    ('Eskişehir Mahmudiye İlçe Hastanesi', 'Eskişehir', 'Mahmudiye', 'state_hospital'),
    ('Eskişehir Mihalıççık Gün Sazak İlçe Hastanesi', 'Eskişehir', 'Mihalıççık', 'state_hospital'),
    ('Eskişehir Devlet Hastanesi', 'Eskişehir', 'Odunpazarı', 'state_hospital'),
    ('Eskişehir Sivrihisar Devlet Hastanesi', 'Eskişehir', 'Sivrihisar', 'state_hospital'),
    ('Eskişehir Yunus Emre Devlet Hastanesi', 'Eskişehir', 'Tepebaşı', 'state_hospital'),
    ('Gaziantep Araban İlçe Hastanesi', 'Gaziantep', 'Araban', 'state_hospital'),
    ('Gaziantep İslahiye Devlet Hastanesi', 'Gaziantep', 'İslahiye', 'state_hospital'),
    ('Gaziantep Nizip Devlet Hastanesi', 'Gaziantep', 'Nizip', 'state_hospital'),
    ('Gaziantep Nurdağı İlçe Hastanesi', 'Gaziantep', 'Nurdağı', 'state_hospital'),
    ('Gaziantep Oğuzeli İlçe Hastanesi', 'Gaziantep', 'Oğuzeli', 'state_hospital'),
    ('Gaziantep Dr. Ersin Arslan Devlet Hastanesi', 'Gaziantep', 'Şahinbey', 'state_hospital'),
    ('Gaziantep 25 Aralık Devlet Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Gaziantep Cengiz Gökçek Kadın Hastalıkları Ve Doğum Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Gaziantep Çocuk Hastalıkları Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Gaziantep Şehitkamil Devlet Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Giresun Alucra İlçe Hastanesi', 'Giresun', 'Alucra', 'state_hospital'),
    ('Giresun Bulancak Devlet Hastanesi', 'Giresun', 'Bulancak', 'state_hospital'),
    ('Giresun Dereli İlçe Hastanesi', 'Giresun', 'Dereli', 'state_hospital'),
    ('Giresun Espiye Devlet Hastanesi', 'Giresun', 'Espiye', 'state_hospital'),
    ('Giresun Op.Dr. Ergun Özdemir Görele Devlet Hastanesi', 'Giresun', 'Görele', 'state_hospital'),
    ('Giresun Dr. A.İlhan Özdemir Devlet Hastanesi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Dr. Ali Menekşe Göğüs Hastalıkları Hastanesi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Ş.Karahisar Devlet Hastanesi', 'Giresun', 'Şebinkarahisar', 'state_hospital'),
    ('Giresun Tirebolu Devlet Hastanesi', 'Giresun', 'Tirebolu', 'state_hospital'),
    ('Giresun Yağlıdere İlçe Hastanesi', 'Giresun', 'Yağlıdere', 'state_hospital'),
    ('Gümüşhane Kelkit Devlet Hastanesi', 'Gümüşhane', 'Kelkit', 'state_hospital'),
    ('Gümüşhane Devlet Hastanesi', 'Gümüşhane', 'Merkez', 'state_hospital'),
    ('Gümüşhane Şiran Devlet Hastanesi', 'Gümüşhane', 'Şiran', 'state_hospital'),
    ('I�d�r Devlet Hastanesi', 'Iğdır', 'Merkez', 'state_hospital'),
    ('I�d�r Tuzluca Devlet Hastanesi', 'Iğdır', 'Tuzluca', 'state_hospital'),
    ('Isparta Eğirdir Kemik Eklem Hastalıkları Tedavi Ve Rehabilitasyon Hastanesi', 'Isparta', 'Eğirdir', 'state_hospital'),
    ('Isparta Devlet Hastanesi', 'Isparta', 'Merkez', 'state_hospital'),
    ('Isparta Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Isparta', 'Merkez', 'state_hospital'),
    ('Isparta Şarkikaraağaç Devlet Hastanesi', 'Isparta', 'Şarkikaraağaç', 'state_hospital'),
    ('Isparta Yalvaç Devlet Hastanesi', 'Isparta', 'Yalvaç', 'state_hospital'),
    ('�zmir Alia�a Devlet Hastanesi', 'İzmir', 'Al�a�a', 'state_hospital'),
    ('�zmir Bay�nd�r Devlet Hastanesi', 'İzmir', 'Bayındır', 'state_hospital'),
    ('�zmir Dr. Faruk �lker Bergama Devlet Hastanesi', 'İzmir', 'Bergama', 'state_hospital'),
    ('�zmir Bornova T�rkan �zilhan Devlet Hastanesi', 'İzmir', 'Bornova', 'state_hospital'),
    ('�zmir Buca Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'İzmir', 'Buca', 'state_hospital'),
    ('�zmir Buca Seyfi Demirsoy Devlet Hastanesi', 'İzmir', 'Buca', 'state_hospital'),
    ('�zmir Dikili Devlet Hastanesi', 'İzmir', 'D�k�l�', 'state_hospital'),
    ('�zmir Fo�a Devlet Hastanesi', 'İzmir', 'Fo�a', 'state_hospital'),
    ('�zmir Gaziemir Nevvar Salih ��g�ren Devlet Hastanesi', 'İzmir', 'Gaz�em�r', 'state_hospital'),
    ('�zmir Bozyaka E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Karaba�lar', 'state_hospital'),
    ('�zmir Katip �elebi �niversitesi Atat�rk E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Karaba�lar', 'state_hospital'),
    ('�zmir Kar��yaka Devlet Hastanesi', 'İzmir', 'Kar�ıyaka', 'state_hospital'),
    ('�zmir Kemalpa�a Devlet Hastanesi', 'İzmir', 'Kemalpa�a', 'state_hospital'),
    ('�zmir Alsancak Nevvar Salih ��g�ren Devlet Hastanesi', 'İzmir', 'Konak', 'state_hospital'),
    ('�zmir Dr. Beh�et Uz �ocuk Hastal�klar� Ve Cerrahisi E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Konak', 'state_hospital'),
    ('�zmir Dr. Suat Seren G���s Hastal�klar� Ve Cerrahisi E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Konak', 'state_hospital'),
    ('�zmir E�itim Di� Hastanesi', 'İzmir', 'Konak', 'state_hospital'),
    ('�zmir Tepecik E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Konak', 'state_hospital'),
    ('�zmir Kiraz Devlet Hastanesi', 'İzmir', 'K�raz', 'state_hospital'),
    ('�zmir Menemen Devlet Hastanesi', 'İzmir', 'Menemen', 'state_hospital'),
    ('�zmir Nejat Hepkon Seferihisar Devlet Hastanesi', 'İzmir', 'Sefer�h�sar', 'state_hospital'),
    ('�zmir Sel�uk Devlet Hastanesi', 'İzmir', 'Sel�uk', 'state_hospital'),
    ('�zmir M.Enver �enerdem Torbal� Devlet Hastanesi', 'İzmir', 'Torbalı', 'state_hospital'),
    ('�zmir Tire Devlet Hastanesi', 'İzmir', 'T�re', 'state_hospital'),
    ('�zmir Urla Devlet Hastanesi', 'İzmir', 'Urla', 'state_hospital'),
    ('�zmir �demi� Devlet Hastanesi', 'İzmir', '�dem��', 'state_hospital'),
    ('�zmir Alper �izgenakat �e�me Devlet Hastanesi', 'İzmir', '�e�me', 'state_hospital'),
    ('�zmir �i�li Devlet Hastanesi', 'İzmir', '���l�', 'state_hospital'),
    ('Kahramanmaraş Afşin Devlet Hastanesi', 'Kahramanmaraş', 'Afşin', 'state_hospital'),
    ('Kahramanmaraş Andırın Devlet Hastanesi', 'Kahramanmaraş', 'Andırın', 'state_hospital'),
    ('Kahramanmaraş Çağlayancerit İlçe Hastanesi', 'Kahramanmaraş', 'Çağlayancerit', 'state_hospital'),
    ('Kahramanmaraş Elbistan Devlet Hastanesi', 'Kahramanmaraş', 'Elbistan', 'state_hospital'),
    ('Kahramanmaraş Dr. Süreyya Adanalı Göksun Devlet Hastanesi', 'Kahramanmaraş', 'Göksun', 'state_hospital'),
    ('Kahramanmaraş Necip Fazıl Şehir Devlet Hastanesi', 'Kahramanmaraş', 'Merkez', 'state_hospital'),
    ('Kahramanmaraş Pazarcık Devlet Hastanesi', 'Kahramanmaraş', 'Pazarcık', 'state_hospital'),
    ('Kahramanmaraş Türkoğlu Dr. Kemal Beyazıt Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Kahramanmaraş', 'Türkoğlu', 'state_hospital'),
    ('Karab�k Sa�l�k Bakanl��� Karab�k �niversitesi Karab�k E�itim Ve Ara�t�rma Hastanesi', 'Karabük', 'Merkez', 'state_hospital'),
    ('Karab�k Safranbolu Devlet Hastanesi', 'Karabük', 'Safranbolu', 'state_hospital'),
    ('Karab�k Yenice Devlet Hastanesi', 'Karabük', 'Yen�ce', 'state_hospital'),
    ('Karaman Ermenek Devlet Hastanesi', 'Karaman', 'Ermenek', 'state_hospital'),
    ('Karaman Devlet Hastanesi', 'Karaman', 'Merkez', 'state_hospital'),
    ('Kars Ka��zman Devlet Hastanesi', 'Kars', 'Ka�ızman', 'state_hospital'),
    ('Kars Devlet Hastanesi', 'Kars', 'Merkez', 'state_hospital'),
    ('Kars Sar�kam�� Devlet Hastanesi', 'Kars', 'Sarıkamı�', 'state_hospital'),
    ('Kars Selim �l�e Hastanesi', 'Kars', 'Sel�m', 'state_hospital'),
    ('Kastamonu Ara� �l�e Devlet Hastanesi', 'Kastamonu', 'Ara�', 'state_hospital'),
    ('Kastamonu Azdavay �l�e Hastanesi', 'Kastamonu', 'Azdavay', 'state_hospital'),
    ('Kastamonu Bozkurt Devlet Hastanesi', 'Kastamonu', 'Bozkurt', 'state_hospital'),
    ('Kastamonu Cide Devlet Hastanesi', 'Kastamonu', 'C�de', 'state_hospital'),
    ('Kastamonu Daday Devlet Hastanesi', 'Kastamonu', 'Daday', 'state_hospital'),
    ('Kastamonu Devrekani Devlet Hastanesi', 'Kastamonu', 'Devrekan�', 'state_hospital'),
    ('Kastamonu Dr. M�nif �slamo�lu Devlet Hastanesi', 'Kastamonu', 'Merkez', 'state_hospital'),
    ('Kastamonu Rehabilitasyon Merkezi', 'Kastamonu', 'Merkez', 'state_hospital'),
    ('Kastamonu Ta�k�pr� Devlet Hastanesi', 'Kastamonu', 'Ta�k�pr�', 'state_hospital'),
    ('Kastamonu Tosya Devlet Hastanesi', 'Kastamonu', 'Tosya', 'state_hospital'),
    ('Kastamonu �nebolu Devlet Hastanesi', 'Kastamonu', '�nebolu', 'state_hospital'),
    ('Kayseri B�nyan Devlet Hastanesi', 'Kayseri', 'B�nyan', 'state_hospital'),
    ('Kayseri Develi Devlet Hastanesi', 'Kayseri', 'Devel�', 'state_hospital'),
    ('Kayseri E�itim Ve Ara�t�rma Hastanesi', 'Kayseri', 'Kocas�nan', 'state_hospital'),
    ('Kayseri P�narba�� �l�e Hastanesi', 'Kayseri', 'Pınarba�ı', 'state_hospital'),
    ('Kayseri Tomarza Devlet Hastanesi', 'Kayseri', 'Tomarza', 'state_hospital'),
    ('Kayseri Yahyal� Devlet Hastanesi', 'Kayseri', 'Yahyalı', 'state_hospital'),
    ('Kayseri Ye�ilhisaril�e Devlet Hastanesi', 'Kayseri', 'Ye��lh�sar', 'state_hospital'),
    ('Kayseri �ncesu �l�e Hastanesi', 'Kayseri', '�ncesu', 'state_hospital'),
    ('K�r�kkale Y�ksek �htisas Hastanesi', 'Kırıkkale', 'Merkez', 'state_hospital'),
    ('K�rklareli Babaeski Devlet Hastanesi', 'Kırklareli', 'Babaesk�', 'state_hospital'),
    ('K�rklareli L�leburgaz Devlet Hastanesi', 'Kırklareli', 'L�leburgaz', 'state_hospital'),
    ('K�rklareli Devlet Hastanesi', 'Kırklareli', 'Merkez', 'state_hospital'),
    ('K�rklareli P�narhisar Devlet Hastanesi', 'Kırklareli', 'Pınarh�sar', 'state_hospital'),
    ('K�rklareli Vize Devlet Hastanesi', 'Kırklareli', 'V�ze', 'state_hospital'),
    ('K�r�ehir Kaman Devlet Hastanesi', 'Kırşehir', 'Kaman', 'state_hospital'),
    ('K�r�ehir Ahi Evran �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Kırşehir', 'Merkez', 'state_hospital'),
    ('K�r�ehir Mucur Devlet Hastanesi', 'Kırşehir', 'Mucur', 'state_hospital'),
    ('Kilis Devlet Hastanesi', 'Kilis', 'Merkez', 'state_hospital'),
    ('Kocaeli Dar�ca Farabi Devlet Hastanesi', 'Kocaeli', 'Darıca', 'state_hospital'),
    ('Kocaeli Derince E�itim Ve Ara�t�rma Hastanesi', 'Kocaeli', 'Der�nce', 'state_hospital'),
    ('Kocaeli Gebze Fatih Devlet Hastanesi', 'Kocaeli', 'Gebze', 'state_hospital'),
    ('Kocaeli G�lc�k Necati �elik Devlet Hastanesi', 'Kocaeli', 'G�lc�k', 'state_hospital'),
    ('Kocaeli Kand�ra Kaz�m Din� Devlet Hastanesi', 'Kocaeli', 'Kandıra', 'state_hospital'),
    ('Kocaeli Karam�rsel Devlet Hastanesi', 'Kocaeli', 'Karam�rsel', 'state_hospital'),
    ('Kocaeli K�rfez Devlet Hastanesi', 'Kocaeli', 'K�rfez', 'state_hospital'),
    ('Kocaeli Devlet Hastanesi', 'Kocaeli', '�zm�t', 'state_hospital'),
    ('Kocaeli �zmit Seka Devlet Hastanesi', 'Kocaeli', '�zm�t', 'state_hospital'),
    ('Konya Ak�ehir Devlet Hastanesi', 'Konya', 'Ak�eh�r', 'state_hospital'),
    ('Konya Bey�ehir Devlet Hastanesi', 'Konya', 'Bey�eh�r', 'state_hospital'),
    ('Konya Bozk�r Devlet Hastanesi', 'Konya', 'Bozkır', 'state_hospital'),
    ('Konya Cihanbeyli Devlet Hastanesi', 'Konya', 'C�hanbeyl�', 'state_hospital'),
    ('Konya Do�anhisar Devlet Hastanesi', 'Konya', 'Do�anh�sar', 'state_hospital'),
    ('Konya Ere�li Devlet Hastanesi', 'Konya', 'Ere�l�', 'state_hospital'),
    ('Konya Hadim Devlet Hastanesi', 'Konya', 'Had�m', 'state_hospital'),
    ('Konya H�y�k Devlet Hastanesi', 'Konya', 'H�y�k', 'state_hospital'),
    ('Konya Dr. Vefa Tan�r Ilg�n Devlet Hastanesi', 'Konya', 'Ilgın', 'state_hospital'),
    ('Konya Kad�nhan� Refik Saime Koyuncu Devlet Hastanesi', 'Konya', 'Kadınhanı', 'state_hospital'),
    ('Konya Karap�nar Devlet Hastanesi', 'Konya', 'Karapınar', 'state_hospital'),
    ('Konya Kulu Devlet Hastanesi', 'Konya', 'Kulu', 'state_hospital'),
    ('Konya E�itim Ve Ara�t�rma Hastanesi', 'Konya', 'Meram', 'state_hospital'),
    ('Konya Saray�n� Devlet Hastanesi', 'Konya', 'Saray�n�', 'state_hospital'),
    ('Konya Beyhekim Devlet Hastanesi', 'Konya', 'Sel�uklu', 'state_hospital'),
    ('Konya Dr. Faruk S�kan Do�um Ve �ocuk Bak�mevi', 'Konya', 'Sel�uklu', 'state_hospital'),
    ('Konya Numune Hastanesi', 'Konya', 'Sel�uklu', 'state_hospital'),
    ('Konya Seydi�ehir Devlet Hastanesi', 'Konya', 'Seyd��eh�r', 'state_hospital'),
    ('Konya Yunak Hac� �zzet Baysal Devlet Hastanesi', 'Konya', 'Yunak', 'state_hospital'),
    ('Konya �umra Devlet Hastanesi', 'Konya', '�umra', 'state_hospital'),
    ('K�tahya Emet Devlet Hastanesi', 'Kütahya', 'Emet', 'state_hospital'),
    ('K�tahya Gediz Devlet Hastanesi', 'Kütahya', 'Ged�z', 'state_hospital'),
    ('K�tahya D.P.�. Evliya �elebi E�itim Ve Ara�t�rma Hastanesi', 'Kütahya', 'Merkez', 'state_hospital'),
    ('K�tahya Yoncal� Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Kütahya', 'Merkez', 'state_hospital'),
    ('K�tahya Do�.Dr.�smail Karakuyu Simav Devlet Hastanesi', 'Kütahya', 'S�mav', 'state_hospital'),
    ('K�tahya Do�.Dr. Mustafa Kalemli Tav�anl� Devlet Hastanesi', 'Kütahya', 'Tav�anlı', 'state_hospital'),
    ('Malatya Akçadağ 75.Yıl Devlet Hastanesi', 'Malatya', 'Akçadağ', 'state_hospital'),
    ('Malatya Arapgir İlçe Hastanesi', 'Malatya', 'Arapkir', 'state_hospital'),
    ('Malatya Darende Hulusi Efendi Devlet Hastanesi', 'Malatya', 'Darende', 'state_hospital'),
    ('Malatya Doğanşehir Devlet Hastanesi', 'Malatya', 'Doğanşehir', 'state_hospital'),
    ('Malatya Hekimhan Devlet Hastanesi', 'Malatya', 'Hekimhan', 'state_hospital'),
    ('Malatya Devlet Hastanesi', 'Malatya', 'Merkez', 'state_hospital'),
    ('Malatya Pötürge Devlet Hastanesi', 'Malatya', 'Pötürge', 'state_hospital'),
    ('Malatya Yeşilyurt Hasan Çalık Devlet Hastanesi', 'Malatya', 'Yeşilyurt', 'state_hospital'),
    ('Manisa Akhisar Devlet Hastanesi', 'Manisa', 'Akh�sar', 'state_hospital'),
    ('Manisa Ala�ehir Devlet Hastanesi', 'Manisa', 'Ala�eh�r', 'state_hospital'),
    ('Manisa Demirci Devlet Hastanesi', 'Manisa', 'Dem�rc�', 'state_hospital'),
    ('Manisa G�rdes Devlet Hastanesi', 'Manisa', 'G�rdes', 'state_hospital'),
    ('Manisa K�rka�a� Devlet Hastanesi', 'Manisa', 'Kırka�a�', 'state_hospital'),
    ('Manisa Kula Devlet Hastanesi', 'Manisa', 'Kula', 'state_hospital'),
    ('Manisa Devlet Hastanesi', 'Manisa', 'Merkez', 'state_hospital'),
    ('Manisa Merkezefendi Devlet Hastanesi', 'Manisa', 'Merkez', 'state_hospital'),
    ('Manisa Ruh Sa�l��� Ve Hastal�klar� Hastanesi', 'Manisa', 'Merkez', 'state_hospital'),
    ('Manisa Salihli Devlet Hastanesi', 'Manisa', 'Sal�hl�', 'state_hospital'),
    ('Manisa Sar�g�l Devlet Hastanesi', 'Manisa', 'Sarıg�l', 'state_hospital'),
    ('Manisa Saruhanl� Devlet Hastanesi', 'Manisa', 'Saruhanlı', 'state_hospital'),
    ('Manisa Selendi Devlet Hastanesi', 'Manisa', 'Selend�', 'state_hospital'),
    ('Manisa Soma Devlet Hastanesi', 'Manisa', 'Soma', 'state_hospital'),
    ('Manisa Turgutlu Devlet Hastanesi', 'Manisa', 'Turgutlu', 'state_hospital'),
    ('Mardin Darge�it �l�e Hastanesi', 'Mardin', 'Darge��t', 'state_hospital'),
    ('Mardin Derik Devlet Hastanesi', 'Mardin', 'Der�k', 'state_hospital'),
    ('Mardin K�z�ltepe Devlet Hastanesi', 'Mardin', 'Kızıltepe', 'state_hospital'),
    ('Mardin Maz�da�� �l�e Hastanesi', 'Mardin', 'Mazıda�ı', 'state_hospital'),
    ('Mardin Devlet Hastanesi', 'Mardin', 'Merkez', 'state_hospital'),
    ('Mardin Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Mardin', 'Merkez', 'state_hospital'),
    ('Mardin Midyat Devlet Hastanesi', 'Mardin', 'M�dyat', 'state_hospital'),
    ('Mardin Nusaybin Devlet Hastanesi', 'Mardin', 'Nusayb�n', 'state_hospital'),
    ('Mardin Savur �l�e Hastanesi', 'Mardin', 'Savur', 'state_hospital'),
    ('Mersin Devlet Hastanesi', 'Mersin', 'Akdeniz', 'state_hospital'),
    ('Mersin Toros Devlet Hastanesi', 'Mersin', 'Akdeniz', 'state_hospital'),
    ('Mersin Anamur Devlet Hastanesi', 'Mersin', 'Anamur', 'state_hospital'),
    ('Mersin Aydıncık Devlet Hastanesi', 'Mersin', 'Aydıncık', 'state_hospital'),
    ('Mersin Bozyazı Devlet Hastanesi', 'Mersin', 'Bozyazı', 'state_hospital'),
    ('Mersin Erdemli Devlet Hastanesi', 'Mersin', 'Erdemli', 'state_hospital'),
    ('Mersin Gülnar Devlet Hastanesi', 'Mersin', 'Gülnar', 'state_hospital'),
    ('Mersin Mut Devlet Hastanesi', 'Mersin', 'Mut', 'state_hospital'),
    ('Mersin Silifke Devlet Hastanesi', 'Mersin', 'Silifke', 'state_hospital'),
    ('Mersin Tarsus Devlet Hastanesi', 'Mersin', 'Tarsus', 'state_hospital'),
    ('Mersin Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Mersin', 'Toroslar', 'state_hospital'),
    ('Mu�la Bodrum Devlet Hastanesi', 'Muğla', 'Bodrum', 'state_hospital'),
    ('Mu�la Dalaman Devlet Hastanesi', 'Muğla', 'Dalaman', 'state_hospital'),
    ('Mu�la Dat�a Devlet Hastanesi', 'Muğla', 'Dat�a', 'state_hospital'),
    ('Mu�la Fethiye Devlet Hastanesi', 'Muğla', 'Feth�ye', 'state_hospital'),
    ('Mu�la K�yce�iz Devlet Hastanesi', 'Muğla', 'K�yce��z', 'state_hospital'),
    ('Mu�la Marmaris Devlet Hastanesi', 'Muğla', 'Marmar�s', 'state_hospital'),
    ('Mu�la T.C.Sa�l�k Bakanl��� Mu�la S�tk� Ko�man �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Muğla', 'Merkez', 'state_hospital'),
    ('Mu�la Milas 75.Y�l Devlet Hastanesi', 'Muğla', 'M�las', 'state_hospital'),
    ('Mu�la Ortaca Devlet Hastanesi', 'Muğla', 'Ortaca', 'state_hospital'),
    ('Mu�la Yata�an Devlet Hastanesi', 'Muğla', 'Yata�an', 'state_hospital'),
    ('Mu� Bulan�k Devlet Hastanesi', 'Muş', 'Bulanık', 'state_hospital'),
    ('Mu� Hask�y Devlet Hastanesi', 'Muş', 'Hask�y', 'state_hospital'),
    ('Mu� Korkut �l�e Hastanesi', 'Muş', 'Korkut', 'state_hospital'),
    ('Mu� Malazgirt Devlet Hastanesi', 'Muş', 'Malazg�rt', 'state_hospital'),
    ('Mu� Devlet Hastanesi', 'Muş', 'Merkez', 'state_hospital'),
    ('Mu� Varto Devlet Hastanesi', 'Muş', 'Varto', 'state_hospital'),
    ('Nev�ehir Dr.�.�evki Atasagun Devlet Hastanesi', 'Nevşehir', 'Merkez', 'state_hospital'),
    ('Nev�ehir �rg�p Devlet Hastanesi', 'Nevşehir', '�rg�p', 'state_hospital'),
    ('Ni�de Bor Devlet Hastanesi', 'Niğde', 'Bor', 'state_hospital'),
    ('Ni�de Devlet Hastanesi', 'Niğde', 'Merkez', 'state_hospital'),
    ('Ni�de Uluk��la �l�e Hastanesi', 'Niğde', 'Ulukı�la', 'state_hospital'),
    ('Ni�de �iftlik �l�e Hastanesi', 'Niğde', '��ftl�k', 'state_hospital'),
    ('Ordu Akku� Devlet Hastanesi', 'Ordu', 'Akku�', 'state_hospital'),
    ('Ordu Aybast� Devlet Hastanesi', 'Ordu', 'Aybastı', 'state_hospital'),
    ('Ordu Fatsa Devlet Hastanesi', 'Ordu', 'Fatsa', 'state_hospital'),
    ('Ordu G�lk�y Devlet Hastanesi', 'Ordu', 'G�lk�y', 'state_hospital'),
    ('Ordu G�rgentepe Devlet Hastanesi', 'Ordu', 'G�rgentepe', 'state_hospital'),
    ('Ordu Korgan Devlet Hastanesi', 'Ordu', 'Korgan', 'state_hospital'),
    ('Ordu Kumru Devlet Hastanesi', 'Ordu', 'Kumru', 'state_hospital'),
    ('Ordu Devlet Hastanesi', 'Ordu', 'Merkez', 'state_hospital'),
    ('Ordu Sa�l�k Bakanl���-ordu �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Ordu', 'Merkez', 'state_hospital'),
    ('Ordu Ulubey Devlet Hastanesi', 'Ordu', 'Ulubey', 'state_hospital'),
    ('Ordu �nye Devlet Hastanesi', 'Ordu', '�nye', 'state_hospital'),
    ('Osmaniye D�zi�i Devlet Hastanesi', 'Osmaniye', 'D�z���', 'state_hospital'),
    ('Osmaniye Kadirli Devlet Hastanesi', 'Osmaniye', 'Kad�rl�', 'state_hospital'),
    ('Osmaniye Devlet Hastanesi', 'Osmaniye', 'Merkez', 'state_hospital'),
    ('Rize F�nd�kl� B�lge Guatr Ara�t�rma Ve Tedavi Merkezi', 'Rize', 'Fındıklı', 'state_hospital'),
    ('Rize G�neysu Tenzile Erdo�an �l�e Hastanesi', 'Rize', 'G�neysu', 'state_hospital'),
    ('Rize Devlet Hastanesi', 'Rize', 'Merkez', 'state_hospital'),
    ('Rize T.C. Sa�l�k Bakanl��� Recep Tayyip Erdo�an �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Rize', 'Merkez', 'state_hospital'),
    ('Rize Ka�kar Devlet Hastanesi', 'Rize', 'Pazar', 'state_hospital'),
    ('Rize �shako�lu �ayeli Devlet Hastanesi', 'Rize', '�ayel�', 'state_hospital'),
    ('Sakarya Do�um Ve �ocuk Bak�mevi', 'Sakarya', 'Adapazarı', 'state_hospital'),
    ('Sakarya Sa�l�k Bakanl��� Sakarya �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Sakarya', 'Adapazarı', 'state_hospital'),
    ('Sakarya Yenikent Devlet Hastanesi', 'Sakarya', 'Adapazarı', 'state_hospital'),
    ('Sakarya Akyaz� Devlet Hastanesi', 'Sakarya', 'Akyazı', 'state_hospital'),
    ('Sakarya Toyotasa Acil Yard�m Hastanesi', 'Sakarya', 'Ar�f�ye', 'state_hospital'),
    ('Sakarya Ferizli �l�e Hastanesi', 'Sakarya', 'Fer�zl�', 'state_hospital'),
    ('Sakarya Geyve Devlet Hastanesi', 'Sakarya', 'Geyve', 'state_hospital'),
    ('Sakarya Hendek Devlet Hastanesi', 'Sakarya', 'Hendek', 'state_hospital'),
    ('Sakarya Karasu Devlet Hastanesi', 'Sakarya', 'Karasu', 'state_hospital'),
    ('Sakarya Kaynarca �l�e Hastanesi', 'Sakarya', 'Kaynarca', 'state_hospital'),
    ('Sakarya Kocaali �l�e Hastanesi', 'Sakarya', 'Kocaal�', 'state_hospital'),
    ('Sakarya Pamukova Devlet Hastanesi', 'Sakarya', 'Pamukova', 'state_hospital'),
    ('Sakarya Sapanca �l�e Hastanesi', 'Sakarya', 'Sapanca', 'state_hospital'),
    ('Samsun 19 May�s �l�e (Engiz) Hastanesi', 'Samsun', '19mayıs', 'state_hospital'),
    ('Samsun Ala�am Devlet Hastanesi', 'Samsun', 'Ala�am', 'state_hospital'),
    ('Samsun Asarc�k �l�e Hastanesi', 'Samsun', 'Asarcık', 'state_hospital'),
    ('Samsun Ayvac�k Devlet Hastanesi', 'Samsun', 'Ayvacık', 'state_hospital'),
    ('Samsun Bafra Devlet Hastanesi', 'Samsun', 'Bafra', 'state_hospital'),
    ('Samsun Havza Devlet Hastanesi', 'Samsun', 'Havza', 'state_hospital'),
    ('Samsun Kavak Devlet Hastanesi', 'Samsun', 'Kavak', 'state_hospital'),
    ('Samsun Ladik Devlet Hastanesi', 'Samsun', 'Lad�k', 'state_hospital'),
    ('Samsun Sal�pazar� �l�e Hastanesi', 'Samsun', 'Salıpazarı', 'state_hospital'),
    ('Samsun Terme Devlet Hastanesi', 'Samsun', 'Terme', 'state_hospital'),
    ('Samsun Vezirk�pr� Devlet Hastanesi', 'Samsun', 'Vez�rk�pr�', 'state_hospital'),
    ('Samsun �ar�amba Devlet Hastanesi', 'Samsun', '�ar�amba', 'state_hospital'),
    ('Samsun E�itim Ve Ara�t�rma Hastanesi', 'Samsun', '�lkadım', 'state_hospital'),
    ('Samsun Fiziksel T�p Rehabilitasyon Hastal�klar� Hastanesi', 'Samsun', '�lkadım', 'state_hospital'),
    ('Samsun Gazi Devlet Hastanesi', 'Samsun', '�lkadım', 'state_hospital'),
    ('Samsun G���s Hastal�klar� Ve G���s Cerrahisi Hastanesi', 'Samsun', '�lkadım', 'state_hospital'),
    ('Samsun Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Samsun', '�lkadım', 'state_hospital'),
    ('Samsun Ruh Sa�l��� Ve Hastal�klar� Hastanesi', 'Samsun', '�lkadım', 'state_hospital'),
    ('Siirt Baykan Devlet Hastanesi', 'Siirt', 'Baykan', 'state_hospital'),
    ('Siirt Eruh �l�e Hastanesi', 'Siirt', 'Eruh', 'state_hospital'),
    ('Siirt Kurtalan Devlet Hastanesi', 'Siirt', 'Kurtalan', 'state_hospital'),
    ('Siirt Devlet Hastanesi', 'Siirt', 'Merkez', 'state_hospital'),
    ('Siirt Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Siirt', 'Merkez', 'state_hospital'),
    ('Siirt Pervari �l�e Hastanesi', 'Siirt', 'Pervar�', 'state_hospital'),
    ('Sinop Ayanc�k Devlet Hastanesi', 'Sinop', 'Ayancık', 'state_hospital'),
    ('Sinop Boyabat 75.Y�l Devlet Hastanesi', 'Sinop', 'Boyabat', 'state_hospital'),
    ('Sinop Dura�an Devlet Hastanesi', 'Sinop', 'Dura�an', 'state_hospital'),
    ('Sinop Gerze Devlet Hastanesi', 'Sinop', 'Gerze', 'state_hospital'),
    ('Sinop Atat�rk Devlet Hastanesi', 'Sinop', 'Merkez', 'state_hospital'),
    ('Sinop T�rkeli Devlet Hastanesi', 'Sinop', 'T�rkel�', 'state_hospital'),
    ('�anl�urfa Ak�akale Devlet Hastanesi', 'Şanlıurfa', 'Ak�akale', 'state_hospital'),
    ('�anl�urfa Bozova �l�e Hastanesi', 'Şanlıurfa', 'Bozova', 'state_hospital'),
    ('�anl�urfa Birecik Devlet Hastanesi', 'Şanlıurfa', 'B�rec�k', 'state_hospital'),
    ('�anl�urfa Ceylanp�nar Devlet Hastanesi', 'Şanlıurfa', 'Ceylanpınar', 'state_hospital'),
    ('�anl�urfa Halfeti �l�e Hastanesi', 'Şanlıurfa', 'Halfet�', 'state_hospital'),
    ('�anl�urfa Harran Devlet Hastanesi', 'Şanlıurfa', 'Harran', 'state_hospital'),
    ('�anl�urfa Hilvan Devlet Hastanesi', 'Şanlıurfa', 'H�lvan', 'state_hospital'),
    ('�anl�urfa Bal�kl�g�l Devlet Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('�anl�urfa E�itim Ve Ara�t�rma Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('�anl�urfa Kad�n Hastal�klar� Ve Do�um Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('�anl�urfa �ocuk Hastal�klar� Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('�anl�urfa Suru� Devlet Hastanesi', 'Şanlıurfa', 'Suru�', 'state_hospital'),
    ('�anl�urfa Siverek Devlet Hastanesi', 'Şanlıurfa', 'S�verek', 'state_hospital'),
    ('�anl�urfa Viran�ehir Devlet Hastanesi', 'Şanlıurfa', 'V�ran�eh�r', 'state_hospital'),
    ('Tekirda� Hayrabolu Devlet Hastanesi', 'Tekirdağ', 'Hayrabolu', 'state_hospital'),
    ('Tekirda� Marmara Ere�lisi �l�e Devlet Hastanesi', 'Tekirdağ', 'M.ere�l�s�', 'state_hospital'),
    ('Tekirda� Malkara Devlet Hastanesi', 'Tekirdağ', 'Malkara', 'state_hospital'),
    ('Tekirda� Devlet Hastanesi', 'Tekirdağ', 'Merkez', 'state_hospital'),
    ('Tekirda� Muratl� Devlet Hastanesi', 'Tekirdağ', 'Muratlı', 'state_hospital'),
    ('Tekirda� Saray Devlet Hastanesi', 'Tekirdağ', 'Saray', 'state_hospital'),
    ('Tekirda� �ark�y Devlet Hastanesi', 'Tekirdağ', '�ark�y', 'state_hospital'),
    ('Tekirda� �erkezk�y Devlet Hastanesi', 'Tekirdağ', '�erkezk�y', 'state_hospital'),
    ('Tekirda� �orlu Devlet Hastanesi', 'Tekirdağ', '�orlu', 'state_hospital'),
    ('Tokat Almus �l�e Hastanesi', 'Tokat', 'Almus', 'state_hospital'),
    ('Tokat Erbaa Devlet Hastanesi', 'Tokat', 'Erbaa', 'state_hospital'),
    ('Tokat Devlet Hastanesi', 'Tokat', 'Merkez', 'state_hospital'),
    ('Tokat Ruh Sa�l��� Ve Hastal�klar� Hastanesi', 'Tokat', 'Merkez', 'state_hospital'),
    ('Tokat Niksar Devlet Hastanesi', 'Tokat', 'N�ksar', 'state_hospital'),
    ('Tokat Re�adiye Devlet Hastanesi', 'Tokat', 'Re�ad�ye', 'state_hospital'),
    ('Tokat Turhal Devlet Hastanesi', 'Tokat', 'Turhal', 'state_hospital'),
    ('Tokat Zile Devlet Hastanesi', 'Tokat', 'Z�le', 'state_hospital'),
    ('Trabzon Ak�aabat Ha�kal� Baba Devlet Hastanesi', 'Trabzon', 'Ak�aabat', 'state_hospital'),
    ('Trabzon Arakl� Bayram Halil Devlet Hastanesi', 'Trabzon', 'Araklı', 'state_hospital'),
    ('Trabzon Ma�ka �mer Burhano�lu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Ma�ka', 'state_hospital'),
    ('Trabzon Ahi Evren G���s Kalp Ve Damar Cerrahisi E�itim Ve Ara�t�rma Hastanesi', 'Trabzon', 'Merkez', 'state_hospital'),
    ('Trabzon Fatih Devlet Hastanesi', 'Trabzon', 'Merkez', 'state_hospital'),
    ('Trabzon Kanuni E�itim Ve Ara�t�rma Hastanesi', 'Trabzon', 'Merkez', 'state_hospital'),
    ('Trabzon Yavuz Selim Kemik Hastal�klar� Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Merkez', 'state_hospital'),
    ('Trabzon Of Devlet Hastanesi', 'Trabzon', 'Of', 'state_hospital'),
    ('Trabzon S�rmene Devlet Hastanesi', 'Trabzon', 'S�rmene', 'state_hospital'),
    ('Trabzon Tonya Devlet Hastanesi', 'Trabzon', 'Tonya', 'state_hospital'),
    ('Trabzon Vakf�kebir Devlet Hastanesi', 'Trabzon', 'Vakfıkeb�r', 'state_hospital'),
    ('Trabzon Atak�y Ruh Ve Sinir Hastal�klar� Hastanesi', 'Trabzon', '�aykara', 'state_hospital'),
    ('Tunceli Devlet Hastanesi', 'Tunceli', 'Merkez', 'state_hospital'),
    ('U�ak Banaz Devlet Hastanesi', 'Uşak', 'Banaz', 'state_hospital'),
    ('U�ak E�me Devlet Hastanesi', 'Uşak', 'E�me', 'state_hospital'),
    ('U�ak Devlet Hastanesi', 'Uşak', 'Merkez', 'state_hospital'),
    ('U�ak Sivasl� Devlet Hastanesi', 'Uşak', 'S�vaslı', 'state_hospital'),
    ('Van Bah�esaray �l�e Hastanesi', 'Van', 'Bah�esaray', 'state_hospital'),
    ('Van Ba�kale Devlet Hastanesi', 'Van', 'Ba�kale', 'state_hospital'),
    ('Van Erci� Devlet Hastanesi', 'Van', 'Erc��', 'state_hospital'),
    ('Van Geva� Devlet Hastanesi', 'Van', 'Geva�', 'state_hospital'),
    ('Van B�lge E�itim Ve Ara�t�rma Hastanesi', 'Van', 'Merkez', 'state_hospital'),
    ('Van Muradiye Devlet Hastanesi', 'Van', 'Murad�ye', 'state_hospital'),
    ('Van �ald�ran �l�e Hastanesi', 'Van', '�aldıran', 'state_hospital'),
    ('Van �atak �l�e Hastanesi', 'Van', '�atak', 'state_hospital'),
    ('Van Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Van', '�pekyolu', 'state_hospital'),
    ('Van �zalp Devlet Hastanesi', 'Van', '�zalp', 'state_hospital'),
    ('Yalova Devlet Hastanesi', 'Yalova', 'Merkez', 'state_hospital'),
    ('Yalova ��narc�k Devlet Hastanesi', 'Yalova', '�ınarcık', 'state_hospital'),
    ('Yozgat Akda�madeni Devlet Hastanesi', 'Yozgat', 'Akda�maden�', 'state_hospital'),
    ('Yozgat Bo�azl�yan Devlet Hastanesi', 'Yozgat', 'Bo�azlıyan', 'state_hospital'),
    ('Yozgat Devlet Hastanesi', 'Yozgat', 'Merkez', 'state_hospital'),
    ('Yozgat Saraykent �l�e Hastanesi', 'Yozgat', 'Saraykent', 'state_hospital'),
    ('Yozgat Sar�kaya Devlet Hastanesi', 'Yozgat', 'Sarıkaya', 'state_hospital'),
    ('Yozgat Sorgun Devlet Hastanesi', 'Yozgat', 'Sorgun', 'state_hospital'),
    ('Yozgat Yerk�y Devlet Hastanesi', 'Yozgat', 'Yerk�y', 'state_hospital'),
    ('Yozgat �efaatli Devlet Hastanesi', 'Yozgat', '�efaatl�', 'state_hospital'),
    ('Yozgat �ekerek Devlet Hastanesi', 'Yozgat', '�ekerek', 'state_hospital'),
    ('Zonguldak Alapl� Devlet Hastanesi', 'Zonguldak', 'Alaplı', 'state_hospital'),
    ('Zonguldak Devrek Devlet Hastanesi', 'Zonguldak', 'Devrek', 'state_hospital'),
    ('Zonguldak Karadeniz Ere�li Devlet Hastanesi', 'Zonguldak', 'Ere�l�', 'state_hospital'),
    ('Zonguldak G�k�ebey �l�e Hastanesi', 'Zonguldak', 'G�k�ebey', 'state_hospital'),
    ('Zonguldak Atat�rk Devlet Hastanesi', 'Zonguldak', 'Merkez', 'state_hospital'),
    ('Zonguldak Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Zonguldak', 'Merkez', 'state_hospital'),
    ('Zonguldak Uzun Mehmet G���s Ve Meslek Hastal�klar� Hastanesi', 'Zonguldak', 'Merkez', 'state_hospital'),
    ('Zonguldak �aycuma Devlet Hastanesi', 'Zonguldak', '�aycuma', 'state_hospital')
)
insert into public.hospitals (name, city, district, hospital_type)
select name, city, district, hospital_type::public.hospital_type
from hospital_seed s
where not exists (
  select 1 from public.hospitals h
  where lower(h.name)=lower(s.name) and h.city=s.city and h.district=s.district
);

with hospital_seed(name, city, district) as (
  values
    ('Adana Ceyhan Devlet Hastanesi', 'Adana', 'Ceyhan'),
    ('Adana Dr. Ekrem Tok Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Adana', 'Çukurova'),
    ('Adana İmamoğlu Devlet Hastanesi', 'Adana', 'İmamoğlu'),
    ('Adana Karaisalı Devlet Hastanesi', 'Adana', 'Karaisalı'),
    ('Adana Kozan Devlet Hastanesi', 'Adana', 'Kozan'),
    ('Adana Pozantı 80.Yıl Devlet Hastanesi', 'Adana', 'Pozantı'),
    ('Adana Çukurova Dr. Aşkım Tüfekçi Devlet Hastanesi', 'Adana', 'Seyhan'),
    ('Adana Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Adana', 'Seyhan'),
    ('Adana Tufanbeyli Devlet Hastanesi', 'Adana', 'Tufanbeyli'),
    ('Adana Devlet Hastanesi', 'Adana', 'Yüreğir'),
    ('Adana Numune Eğitim Ve Araştırma Hastanesi', 'Adana', 'Yüreğir'),
    ('Adıyaman Besni Devlet Hastanesi', 'Adıyaman', 'Besni'),
    ('Adıyaman Çelikhan Devlet Hastanesi', 'Adıyaman', 'Çelikhan'),
    ('Adıyaman Gölbaşı Devlet Hastanesi', 'Adıyaman', 'Gölbaşı'),
    ('Adıyaman Kahta Devlet Hastanesi', 'Adıyaman', 'Kahta'),
    ('Adıyaman T.C. Sağlık Bakanlığı Adıyaman Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Adıyaman', 'Merkez'),
    ('Afyonkarahisar Dr. Halil İbrahim Özsoy Bolvadin Devlet Hastanesi', 'Afyonkarahisar', 'Bolvadin'),
    ('Afyonkarahisar Çay Devlet Hastanesi', 'Afyonkarahisar', 'Çay'),
    ('Afyonkarahisar Dinar Devlet Hastanesi', 'Afyonkarahisar', 'Dinar'),
    ('Afyonkarahisar Emirdağ Devlet Hastanesi', 'Afyonkarahisar', 'Emirdağ'),
    ('Afyonkarahisar İscehisar Devlet Hastanesi', 'Afyonkarahisar', 'İscehisar'),
    ('Afyonkarahisar Devlet Hastanesi', 'Afyonkarahisar', 'Merkez'),
    ('Afyonkarahisar Zübeyde Hanım Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Afyonkarahisar', 'Merkez'),
    ('Afyonkarahisar Sandıklı Devlet Hastanesi', 'Afyonkarahisar', 'Sandıklı'),
    ('Afyonkarahisar Sinanpaşa İlçe Hastanesi', 'Afyonkarahisar', 'Sinanpaşa'),
    ('Afyonkarahisar Şuhut Devlet Hastanesi', 'Afyonkarahisar', 'Şuhut'),
    ('Ağrı Diyadin Devlet Hastanesi', 'Ağrı', 'Diyadin'),
    ('Ağrı Dr. Yaşar Eryılmaz Doğubeyazıt Devlet Hastanesi', 'Ağrı', 'Doğubeyazıt'),
    ('Ağrı Eleşkirt Devlet Hastanesi', 'Ağrı', 'Eleşkirt'),
    ('Ağrı Hamur İlçe Devlet Hastanesi', 'Ağrı', 'Hamur'),
    ('Ağrı Devlet Hastanesi', 'Ağrı', 'Merkez'),
    ('Ağrı Patnos Devlet Hastanesi', 'Ağrı', 'Patnos'),
    ('Ağrı Taşlıçay İlçe Devlet Hastanesi', 'Ağrı', 'Taşlıçay'),
    ('Ağrı Tutak Devlet Hastanesi', 'Ağrı', 'Tutak'),
    ('Aksaray Eskil Devlet Hastanesi', 'Aksaray', 'Esk�l'),
    ('Aksaray G�la�a� �l�e Hastanesi', 'Aksaray', 'G�la�a�'),
    ('Aksaray Devlet Hastanesi', 'Aksaray', 'Merkez'),
    ('Aksaray Ortak�y Devlet Hastanesi', 'Aksaray', 'Ortak�y'),
    ('Amasya Gümüşhacıköy Devlet Hastanesi', 'Amasya', 'Gümüşhacıköy'),
    ('Amasya Sabuncuoğlu Şerefeddin Devlet Hastanesi', 'Amasya', 'Merkez'),
    ('Amasya Merzifon Kara Mustafa Paşa Devlet Hastanesi', 'Amasya', 'Merzifon'),
    ('Amasya Suluova Devlet Hastanesi', 'Amasya', 'Suluova'),
    ('Amasya Taşova Devlet Hastanesi', 'Amasya', 'Taşova'),
    ('Ankara Dışkapı Çocuk Sağlığı Ve Hastalıkları Hematoloji Onkoloji Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Dışkapı Yıldırım Beyazıt Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Dr. Sami Ulus Kadın Doğum Çocuk Sağlığı Ve Hastalıkları Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Dr. Zekai Tahir Burak Kadın Sağlığı Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Fizik Tedavi Ve Rehabilitasyon Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Numune Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Türkiye Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Ulucanlar Göz Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Ulus Devlet Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Beypazarı Devlet Hastanesi', 'Ankara', 'Beypazarı'),
    ('Ankara Atatürk Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Çankaya'),
    ('Ankara Halil Şıvgın Çubuk Devlet Hastanesi', 'Ankara', 'Çubuk'),
    ('Ankara Dr. Hulusi Alataş Elmadağ Devlet Hastanesi', 'Ankara', 'Elmadağ'),
    ('Ankara Prof.Dr. Celal Ertuğ Etimesgut Devlet Hastanesi', 'Ankara', 'Etimesgut'),
    ('Ankara Gölbaşı Hasvak Devlet Hastanesi', 'Ankara', 'Gölbaşı'),
    ('Ankara Haymana Devlet Hastanesi', 'Ankara', 'Haymana'),
    ('Ankara Kazan Hamdi Eriş Devlet Hastanesi', 'Ankara', 'Kazan'),
    ('Ankara Atatürk Göğüs Hastalıkları Ve Göğüs Cerrahisi Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Etlik Zübeyde Hanım Kadın Hastalıkları Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Keçiören Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Meslek Hastalıkları Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Kızılcahamam Devlet Hastanesi', 'Ankara', 'Kızılcahamam'),
    ('Ankara Nallıhan Devlet Hastanesi', 'Ankara', 'Nallıhan'),
    ('Ankara Polatlı Duatepe Devlet Hastanesi', 'Ankara', 'Polatlı'),
    ('Ankara Sincan Dr. Nafiz Körez Devlet Hastanesi', 'Ankara', 'Sincan'),
    ('Ankara Şereflikoçhisar Devlet Hastanesi', 'Ankara', 'Şereflikoçhisar'),
    ('Ankara Dr. Abdurrahman Yurtaslan Onkoloji Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Yenimahalle'),
    ('Ankara Gazi Mustafa Kemal Devlet Hastanesi', 'Ankara', 'Yenimahalle'),
    ('Ankara Yenimahalle Devlet Hastanesi', 'Ankara', 'Yenimahalle'),
    ('Antalya Akseki Devlet Hastanesi', 'Antalya', 'Akseki'),
    ('Antalya Alanya Devlet Hastanesi', 'Antalya', 'Alanya'),
    ('Antalya Demre Devlet Hastanesi', 'Antalya', 'Demre'),
    ('Antalya Elmalı Devlet Hastanesi', 'Antalya', 'Elmalı'),
    ('Antalya Finike Devlet Hastanesi', 'Antalya', 'Finike'),
    ('Antalya Gazipaşa Devlet Hastanesi', 'Antalya', 'Gazipaşa'),
    ('Antalya Kaş Devlet Hastanesi', 'Antalya', 'Kaş'),
    ('Antalya Kemer Devlet Hastanesi', 'Antalya', 'Kemer'),
    ('Antalya Korkuteli Devlet Hastanesi', 'Antalya', 'Korkuteli'),
    ('Antalya Kumluca Devlet Hastanesi', 'Antalya', 'Kumluca'),
    ('Antalya Manavgat Devlet Hastanesi', 'Antalya', 'Manavgat'),
    ('Antalya Atatürk Devlet Hastanesi', 'Antalya', 'Muratpaşa'),
    ('Antalya Eğitim Ve Araştırma Hastanesi', 'Antalya', 'Muratpaşa'),
    ('Antalya Serik Devlet Hastanesi', 'Antalya', 'Serik'),
    ('Ardahan G�le Devlet Hastanesi', 'Ardahan', 'G�le'),
    ('Ardahan Devlet Hastanesi', 'Ardahan', 'Merkez'),
    ('Artvin Arhavi Devlet Hastanesi', 'Artvin', 'Arhavi'),
    ('Artvin Borçka Devlet Hastanesi', 'Artvin', 'Borçka'),
    ('Artvin Hopa Devlet Hastanesi', 'Artvin', 'Hopa'),
    ('Artvin Devlet Hastanesi', 'Artvin', 'Merkez'),
    ('Artvin Şavşat Devlet Hastanesi', 'Artvin', 'Şavşat'),
    ('Artvin Yusufeli Devlet Hastanesi', 'Artvin', 'Yusufeli'),
    ('Aydın Çine Devlet Hastanesi', 'Aydın', 'Çine'),
    ('Aydın Didim Devlet Hastanesi', 'Aydın', 'Didim'),
    ('Aydın Germencik Devlet Hastanesi', 'Aydın', 'Germencik'),
    ('Aydın Kuşadası Devlet Hastanesi', 'Aydın', 'Kuşadası'),
    ('Aydın Atatürk Devlet Hastanesi', 'Aydın', 'Merkez'),
    ('Aydın Devlet Hastanesi', 'Aydın', 'Merkez'),
    ('Aydın Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Aydın', 'Merkez'),
    ('Aydın Nazilli Devlet Hastanesi', 'Aydın', 'Nazilli'),
    ('Aydın Söke Fehime Faik Kocagöz Devlet Hastanesi', 'Aydın', 'Söke'),
    ('Balıkesir Ayvalık Devlet Hastanesi', 'Balıkesir', 'Ayvalık'),
    ('Balıkesir Bandırma Devlet Hastanesi', 'Balıkesir', 'Bandırma'),
    ('Balıkesir Bigadiç Devlet Hastanesi', 'Balıkesir', 'Bigadiç'),
    ('Balıkesir Burhaniye Devlet Hastanesi', 'Balıkesir', 'Burhaniye'),
    ('Balıkesir Dursunbey Devlet Hastanesi', 'Balıkesir', 'Dursunbey'),
    ('Balıkesir Edremit Devlet Hastanesi', 'Balıkesir', 'Edremit'),
    ('Balıkesir Erdek Neyyire Sıtkı Devlet Hastanesi', 'Balıkesir', 'Erdek'),
    ('Balıkesir Gönen Devlet Hastanesi', 'Balıkesir', 'Gönen'),
    ('Balıkesir Havran Devlet Hastanesi', 'Balıkesir', 'Havran'),
    ('Balıkesir İvrindi Devlet Hastanesi', 'Balıkesir', 'İvrindi'),
    ('Balıkesir Manyas Devlet Hastanesi', 'Balıkesir', 'Manyas'),
    ('Balıkesir Atatürk Devlet Hastanesi', 'Balıkesir', 'Merkez'),
    ('Balıkesir Devlet Hastanesi', 'Balıkesir', 'Merkez'),
    ('Balıkesir Göğüs Hastalıkları Hastanesi', 'Balıkesir', 'Merkez'),
    ('Balıkesir Savaştepe Devlet Hastanesi', 'Balıkesir', 'Savaştepe'),
    ('Balıkesir Sındırgı Devlet Hastanesi', 'Balıkesir', 'Sındırgı'),
    ('Balıkesir Susurluk Devlet Hastanesi', 'Balıkesir', 'Susurluk'),
    ('Bart�n Devlet Hastanesi', 'Bartın', 'Merkez'),
    ('Batman Gerc�� Devlet Hastanesi', 'Batman', 'Gerc��'),
    ('Batman Kozluk Devlet Hastanesi', 'Batman', 'Kozluk'),
    ('Batman B�lge Devlet Hastanesi', 'Batman', 'Merkez'),
    ('Batman Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Batman', 'Merkez'),
    ('Batman Sason Devlet Hastanesi', 'Batman', 'Sason'),
    ('Bayburt Devlet Hastanesi', 'Bayburt', 'Merkez'),
    ('Bilecik Bozüyük Devlet Hastanesi', 'Bilecik', 'Bozüyük'),
    ('Bilecik Devlet Hastanesi', 'Bilecik', 'Merkez'),
    ('Bilecik Osmaneli Devlet Hastanesi', 'Bilecik', 'Osmaneli'),
    ('Bilecik Söğüt Devlet Hastanesi', 'Bilecik', 'Söğüt'),
    ('Bingöl Genç Devlet Hastanesi', 'Bingöl', 'Genç'),
    ('Bingöl Karlıova İlçe Hastanesi', 'Bingöl', 'Karlıova'),
    ('Bingöl Devlet Hastanesi', 'Bingöl', 'Merkez'),
    ('Bingöl Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Bingöl', 'Merkez'),
    ('Bingöl Solhan Devlet Hastanesi', 'Bingöl', 'Solhan'),
    ('Bitlis Adilcevaz Onkoloji Hastanesi', 'Bitlis', 'Adilcevaz'),
    ('Bitlis Ahlat Devlet Hastanesi', 'Bitlis', 'Ahlat'),
    ('Bitlis Güroymak Devlet Hastanesi', 'Bitlis', 'Güroymak'),
    ('Bitlis Hizan İlçe Hastanesi', 'Bitlis', 'Hizan'),
    ('Bitlis Devlet Hastanesi', 'Bitlis', 'Merkez'),
    ('Bitlis Mutki İlçe Hastanesi', 'Bitlis', 'Mutki'),
    ('Bitlis Tatvan Devlet Hastanesi', 'Bitlis', 'Tatvan'),
    ('Bolu Gerede Devlet Hastanesi', 'Bolu', 'Gerede'),
    ('Bolu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Bolu', 'Merkez'),
    ('Bolu İzzet Baysal Devlet Hastanesi', 'Bolu', 'Merkez'),
    ('Bolu İzzet Baysal Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Bolu', 'Merkez'),
    ('Bolu Mudurnu İlçe Hastanesi', 'Bolu', 'Mudurnu'),
    ('Burdur Bucak Devlet Hastanesi', 'Burdur', 'Bucak'),
    ('Burdur Gölhisar Devlet Hastanesi', 'Burdur', 'Gölhisar'),
    ('Burdur Devlet Hastanesi', 'Burdur', 'Merkez'),
    ('Burdur Yeşilova Devlet Hastanesi', 'Burdur', 'Yeşilova'),
    ('Bursa Gemlik Muammer Ağım Devlet Hastanesi', 'Bursa', 'Gemlik'),
    ('Bursa İnegöl Devlet Hastanesi', 'Bursa', 'İnegöl'),
    ('Bursa İznik Devlet Hastanesi', 'Bursa', 'İznik'),
    ('Bursa Karacabey Devlet Hastanesi', 'Bursa', 'Karacabey'),
    ('Bursa M.Kemalpaşa Devlet Hastanesi', 'Bursa', 'M.kemalpaşa'),
    ('Bursa Mudanya Şaziye Rüştü Devlet Hastanesi', 'Bursa', 'Mudanya'),
    ('Bursa Dörtçelik Çocuk Hastalıkları Hastanesi', 'Bursa', 'Nilüfer'),
    ('Bursa Orhaneli Devlet Hastanesi', 'Bursa', 'Orhaneli'),
    ('Bursa Orhangazi Devlet Hastanesi', 'Bursa', 'Orhangazi'),
    ('Bursa Ali Osman Sönmez Onkoloji Hastanesi', 'Bursa', 'Osmangazi'),
    ('Bursa Çekirge Devlet Hastanesi', 'Bursa', 'Osmangazi'),
    ('Bursa Devlet Hastanesi', 'Bursa', 'Osmangazi'),
    ('Bursa Dr. Ayten Bozkaya Spastik Çocuklar Hastanesi Ve Rehabilitasyon Merkezi', 'Bursa', 'Osmangazi'),
    ('Bursa Zübeyde Hanım Doğumevi', 'Bursa', 'Osmangazi'),
    ('Bursa Yenişehir Devlet Hastanesi', 'Bursa', 'Yenişehir'),
    ('Bursa Prof.Dr. Türkan Akyol Göğüs Hastalıkları Hastanesi', 'Bursa', 'Yıldırım'),
    ('Bursa Şevket Yılmaz Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım'),
    ('Bursa Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım'),
    ('Çanakkale Ayvacık Devlet Hastanesi', 'Çanakkale', 'Ayvacık'),
    ('Çanakkale Bayramiç Devlet Hastanesi', 'Çanakkale', 'Bayramiç'),
    ('Çanakkale Biga Devlet Hastanesi', 'Çanakkale', 'Biga'),
    ('Çanakkale Çan Devlet Hastanesi', 'Çanakkale', 'Çan'),
    ('Çanakkale Ezine Devlet Hastanesi', 'Çanakkale', 'Ezine'),
    ('Çanakkale Gelibolu Devlet Hastanesi', 'Çanakkale', 'Gelibolu'),
    ('Çanakkale Gökçeada Devlet Hastanesi', 'Çanakkale', 'Gökçeada'),
    ('Çanakkale Lapseki Devlet Hastanesi', 'Çanakkale', 'Lapseki'),
    ('Çanakkale Devlet Hastanesi', 'Çanakkale', 'Merkez'),
    ('Çanakkale Yenice Devlet Hastanesi', 'Çanakkale', 'Yenice'),
    ('Çankırı Çerkeş Devlet Hastanesi', 'Çankırı', 'Çerkeş'),
    ('Çankırı Ilgaz Devlet Hastanesi', 'Çankırı', 'Ilgaz'),
    ('Çankırı Kurşunlu İlçe Hastanesi', 'Çankırı', 'Kurşunlu'),
    ('Çankırı Devlet Hastanesi', 'Çankırı', 'Merkez'),
    ('Çorum Alaca Devlet Hastanesi', 'Çorum', 'Alaca'),
    ('Çorum Bayat Devlet Hastanesi', 'Çorum', 'Bayat'),
    ('Çorum İskilip Devlet Hastanesi', 'Çorum', 'İskilip'),
    ('Çorum Kargı Devlet Hastanesi', 'Çorum', 'Kargı'),
    ('Çorum Mecitözü Devlet Hastanesi', 'Çorum', 'Mecitözü'),
    ('Çorum Göğüs Hastalıkları Hastanesi', 'Çorum', 'Merkez'),
    ('Çorum T.C. Sağlık Bakanlığı Hitit Üniversitesi Çorum Eğitim Ve Araştırma Hastanesi', 'Çorum', 'Merkez'),
    ('Çorum Osmancık Devlet Hastanesi', 'Çorum', 'Osmancık'),
    ('Çorum Sungurlu Devlet Hastanesi', 'Çorum', 'Sungurlu'),
    ('Denizli Acıpayam Devlet Hastanesi', 'Denizli', 'Acıpayam'),
    ('Denizli Buldan Göğüs Hastalıkları Hastanesi', 'Denizli', 'Buldan'),
    ('Denizli Çal Devlet Hastanesi', 'Denizli', 'Çal'),
    ('Denizli Çameli Devlet Hastanesi', 'Denizli', 'Çameli'),
    ('Denizli Çivril Devlet Hastanesi', 'Denizli', 'Çivril'),
    ('Denizli Honaz Devlet Hastanesi', 'Denizli', 'Honaz'),
    ('Denizli Kale Devlet Hastanesi', 'Denizli', 'Kale'),
    ('Denizli Devlet Hastanesi', 'Denizli', 'Merkez'),
    ('Denizli Servergazi Devlet Hastanesi', 'Denizli', 'Merkez'),
    ('Denizli Sarayköy Devlet Hastanesi', 'Denizli', 'Sarayköy'),
    ('Denizli Tavas Devlet Hastanesi', 'Denizli', 'Tavas'),
    ('Diyarbakır Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Bağlar'),
    ('Diyarbakır Bismil Devlet Hastanesi', 'Diyarbakır', 'Bismil'),
    ('Diyarbakır Çermik Devlet Hastanesi', 'Diyarbakır', 'Çermik'),
    ('Diyarbakır Çınar İlçe Hastanesi', 'Diyarbakır', 'Çınar'),
    ('Diyarbakır Dicle İlçe Hastanesi', 'Diyarbakır', 'Dicle'),
    ('Diyarbakır Eğil İlçe Hastanesi', 'Diyarbakır', 'Eğil'),
    ('Diyarbakır Ergani Devlet Hastanesi', 'Diyarbakır', 'Ergani'),
    ('Diyarbakır Hani İlçe Hastanesi', 'Diyarbakır', 'Hani'),
    ('Diyarbakır Eğitim Ve Araştırma Hastanesi', 'Diyarbakır', 'Kayapınar'),
    ('Diyarbakır Kulp İlçe Hastanesi', 'Diyarbakır', 'Kulp'),
    ('Diyarbakır Lice Halis Toprak Vakfı İlçe Hastanesi', 'Diyarbakır', 'Lice'),
    ('Diyarbakır Silvan Dr. Yusuf Azizoğlu Devlet Hastanesi', 'Diyarbakır', 'Silvan'),
    ('Diyarbakır Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Yenişehir'),
    ('Diyarbakır Devlet Hastanesi', 'Diyarbakır', 'Yenişehir'),
    ('D�zce Ak�akoca Devlet Hastanesi', 'Düzce', 'Ak�akoca'),
    ('D�zce Atat�rk Devlet Hastanesi', 'Düzce', 'Merkez'),
    ('Edirne Keşan Devlet Hastanesi', 'Edirne', 'Keşan'),
    ('Edirne Devlet Hastanesi', 'Edirne', 'Merkez'),
    ('Edirne Uzunköprü Devlet Hastanesi', 'Edirne', 'Uzunköprü'),
    ('Elazığ Karakoçan Devlet Hastanesi', 'Elazığ', 'Karakoçan'),
    ('Elazığ Kovancılar Devlet Hastanesi', 'Elazığ', 'Kovancılar'),
    ('Elazığ Maden Devlet Hastanesi', 'Elazığ', 'Maden'),
    ('Elazığ Eğitim Ve Araştırma Hastanesi', 'Elazığ', 'Merkez'),
    ('Elazığ Harput Devlet Hastanesi', 'Elazığ', 'Merkez'),
    ('Elazığ Ruh Sağlıgı Ve Hastalıkları Hastanesi', 'Elazığ', 'Merkez'),
    ('Elazığ Palu Devlet Hastanesi', 'Elazığ', 'Palu'),
    ('Erzincan Mengücek Gazi Eğitim Ve Araştırma Hastanesi', 'Erzincan', 'Mengücek'),
    ('Erzincan Refahiye Dr. Fahrettin Uğur İlçe Hastanesi', 'Erzincan', 'Refahiye'),
    ('Erzincan Tercan Devlet Hastanesi', 'Erzincan', 'Tercan'),
    ('Erzurum Aşkale İlçe Hastanesi', 'Erzurum', 'Aşkale'),
    ('Erzurum Çat İlçe Hastanesi', 'Erzurum', 'Çat'),
    ('Erzurum Hınıs Devlet Hastanesi', 'Erzurum', 'Hınıs'),
    ('Erzurum Horasan Devlet Hastanesi', 'Erzurum', 'Horasan'),
    ('Erzurum İspir Devlet Hastanesi', 'Erzurum', 'İspir'),
    ('Erzurum Karaçoban İlçe Hastanesi', 'Erzurum', 'Karaçoban'),
    ('Erzurum Türk Eczacıları Birliği Karayazı İlçe Hastanesi', 'Erzurum', 'Karayazı'),
    ('Erzurum Oltu Devlet Hastanesi', 'Erzurum', 'Oltu'),
    ('Erzurum Nenehatun Kadın Doğum Hastanesi', 'Erzurum', 'Palandöken'),
    ('Erzurum Pasinler İbrahim Hakkı Devlet Hastanesi', 'Erzurum', 'Pasinler'),
    ('Erzurum Tekman Devlet Hastanesi', 'Erzurum', 'Tekman'),
    ('Erzurum Tortum İlçe Hastanesi', 'Erzurum', 'Tortum'),
    ('Erzurum Bölge Eğitim Ve Araştırma Hastanesi', 'Erzurum', 'Yakutiye'),
    ('Erzurum Palandöken Devlet Hastanesi', 'Erzurum', 'Yakutiye'),
    ('Eskişehir Çifteler Devlet Hastanesi', 'Eskişehir', 'Çifteler'),
    ('Eskişehir Günyüzü İlçe Hastanesi', 'Eskişehir', 'Günyüzü'),
    ('Eskişehir Mahmudiye İlçe Hastanesi', 'Eskişehir', 'Mahmudiye'),
    ('Eskişehir Mihalıççık Gün Sazak İlçe Hastanesi', 'Eskişehir', 'Mihalıççık'),
    ('Eskişehir Devlet Hastanesi', 'Eskişehir', 'Odunpazarı'),
    ('Eskişehir Sivrihisar Devlet Hastanesi', 'Eskişehir', 'Sivrihisar'),
    ('Eskişehir Yunus Emre Devlet Hastanesi', 'Eskişehir', 'Tepebaşı'),
    ('Gaziantep Araban İlçe Hastanesi', 'Gaziantep', 'Araban'),
    ('Gaziantep İslahiye Devlet Hastanesi', 'Gaziantep', 'İslahiye'),
    ('Gaziantep Nizip Devlet Hastanesi', 'Gaziantep', 'Nizip'),
    ('Gaziantep Nurdağı İlçe Hastanesi', 'Gaziantep', 'Nurdağı'),
    ('Gaziantep Oğuzeli İlçe Hastanesi', 'Gaziantep', 'Oğuzeli'),
    ('Gaziantep Dr. Ersin Arslan Devlet Hastanesi', 'Gaziantep', 'Şahinbey'),
    ('Gaziantep 25 Aralık Devlet Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Gaziantep Cengiz Gökçek Kadın Hastalıkları Ve Doğum Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Gaziantep Çocuk Hastalıkları Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Gaziantep Şehitkamil Devlet Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Giresun Alucra İlçe Hastanesi', 'Giresun', 'Alucra'),
    ('Giresun Bulancak Devlet Hastanesi', 'Giresun', 'Bulancak'),
    ('Giresun Dereli İlçe Hastanesi', 'Giresun', 'Dereli'),
    ('Giresun Espiye Devlet Hastanesi', 'Giresun', 'Espiye'),
    ('Giresun Op.Dr. Ergun Özdemir Görele Devlet Hastanesi', 'Giresun', 'Görele'),
    ('Giresun Dr. A.İlhan Özdemir Devlet Hastanesi', 'Giresun', 'Merkez'),
    ('Giresun Dr. Ali Menekşe Göğüs Hastalıkları Hastanesi', 'Giresun', 'Merkez'),
    ('Giresun Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Giresun', 'Merkez'),
    ('Giresun Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Giresun', 'Merkez'),
    ('Giresun Ş.Karahisar Devlet Hastanesi', 'Giresun', 'Şebinkarahisar'),
    ('Giresun Tirebolu Devlet Hastanesi', 'Giresun', 'Tirebolu'),
    ('Giresun Yağlıdere İlçe Hastanesi', 'Giresun', 'Yağlıdere'),
    ('Gümüşhane Kelkit Devlet Hastanesi', 'Gümüşhane', 'Kelkit'),
    ('Gümüşhane Devlet Hastanesi', 'Gümüşhane', 'Merkez'),
    ('Gümüşhane Şiran Devlet Hastanesi', 'Gümüşhane', 'Şiran'),
    ('Hakkari Devlet Hastanesi', 'Hakkâri', 'Merkez'),
    ('Hakkari Şemdinli Devlet Hastanesi', 'Hakkâri', 'Şemdinli'),
    ('Hakkari Yüksekova Devlet Hastanesi', 'Hakkâri', 'Yüksekova'),
    ('Hatay Altınözü Devlet Hastanesi', 'Hatay', 'Altınözü'),
    ('Hatay Antakya Devlet Hastanesi', 'Hatay', 'Antakya'),
    ('Hatay Doğum Ve Çocuk Bakımevi', 'Hatay', 'Antakya'),
    ('Hatay Dörtyol Devlet Hastanesi', 'Hatay', 'Dörtyol'),
    ('Hatay Erzin Devlet Hastanesi', 'Hatay', 'Erzin'),
    ('Hatay Hassa Devlet Hastanesi', 'Hatay', 'Hassa'),
    ('Hatay İskenderun Devlet Hastanesi', 'Hatay', 'İskenderun'),
    ('Hatay Kırıkhan Devlet Hastanesi', 'Hatay', 'Kırıkhan'),
    ('Hatay Reyhanlı Devlet Hastanesi', 'Hatay', 'Reyhanlı'),
    ('Hatay Samandağı Devlet Hastanesi', 'Hatay', 'Samandağ'),
    ('I�d�r Devlet Hastanesi', 'Iğdır', 'Merkez'),
    ('I�d�r Tuzluca Devlet Hastanesi', 'Iğdır', 'Tuzluca'),
    ('Isparta Eğirdir Kemik Eklem Hastalıkları Tedavi Ve Rehabilitasyon Hastanesi', 'Isparta', 'Eğirdir'),
    ('Isparta Devlet Hastanesi', 'Isparta', 'Merkez'),
    ('Isparta Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Isparta', 'Merkez'),
    ('Isparta Şarkikaraağaç Devlet Hastanesi', 'Isparta', 'Şarkikaraağaç'),
    ('Isparta Yalvaç Devlet Hastanesi', 'Isparta', 'Yalvaç'),
    ('İstanbul- (Avrupa)- Arnavutköy Devlet Hastanesi', 'İstanbul', 'Arnavutköy'),
    ('İstanbul- (Anadolu)- Ataşehir- Fatih Sultan Mehmet Eğitim Araştırma Hastanesi', 'İstanbul', 'Ataşehir'),
    ('İstanbul -(Avrupa)- Avcılar Murat Kölük Devlet Hastanesi', 'İstanbul', 'Avcılar'),
    ('İstanbul- (Avrupa)- Bağcılar Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Bağcılar'),
    ('İstanbul- (Avrupa)- Bahçelievler Devlet Hastanesi', 'İstanbul', 'Bahçelievler'),
    ('İstanbul- (Avrupa)- Bahçelievler- Fizik Tedavi Ve Rehabilitasyon Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Bahçelievler'),
    ('İstanbul- (Avrupa)- Bakırköy -Lepra Deri Ve Zührevi Hastalıkları Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Bakırköy Prof.Dr. Mazhar Osman Ruh Sağ. Ve Sinir Hast. Eğt. Ve Araş. Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Bakırköy- Deri Ve Tenasül Hastalıkları Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Bakırköy- Dr. Sadi Konuk Eğitim Araştırma Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Başakşehir Devlet Hastanesi', 'İstanbul', 'Başakşehir'),
    ('İstanbul- (Avrupa)- Bayrampaşa Devlet Hastanesi', 'İstanbul', 'Bayrampaşa'),
    ('İstanbul- (Avrupa)- Beşiktaş- Sait Çiftçi Devlet Hastanesi', 'İstanbul', 'Beşiktaş'),
    ('İstanbul- (Anadolu)- Beykoz Devlet Hastanesi', 'İstanbul', 'Beykoz'),
    ('İstanbul- (Avrupa)- Prof.Dr. N.Reşat Belger Beyoğlu Göz Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Beyoğlu'),
    ('İstanbul- (Avrupa)- Büyükçekmece Devlet Hastanesi', 'İstanbul', 'Büyükçekmece'),
    ('İstanbul- (Avrupa)- Çatalca- İlyas Çokay Devlet Hastanesi', 'İstanbul', 'Çatalca'),
    ('İstanbul- (Avrupa)- Esenler Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'İstanbul', 'Esenler'),
    ('İstanbul- (Avrupa)- Esenyurt Devlet Hastanesi', 'İstanbul', 'Esenyurt'),
    ('İstanbul- (Avrupa)- Eyüp Devlet Hastanesi', 'İstanbul', 'Eyüp'),
    ('İstanbul- (Avrupa)- Fatih- İstanbul Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Fatih'),
    ('İstanbul- (Avrupa)- Fatih-haseki Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Fatih'),
    ('İstanbul- (Avrupa)- Gaziosmanpaşa Taksim Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Gaziosmanpaşa'),
    ('İstanbul- (Anadolu)- Kadıköy- Erenköy Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'İstanbul', 'Kadıköy'),
    ('İstanbul- (Anadolu)- Kadıköy- Erenköy Ruh Ve Sinir Hastalıkları Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kadıköy'),
    ('İstanbul- (Anadolu)- S.B. İstanbul Medeniyet Üniversitesi Göztepe Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kadıköy'),
    ('İstanbul- (Avrupa)- Kağıthane Devlet Hastanesi', 'İstanbul', 'Kağıthane'),
    ('İstanbul- (Anadolu)- Kartal- Dr. Lütfi Kırdar Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Anadolu)- Kartal- Koşuyolu Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Anadolu)- Kartal- Yakacık Doğum Ve Çocuk Hastalıkları Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Anadolu)- Kartal- Yavuz Selim Devlet Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Avrupa)- Küçükçekmece- Kanuni Sultan Süleyman Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Küçükçekmece'),
    ('İstanbul- (Avrupa)- Mehmet Akif Ersoy Göğüs Kalp Ve Damar Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Küçükçekmece'),
    ('İstanbul- (Anadolu)- Maltepe Devlet Hastanesi', 'İstanbul', 'Maltepe'),
    ('İstanbul- (Anadolu)- Meslek Hastalıkları Hastanesi', 'İstanbul', 'Maltepe'),
    ('İstanbul- (Anadolu)- Süreyyapaşa Göğüs Hastalıkları Ve Göğüs Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Maltepe'),
    ('İstanbul- (Anadolu)- Pendik Devlet Hastanesi', 'İstanbul', 'Pendik'),
    ('İstanbul- (Anadolu)- T.C.Sağlık Bakanlığı-marmara Üniversitesi Pendik Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Pendik'),
    ('İstanbul- (Avrupa)- Sarıyer- İsmail Akgün Devlet Hastanesi', 'İstanbul', 'Sarıyer'),
    ('İstanbul- (Avrupa)- Sarıyer- İstinye Devlet Hastanesi', 'İstanbul', 'Sarıyer'),
    ('İstanbul- (Avrupa)- Sarıyer- Metin Sabancı Baltalimanı Kemik Hastalıkları Eğitim Araştırma Hastanesi', 'İstanbul', 'Sarıyer'),
    ('İstanbul- (Avrupa)- Dr. Necmi Ayanoğlu Silivri Devlet Hastanesi', 'İstanbul', 'Silivri'),
    ('İstanbul- (Anadolu)- Tacirler Eğitim Vakfı Sultanbeyli Devlet Hastanesi', 'İstanbul', 'Sultanbeyli'),
    ('İstanbul- (Avrupa)- Sultangazi- Lütfiye Nuri Burat Devlet Hastanesi', 'İstanbul', 'Sultangazi'),
    ('İstanbul- (Anadolu)- Şile Devlet Hastanesi', 'İstanbul', 'Şile'),
    ('İstanbul- (Avrupa)- Şişli Etfal Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Şişli'),
    ('İstanbul- (Avrupa)- Şişli- Okmeydanı Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Şişli'),
    ('İstanbul- (Anadolu)- Tuzla Devlet Hastanesi', 'İstanbul', 'Tuzla'),
    ('İstanbul- (Anadolu)- Ümraniye Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Ümraniye'),
    ('İstanbul- (Anadolu)- Dr. Siyami Ersek Göğüs Kalp Ve Damar Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Anadolu)- Üsküdar Devlet Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Anadolu)- Üsküdar- Haydarpaşa Numune Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Anadolu)- Üsküdar- Zeynep Kamil Kadın Ve Çocuk Hastalıkları Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Avrupa)- Süleymaniye Kadın Doğum Ve Çocuk Hastalıkları Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Zeytinburnu'),
    ('İstanbul- (Avrupa)- Yedikule Göğüs Hastalıkları Ve Göğüs Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Zeytinburnu'),
    ('�zmir Alia�a Devlet Hastanesi', 'İzmir', 'Al�a�a'),
    ('�zmir Bay�nd�r Devlet Hastanesi', 'İzmir', 'Bayındır'),
    ('�zmir Dr. Faruk �lker Bergama Devlet Hastanesi', 'İzmir', 'Bergama'),
    ('�zmir Bornova T�rkan �zilhan Devlet Hastanesi', 'İzmir', 'Bornova'),
    ('�zmir Buca Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'İzmir', 'Buca'),
    ('�zmir Buca Seyfi Demirsoy Devlet Hastanesi', 'İzmir', 'Buca'),
    ('�zmir Dikili Devlet Hastanesi', 'İzmir', 'D�k�l�'),
    ('�zmir Fo�a Devlet Hastanesi', 'İzmir', 'Fo�a'),
    ('�zmir Gaziemir Nevvar Salih ��g�ren Devlet Hastanesi', 'İzmir', 'Gaz�em�r'),
    ('�zmir Bozyaka E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Karaba�lar'),
    ('�zmir Katip �elebi �niversitesi Atat�rk E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Karaba�lar'),
    ('�zmir Kar��yaka Devlet Hastanesi', 'İzmir', 'Kar�ıyaka'),
    ('�zmir Kemalpa�a Devlet Hastanesi', 'İzmir', 'Kemalpa�a'),
    ('�zmir Alsancak Nevvar Salih ��g�ren Devlet Hastanesi', 'İzmir', 'Konak'),
    ('�zmir Dr. Beh�et Uz �ocuk Hastal�klar� Ve Cerrahisi E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Konak'),
    ('�zmir Dr. Suat Seren G���s Hastal�klar� Ve Cerrahisi E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Konak'),
    ('�zmir E�itim Di� Hastanesi', 'İzmir', 'Konak'),
    ('�zmir Tepecik E�itim Ve Ara�t�rma Hastanesi', 'İzmir', 'Konak'),
    ('�zmir Kiraz Devlet Hastanesi', 'İzmir', 'K�raz'),
    ('�zmir Menemen Devlet Hastanesi', 'İzmir', 'Menemen'),
    ('�zmir Nejat Hepkon Seferihisar Devlet Hastanesi', 'İzmir', 'Sefer�h�sar'),
    ('�zmir Sel�uk Devlet Hastanesi', 'İzmir', 'Sel�uk'),
    ('�zmir M.Enver �enerdem Torbal� Devlet Hastanesi', 'İzmir', 'Torbalı'),
    ('�zmir Tire Devlet Hastanesi', 'İzmir', 'T�re'),
    ('�zmir Urla Devlet Hastanesi', 'İzmir', 'Urla'),
    ('�zmir �demi� Devlet Hastanesi', 'İzmir', '�dem��'),
    ('�zmir Alper �izgenakat �e�me Devlet Hastanesi', 'İzmir', '�e�me'),
    ('�zmir �i�li Devlet Hastanesi', 'İzmir', '���l�'),
    ('Kahramanmaraş Afşin Devlet Hastanesi', 'Kahramanmaraş', 'Afşin'),
    ('Kahramanmaraş Andırın Devlet Hastanesi', 'Kahramanmaraş', 'Andırın'),
    ('Kahramanmaraş Çağlayancerit İlçe Hastanesi', 'Kahramanmaraş', 'Çağlayancerit'),
    ('Kahramanmaraş Elbistan Devlet Hastanesi', 'Kahramanmaraş', 'Elbistan'),
    ('Kahramanmaraş Dr. Süreyya Adanalı Göksun Devlet Hastanesi', 'Kahramanmaraş', 'Göksun'),
    ('Kahramanmaraş Necip Fazıl Şehir Devlet Hastanesi', 'Kahramanmaraş', 'Merkez'),
    ('Kahramanmaraş Pazarcık Devlet Hastanesi', 'Kahramanmaraş', 'Pazarcık'),
    ('Kahramanmaraş Türkoğlu Dr. Kemal Beyazıt Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Kahramanmaraş', 'Türkoğlu'),
    ('Karab�k Sa�l�k Bakanl��� Karab�k �niversitesi Karab�k E�itim Ve Ara�t�rma Hastanesi', 'Karabük', 'Merkez'),
    ('Karab�k Safranbolu Devlet Hastanesi', 'Karabük', 'Safranbolu'),
    ('Karab�k Yenice Devlet Hastanesi', 'Karabük', 'Yen�ce'),
    ('Karaman Ermenek Devlet Hastanesi', 'Karaman', 'Ermenek'),
    ('Karaman Devlet Hastanesi', 'Karaman', 'Merkez'),
    ('Kars Ka��zman Devlet Hastanesi', 'Kars', 'Ka�ızman'),
    ('Kars Devlet Hastanesi', 'Kars', 'Merkez'),
    ('Kars Sar�kam�� Devlet Hastanesi', 'Kars', 'Sarıkamı�'),
    ('Kars Selim �l�e Hastanesi', 'Kars', 'Sel�m'),
    ('Kastamonu Ara� �l�e Devlet Hastanesi', 'Kastamonu', 'Ara�'),
    ('Kastamonu Azdavay �l�e Hastanesi', 'Kastamonu', 'Azdavay'),
    ('Kastamonu Bozkurt Devlet Hastanesi', 'Kastamonu', 'Bozkurt'),
    ('Kastamonu Cide Devlet Hastanesi', 'Kastamonu', 'C�de'),
    ('Kastamonu Daday Devlet Hastanesi', 'Kastamonu', 'Daday'),
    ('Kastamonu Devrekani Devlet Hastanesi', 'Kastamonu', 'Devrekan�'),
    ('Kastamonu Dr. M�nif �slamo�lu Devlet Hastanesi', 'Kastamonu', 'Merkez'),
    ('Kastamonu Rehabilitasyon Merkezi', 'Kastamonu', 'Merkez'),
    ('Kastamonu Ta�k�pr� Devlet Hastanesi', 'Kastamonu', 'Ta�k�pr�'),
    ('Kastamonu Tosya Devlet Hastanesi', 'Kastamonu', 'Tosya'),
    ('Kastamonu �nebolu Devlet Hastanesi', 'Kastamonu', '�nebolu'),
    ('Kayseri B�nyan Devlet Hastanesi', 'Kayseri', 'B�nyan'),
    ('Kayseri Develi Devlet Hastanesi', 'Kayseri', 'Devel�'),
    ('Kayseri E�itim Ve Ara�t�rma Hastanesi', 'Kayseri', 'Kocas�nan'),
    ('Kayseri P�narba�� �l�e Hastanesi', 'Kayseri', 'Pınarba�ı'),
    ('Kayseri Tomarza Devlet Hastanesi', 'Kayseri', 'Tomarza'),
    ('Kayseri Yahyal� Devlet Hastanesi', 'Kayseri', 'Yahyalı'),
    ('Kayseri Ye�ilhisaril�e Devlet Hastanesi', 'Kayseri', 'Ye��lh�sar'),
    ('Kayseri �ncesu �l�e Hastanesi', 'Kayseri', '�ncesu'),
    ('K�r�kkale Y�ksek �htisas Hastanesi', 'Kırıkkale', 'Merkez'),
    ('K�rklareli Babaeski Devlet Hastanesi', 'Kırklareli', 'Babaesk�'),
    ('K�rklareli L�leburgaz Devlet Hastanesi', 'Kırklareli', 'L�leburgaz'),
    ('K�rklareli Devlet Hastanesi', 'Kırklareli', 'Merkez'),
    ('K�rklareli P�narhisar Devlet Hastanesi', 'Kırklareli', 'Pınarh�sar'),
    ('K�rklareli Vize Devlet Hastanesi', 'Kırklareli', 'V�ze'),
    ('K�r�ehir Kaman Devlet Hastanesi', 'Kırşehir', 'Kaman'),
    ('K�r�ehir Ahi Evran �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Kırşehir', 'Merkez'),
    ('K�r�ehir Mucur Devlet Hastanesi', 'Kırşehir', 'Mucur'),
    ('Kilis Devlet Hastanesi', 'Kilis', 'Merkez'),
    ('Kocaeli Dar�ca Farabi Devlet Hastanesi', 'Kocaeli', 'Darıca'),
    ('Kocaeli Derince E�itim Ve Ara�t�rma Hastanesi', 'Kocaeli', 'Der�nce'),
    ('Kocaeli Gebze Fatih Devlet Hastanesi', 'Kocaeli', 'Gebze'),
    ('Kocaeli G�lc�k Necati �elik Devlet Hastanesi', 'Kocaeli', 'G�lc�k'),
    ('Kocaeli Kand�ra Kaz�m Din� Devlet Hastanesi', 'Kocaeli', 'Kandıra'),
    ('Kocaeli Karam�rsel Devlet Hastanesi', 'Kocaeli', 'Karam�rsel'),
    ('Kocaeli K�rfez Devlet Hastanesi', 'Kocaeli', 'K�rfez'),
    ('Kocaeli Devlet Hastanesi', 'Kocaeli', '�zm�t'),
    ('Kocaeli �zmit Seka Devlet Hastanesi', 'Kocaeli', '�zm�t'),
    ('Konya Ak�ehir Devlet Hastanesi', 'Konya', 'Ak�eh�r'),
    ('Konya Bey�ehir Devlet Hastanesi', 'Konya', 'Bey�eh�r'),
    ('Konya Bozk�r Devlet Hastanesi', 'Konya', 'Bozkır'),
    ('Konya Cihanbeyli Devlet Hastanesi', 'Konya', 'C�hanbeyl�'),
    ('Konya Do�anhisar Devlet Hastanesi', 'Konya', 'Do�anh�sar'),
    ('Konya Ere�li Devlet Hastanesi', 'Konya', 'Ere�l�'),
    ('Konya Hadim Devlet Hastanesi', 'Konya', 'Had�m'),
    ('Konya H�y�k Devlet Hastanesi', 'Konya', 'H�y�k'),
    ('Konya Dr. Vefa Tan�r Ilg�n Devlet Hastanesi', 'Konya', 'Ilgın'),
    ('Konya Kad�nhan� Refik Saime Koyuncu Devlet Hastanesi', 'Konya', 'Kadınhanı'),
    ('Konya Karap�nar Devlet Hastanesi', 'Konya', 'Karapınar'),
    ('Konya Kulu Devlet Hastanesi', 'Konya', 'Kulu'),
    ('Konya E�itim Ve Ara�t�rma Hastanesi', 'Konya', 'Meram'),
    ('Konya Saray�n� Devlet Hastanesi', 'Konya', 'Saray�n�'),
    ('Konya Beyhekim Devlet Hastanesi', 'Konya', 'Sel�uklu'),
    ('Konya Dr. Faruk S�kan Do�um Ve �ocuk Bak�mevi', 'Konya', 'Sel�uklu'),
    ('Konya Numune Hastanesi', 'Konya', 'Sel�uklu'),
    ('Konya Seydi�ehir Devlet Hastanesi', 'Konya', 'Seyd��eh�r'),
    ('Konya Yunak Hac� �zzet Baysal Devlet Hastanesi', 'Konya', 'Yunak'),
    ('Konya �umra Devlet Hastanesi', 'Konya', '�umra'),
    ('K�tahya Emet Devlet Hastanesi', 'Kütahya', 'Emet'),
    ('K�tahya Gediz Devlet Hastanesi', 'Kütahya', 'Ged�z'),
    ('K�tahya D.P.�. Evliya �elebi E�itim Ve Ara�t�rma Hastanesi', 'Kütahya', 'Merkez'),
    ('K�tahya Yoncal� Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Kütahya', 'Merkez'),
    ('K�tahya Do�.Dr.�smail Karakuyu Simav Devlet Hastanesi', 'Kütahya', 'S�mav'),
    ('K�tahya Do�.Dr. Mustafa Kalemli Tav�anl� Devlet Hastanesi', 'Kütahya', 'Tav�anlı'),
    ('Malatya Akçadağ 75.Yıl Devlet Hastanesi', 'Malatya', 'Akçadağ'),
    ('Malatya Arapgir İlçe Hastanesi', 'Malatya', 'Arapkir'),
    ('Malatya Darende Hulusi Efendi Devlet Hastanesi', 'Malatya', 'Darende'),
    ('Malatya Doğanşehir Devlet Hastanesi', 'Malatya', 'Doğanşehir'),
    ('Malatya Hekimhan Devlet Hastanesi', 'Malatya', 'Hekimhan'),
    ('Malatya Devlet Hastanesi', 'Malatya', 'Merkez'),
    ('Malatya Pötürge Devlet Hastanesi', 'Malatya', 'Pötürge'),
    ('Malatya Yeşilyurt Hasan Çalık Devlet Hastanesi', 'Malatya', 'Yeşilyurt'),
    ('Manisa Akhisar Devlet Hastanesi', 'Manisa', 'Akh�sar'),
    ('Manisa Ala�ehir Devlet Hastanesi', 'Manisa', 'Ala�eh�r'),
    ('Manisa Demirci Devlet Hastanesi', 'Manisa', 'Dem�rc�'),
    ('Manisa G�rdes Devlet Hastanesi', 'Manisa', 'G�rdes'),
    ('Manisa K�rka�a� Devlet Hastanesi', 'Manisa', 'Kırka�a�'),
    ('Manisa Kula Devlet Hastanesi', 'Manisa', 'Kula'),
    ('Manisa Devlet Hastanesi', 'Manisa', 'Merkez'),
    ('Manisa Merkezefendi Devlet Hastanesi', 'Manisa', 'Merkez'),
    ('Manisa Ruh Sa�l��� Ve Hastal�klar� Hastanesi', 'Manisa', 'Merkez'),
    ('Manisa Salihli Devlet Hastanesi', 'Manisa', 'Sal�hl�'),
    ('Manisa Sar�g�l Devlet Hastanesi', 'Manisa', 'Sarıg�l'),
    ('Manisa Saruhanl� Devlet Hastanesi', 'Manisa', 'Saruhanlı'),
    ('Manisa Selendi Devlet Hastanesi', 'Manisa', 'Selend�'),
    ('Manisa Soma Devlet Hastanesi', 'Manisa', 'Soma'),
    ('Manisa Turgutlu Devlet Hastanesi', 'Manisa', 'Turgutlu'),
    ('Mardin Darge�it �l�e Hastanesi', 'Mardin', 'Darge��t'),
    ('Mardin Derik Devlet Hastanesi', 'Mardin', 'Der�k'),
    ('Mardin K�z�ltepe Devlet Hastanesi', 'Mardin', 'Kızıltepe'),
    ('Mardin Maz�da�� �l�e Hastanesi', 'Mardin', 'Mazıda�ı'),
    ('Mardin Devlet Hastanesi', 'Mardin', 'Merkez'),
    ('Mardin Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Mardin', 'Merkez'),
    ('Mardin Midyat Devlet Hastanesi', 'Mardin', 'M�dyat'),
    ('Mardin Nusaybin Devlet Hastanesi', 'Mardin', 'Nusayb�n'),
    ('Mardin Savur �l�e Hastanesi', 'Mardin', 'Savur'),
    ('Mersin Devlet Hastanesi', 'Mersin', 'Akdeniz'),
    ('Mersin Toros Devlet Hastanesi', 'Mersin', 'Akdeniz'),
    ('Mersin Anamur Devlet Hastanesi', 'Mersin', 'Anamur'),
    ('Mersin Aydıncık Devlet Hastanesi', 'Mersin', 'Aydıncık'),
    ('Mersin Bozyazı Devlet Hastanesi', 'Mersin', 'Bozyazı'),
    ('Mersin Erdemli Devlet Hastanesi', 'Mersin', 'Erdemli'),
    ('Mersin Gülnar Devlet Hastanesi', 'Mersin', 'Gülnar'),
    ('Mersin Mut Devlet Hastanesi', 'Mersin', 'Mut'),
    ('Mersin Silifke Devlet Hastanesi', 'Mersin', 'Silifke'),
    ('Mersin Tarsus Devlet Hastanesi', 'Mersin', 'Tarsus'),
    ('Mersin Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Mersin', 'Toroslar'),
    ('Mu�la Bodrum Devlet Hastanesi', 'Muğla', 'Bodrum'),
    ('Mu�la Dalaman Devlet Hastanesi', 'Muğla', 'Dalaman'),
    ('Mu�la Dat�a Devlet Hastanesi', 'Muğla', 'Dat�a'),
    ('Mu�la Fethiye Devlet Hastanesi', 'Muğla', 'Feth�ye'),
    ('Mu�la K�yce�iz Devlet Hastanesi', 'Muğla', 'K�yce��z'),
    ('Mu�la Marmaris Devlet Hastanesi', 'Muğla', 'Marmar�s'),
    ('Mu�la T.C.Sa�l�k Bakanl��� Mu�la S�tk� Ko�man �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Muğla', 'Merkez'),
    ('Mu�la Milas 75.Y�l Devlet Hastanesi', 'Muğla', 'M�las'),
    ('Mu�la Ortaca Devlet Hastanesi', 'Muğla', 'Ortaca'),
    ('Mu�la Yata�an Devlet Hastanesi', 'Muğla', 'Yata�an'),
    ('Mu� Bulan�k Devlet Hastanesi', 'Muş', 'Bulanık'),
    ('Mu� Hask�y Devlet Hastanesi', 'Muş', 'Hask�y'),
    ('Mu� Korkut �l�e Hastanesi', 'Muş', 'Korkut'),
    ('Mu� Malazgirt Devlet Hastanesi', 'Muş', 'Malazg�rt'),
    ('Mu� Devlet Hastanesi', 'Muş', 'Merkez'),
    ('Mu� Varto Devlet Hastanesi', 'Muş', 'Varto'),
    ('Nev�ehir Dr.�.�evki Atasagun Devlet Hastanesi', 'Nevşehir', 'Merkez'),
    ('Nev�ehir �rg�p Devlet Hastanesi', 'Nevşehir', '�rg�p'),
    ('Ni�de Bor Devlet Hastanesi', 'Niğde', 'Bor'),
    ('Ni�de Devlet Hastanesi', 'Niğde', 'Merkez'),
    ('Ni�de Uluk��la �l�e Hastanesi', 'Niğde', 'Ulukı�la'),
    ('Ni�de �iftlik �l�e Hastanesi', 'Niğde', '��ftl�k'),
    ('Ordu Akku� Devlet Hastanesi', 'Ordu', 'Akku�'),
    ('Ordu Aybast� Devlet Hastanesi', 'Ordu', 'Aybastı'),
    ('Ordu Fatsa Devlet Hastanesi', 'Ordu', 'Fatsa'),
    ('Ordu G�lk�y Devlet Hastanesi', 'Ordu', 'G�lk�y'),
    ('Ordu G�rgentepe Devlet Hastanesi', 'Ordu', 'G�rgentepe'),
    ('Ordu Korgan Devlet Hastanesi', 'Ordu', 'Korgan'),
    ('Ordu Kumru Devlet Hastanesi', 'Ordu', 'Kumru'),
    ('Ordu Devlet Hastanesi', 'Ordu', 'Merkez'),
    ('Ordu Sa�l�k Bakanl���-ordu �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Ordu', 'Merkez'),
    ('Ordu Ulubey Devlet Hastanesi', 'Ordu', 'Ulubey'),
    ('Ordu �nye Devlet Hastanesi', 'Ordu', '�nye'),
    ('Osmaniye D�zi�i Devlet Hastanesi', 'Osmaniye', 'D�z���'),
    ('Osmaniye Kadirli Devlet Hastanesi', 'Osmaniye', 'Kad�rl�'),
    ('Osmaniye Devlet Hastanesi', 'Osmaniye', 'Merkez'),
    ('Rize F�nd�kl� B�lge Guatr Ara�t�rma Ve Tedavi Merkezi', 'Rize', 'Fındıklı'),
    ('Rize G�neysu Tenzile Erdo�an �l�e Hastanesi', 'Rize', 'G�neysu'),
    ('Rize Devlet Hastanesi', 'Rize', 'Merkez'),
    ('Rize T.C. Sa�l�k Bakanl��� Recep Tayyip Erdo�an �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Rize', 'Merkez'),
    ('Rize Ka�kar Devlet Hastanesi', 'Rize', 'Pazar'),
    ('Rize �shako�lu �ayeli Devlet Hastanesi', 'Rize', '�ayel�'),
    ('Sakarya Do�um Ve �ocuk Bak�mevi', 'Sakarya', 'Adapazarı'),
    ('Sakarya Sa�l�k Bakanl��� Sakarya �niversitesi E�itim Ve Ara�t�rma Hastanesi', 'Sakarya', 'Adapazarı'),
    ('Sakarya Yenikent Devlet Hastanesi', 'Sakarya', 'Adapazarı'),
    ('Sakarya Akyaz� Devlet Hastanesi', 'Sakarya', 'Akyazı'),
    ('Sakarya Toyotasa Acil Yard�m Hastanesi', 'Sakarya', 'Ar�f�ye'),
    ('Sakarya Ferizli �l�e Hastanesi', 'Sakarya', 'Fer�zl�'),
    ('Sakarya Geyve Devlet Hastanesi', 'Sakarya', 'Geyve'),
    ('Sakarya Hendek Devlet Hastanesi', 'Sakarya', 'Hendek'),
    ('Sakarya Karasu Devlet Hastanesi', 'Sakarya', 'Karasu'),
    ('Sakarya Kaynarca �l�e Hastanesi', 'Sakarya', 'Kaynarca'),
    ('Sakarya Kocaali �l�e Hastanesi', 'Sakarya', 'Kocaal�'),
    ('Sakarya Pamukova Devlet Hastanesi', 'Sakarya', 'Pamukova'),
    ('Sakarya Sapanca �l�e Hastanesi', 'Sakarya', 'Sapanca'),
    ('Samsun 19 May�s �l�e (Engiz) Hastanesi', 'Samsun', '19mayıs'),
    ('Samsun Ala�am Devlet Hastanesi', 'Samsun', 'Ala�am'),
    ('Samsun Asarc�k �l�e Hastanesi', 'Samsun', 'Asarcık'),
    ('Samsun Ayvac�k Devlet Hastanesi', 'Samsun', 'Ayvacık'),
    ('Samsun Bafra Devlet Hastanesi', 'Samsun', 'Bafra'),
    ('Samsun Havza Devlet Hastanesi', 'Samsun', 'Havza'),
    ('Samsun Kavak Devlet Hastanesi', 'Samsun', 'Kavak'),
    ('Samsun Ladik Devlet Hastanesi', 'Samsun', 'Lad�k'),
    ('Samsun Sal�pazar� �l�e Hastanesi', 'Samsun', 'Salıpazarı'),
    ('Samsun Terme Devlet Hastanesi', 'Samsun', 'Terme'),
    ('Samsun Vezirk�pr� Devlet Hastanesi', 'Samsun', 'Vez�rk�pr�'),
    ('Samsun �ar�amba Devlet Hastanesi', 'Samsun', '�ar�amba'),
    ('Samsun E�itim Ve Ara�t�rma Hastanesi', 'Samsun', '�lkadım'),
    ('Samsun Fiziksel T�p Rehabilitasyon Hastal�klar� Hastanesi', 'Samsun', '�lkadım'),
    ('Samsun Gazi Devlet Hastanesi', 'Samsun', '�lkadım'),
    ('Samsun G���s Hastal�klar� Ve G���s Cerrahisi Hastanesi', 'Samsun', '�lkadım'),
    ('Samsun Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Samsun', '�lkadım'),
    ('Samsun Ruh Sa�l��� Ve Hastal�klar� Hastanesi', 'Samsun', '�lkadım'),
    ('Siirt Baykan Devlet Hastanesi', 'Siirt', 'Baykan'),
    ('Siirt Eruh �l�e Hastanesi', 'Siirt', 'Eruh'),
    ('Siirt Kurtalan Devlet Hastanesi', 'Siirt', 'Kurtalan'),
    ('Siirt Devlet Hastanesi', 'Siirt', 'Merkez'),
    ('Siirt Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Siirt', 'Merkez'),
    ('Siirt Pervari �l�e Hastanesi', 'Siirt', 'Pervar�'),
    ('Sinop Ayanc�k Devlet Hastanesi', 'Sinop', 'Ayancık'),
    ('Sinop Boyabat 75.Y�l Devlet Hastanesi', 'Sinop', 'Boyabat'),
    ('Sinop Dura�an Devlet Hastanesi', 'Sinop', 'Dura�an'),
    ('Sinop Gerze Devlet Hastanesi', 'Sinop', 'Gerze'),
    ('Sinop Atat�rk Devlet Hastanesi', 'Sinop', 'Merkez'),
    ('Sinop T�rkeli Devlet Hastanesi', 'Sinop', 'T�rkel�'),
    ('Sivas Divri�i Sad�k �zg�r Devlet Hastanesi', 'Sivas', 'D�vr���'),
    ('Sivas Gemerek Devlet Hastanesi', 'Sivas', 'Gemerek'),
    ('Sivas G�r�n Devlet Hastanesi', 'Sivas', 'G�r�n'),
    ('Sivas Kangal Devlet Hastanesi', 'Sivas', 'Kangal'),
    ('Sivas Devlet Hastanesi', 'Sivas', 'Merkez'),
    ('Sivas Numune Hastanesi', 'Sivas', 'Merkez'),
    ('Sivas Su�ehri Devlet Hastanesi', 'Sivas', 'Su�ehr�'),
    ('Sivas Y�ld�zeli Devlet Hastanesi', 'Sivas', 'Yıldızel�'),
    ('Sivas Zara Devlet Hastanesi', 'Sivas', 'Zara'),
    ('Sivas �ark��la Devlet Hastanesi', 'Sivas', '�arkı�la'),
    ('�anl�urfa Ak�akale Devlet Hastanesi', 'Şanlıurfa', 'Ak�akale'),
    ('�anl�urfa Bozova �l�e Hastanesi', 'Şanlıurfa', 'Bozova'),
    ('�anl�urfa Birecik Devlet Hastanesi', 'Şanlıurfa', 'B�rec�k'),
    ('�anl�urfa Ceylanp�nar Devlet Hastanesi', 'Şanlıurfa', 'Ceylanpınar'),
    ('�anl�urfa Halfeti �l�e Hastanesi', 'Şanlıurfa', 'Halfet�'),
    ('�anl�urfa Harran Devlet Hastanesi', 'Şanlıurfa', 'Harran'),
    ('�anl�urfa Hilvan Devlet Hastanesi', 'Şanlıurfa', 'H�lvan'),
    ('�anl�urfa Bal�kl�g�l Devlet Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('�anl�urfa E�itim Ve Ara�t�rma Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('�anl�urfa Kad�n Hastal�klar� Ve Do�um Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('�anl�urfa �ocuk Hastal�klar� Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('�anl�urfa Suru� Devlet Hastanesi', 'Şanlıurfa', 'Suru�'),
    ('�anl�urfa Siverek Devlet Hastanesi', 'Şanlıurfa', 'S�verek'),
    ('�anl�urfa Viran�ehir Devlet Hastanesi', 'Şanlıurfa', 'V�ran�eh�r'),
    ('��rnak Beyt���ebap Devlet Hastanesi', 'Şırnak', 'Beyt���ebap'),
    ('��rnak Cizre Dr. Selahattin Cizrelio�lu Devlet Hastanesi', 'Şırnak', 'C�zre'),
    ('��rnak Devlet Hastanesi', 'Şırnak', 'Merkez'),
    ('��rnak Silopi Devlet Hastanesi', 'Şırnak', 'S�lop�'),
    ('��rnak Uludere Devlet Hastanesi', 'Şırnak', 'Uludere'),
    ('��rnak �dil Devlet Hastanesi', 'Şırnak', '�d�l'),
    ('Tekirda� Hayrabolu Devlet Hastanesi', 'Tekirdağ', 'Hayrabolu'),
    ('Tekirda� Marmara Ere�lisi �l�e Devlet Hastanesi', 'Tekirdağ', 'M.ere�l�s�'),
    ('Tekirda� Malkara Devlet Hastanesi', 'Tekirdağ', 'Malkara'),
    ('Tekirda� Devlet Hastanesi', 'Tekirdağ', 'Merkez'),
    ('Tekirda� Muratl� Devlet Hastanesi', 'Tekirdağ', 'Muratlı'),
    ('Tekirda� Saray Devlet Hastanesi', 'Tekirdağ', 'Saray'),
    ('Tekirda� �ark�y Devlet Hastanesi', 'Tekirdağ', '�ark�y'),
    ('Tekirda� �erkezk�y Devlet Hastanesi', 'Tekirdağ', '�erkezk�y'),
    ('Tekirda� �orlu Devlet Hastanesi', 'Tekirdağ', '�orlu'),
    ('Tokat Almus �l�e Hastanesi', 'Tokat', 'Almus'),
    ('Tokat Erbaa Devlet Hastanesi', 'Tokat', 'Erbaa'),
    ('Tokat Devlet Hastanesi', 'Tokat', 'Merkez'),
    ('Tokat Ruh Sa�l��� Ve Hastal�klar� Hastanesi', 'Tokat', 'Merkez'),
    ('Tokat Niksar Devlet Hastanesi', 'Tokat', 'N�ksar'),
    ('Tokat Re�adiye Devlet Hastanesi', 'Tokat', 'Re�ad�ye'),
    ('Tokat Turhal Devlet Hastanesi', 'Tokat', 'Turhal'),
    ('Tokat Zile Devlet Hastanesi', 'Tokat', 'Z�le'),
    ('Trabzon Ak�aabat Ha�kal� Baba Devlet Hastanesi', 'Trabzon', 'Ak�aabat'),
    ('Trabzon Arakl� Bayram Halil Devlet Hastanesi', 'Trabzon', 'Araklı'),
    ('Trabzon Ma�ka �mer Burhano�lu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Ma�ka'),
    ('Trabzon Ahi Evren G���s Kalp Ve Damar Cerrahisi E�itim Ve Ara�t�rma Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Fatih Devlet Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Kanuni E�itim Ve Ara�t�rma Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Yavuz Selim Kemik Hastal�klar� Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Of Devlet Hastanesi', 'Trabzon', 'Of'),
    ('Trabzon S�rmene Devlet Hastanesi', 'Trabzon', 'S�rmene'),
    ('Trabzon Tonya Devlet Hastanesi', 'Trabzon', 'Tonya'),
    ('Trabzon Vakf�kebir Devlet Hastanesi', 'Trabzon', 'Vakfıkeb�r'),
    ('Trabzon Atak�y Ruh Ve Sinir Hastal�klar� Hastanesi', 'Trabzon', '�aykara'),
    ('Tunceli Devlet Hastanesi', 'Tunceli', 'Merkez'),
    ('U�ak Banaz Devlet Hastanesi', 'Uşak', 'Banaz'),
    ('U�ak E�me Devlet Hastanesi', 'Uşak', 'E�me'),
    ('U�ak Devlet Hastanesi', 'Uşak', 'Merkez'),
    ('U�ak Sivasl� Devlet Hastanesi', 'Uşak', 'S�vaslı'),
    ('Van Bah�esaray �l�e Hastanesi', 'Van', 'Bah�esaray'),
    ('Van Ba�kale Devlet Hastanesi', 'Van', 'Ba�kale'),
    ('Van Erci� Devlet Hastanesi', 'Van', 'Erc��'),
    ('Van Geva� Devlet Hastanesi', 'Van', 'Geva�'),
    ('Van B�lge E�itim Ve Ara�t�rma Hastanesi', 'Van', 'Merkez'),
    ('Van Muradiye Devlet Hastanesi', 'Van', 'Murad�ye'),
    ('Van �ald�ran �l�e Hastanesi', 'Van', '�aldıran'),
    ('Van �atak �l�e Hastanesi', 'Van', '�atak'),
    ('Van Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Van', '�pekyolu'),
    ('Van �zalp Devlet Hastanesi', 'Van', '�zalp'),
    ('Yalova Devlet Hastanesi', 'Yalova', 'Merkez'),
    ('Yalova ��narc�k Devlet Hastanesi', 'Yalova', '�ınarcık'),
    ('Yozgat Akda�madeni Devlet Hastanesi', 'Yozgat', 'Akda�maden�'),
    ('Yozgat Bo�azl�yan Devlet Hastanesi', 'Yozgat', 'Bo�azlıyan'),
    ('Yozgat Devlet Hastanesi', 'Yozgat', 'Merkez'),
    ('Yozgat Saraykent �l�e Hastanesi', 'Yozgat', 'Saraykent'),
    ('Yozgat Sar�kaya Devlet Hastanesi', 'Yozgat', 'Sarıkaya'),
    ('Yozgat Sorgun Devlet Hastanesi', 'Yozgat', 'Sorgun'),
    ('Yozgat Yerk�y Devlet Hastanesi', 'Yozgat', 'Yerk�y'),
    ('Yozgat �efaatli Devlet Hastanesi', 'Yozgat', '�efaatl�'),
    ('Yozgat �ekerek Devlet Hastanesi', 'Yozgat', '�ekerek'),
    ('Zonguldak Alapl� Devlet Hastanesi', 'Zonguldak', 'Alaplı'),
    ('Zonguldak Devrek Devlet Hastanesi', 'Zonguldak', 'Devrek'),
    ('Zonguldak Karadeniz Ere�li Devlet Hastanesi', 'Zonguldak', 'Ere�l�'),
    ('Zonguldak G�k�ebey �l�e Hastanesi', 'Zonguldak', 'G�k�ebey'),
    ('Zonguldak Atat�rk Devlet Hastanesi', 'Zonguldak', 'Merkez'),
    ('Zonguldak Kad�n Do�um Ve �ocuk Hastal�klar� Hastanesi', 'Zonguldak', 'Merkez'),
    ('Zonguldak Uzun Mehmet G���s Ve Meslek Hastal�klar� Hastanesi', 'Zonguldak', 'Merkez'),
    ('Zonguldak �aycuma Devlet Hastanesi', 'Zonguldak', '�aycuma')
), branch_seed(branch) as (
  values
    ('Pratisyen Hekim Görevi'),
    ('Acil Tıp'),
    ('Adli Tıp'),
    ('Aile Hekimliği'),
    ('Anesteziyoloji ve Reanimasyon'),
    ('Beyin ve Sinir Cerrahisi'),
    ('Çocuk Cerrahisi'),
    ('Çocuk Sağlığı ve Hastalıkları'),
    ('Çocuk ve Ergen Ruh Sağlığı ve Hastalıkları'),
    ('Çocuk Alerji ve İmmünoloji'),
    ('Çocuk Endokrinolojisi'),
    ('Çocuk Enfeksiyon Hastalıkları'),
    ('Çocuk Gastroenterolojisi'),
    ('Çocuk Göğüs Hastalıkları'),
    ('Çocuk Hematolojisi ve Onkolojisi'),
    ('Çocuk Kardiyolojisi'),
    ('Çocuk Nefrolojisi'),
    ('Çocuk Nörolojisi'),
    ('Çocuk Romatolojisi'),
    ('Çocuk Yoğun Bakım'),
    ('Deri ve Zührevi Hastalıkları'),
    ('Endokrinoloji ve Metabolizma Hastalıkları'),
    ('Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji'),
    ('Fiziksel Tıp ve Rehabilitasyon'),
    ('Gastroenteroloji'),
    ('Genel Cerrahi'),
    ('Geriatri'),
    ('Göğüs Cerrahisi'),
    ('Göğüs Hastalıkları'),
    ('Göz Hastalıkları'),
    ('Halk Sağlığı'),
    ('Hematoloji'),
    ('İç Hastalıkları'),
    ('Jinekolojik Onkoloji Cerrahisi'),
    ('Kadın Hastalıkları ve Doğum'),
    ('Kalp ve Damar Cerrahisi'),
    ('Kardiyoloji'),
    ('Kulak Burun Boğaz Hastalıkları'),
    ('Nefroloji'),
    ('Neonatoloji'),
    ('Nöroloji'),
    ('Nükleer Tıp'),
    ('Ortopedi ve Travmatoloji'),
    ('Perinatoloji'),
    ('Plastik, Rekonstrüktif ve Estetik Cerrahi'),
    ('Psikiyatri'),
    ('Radyasyon Onkolojisi'),
    ('Radyoloji'),
    ('Romatoloji'),
    ('Tıbbi Biyokimya'),
    ('Tıbbi Genetik'),
    ('Tıbbi Mikrobiyoloji'),
    ('Tıbbi Onkoloji'),
    ('Tıbbi Patoloji'),
    ('Üroloji'),
    ('Yoğun Bakım')
), target_hospitals as (
  select distinct h.id
  from public.hospitals h
  join hospital_seed s
    on lower(h.name)=lower(s.name) and h.city=s.city and h.district=s.district
)
insert into public.clinics (hospital_id, branch)
select th.id, bs.branch
from target_hospitals th cross join branch_seed bs
where not exists (
  select 1 from public.clinics c
  where c.hospital_id=th.id and c.branch=bs.branch
);
