-- Türkiye'nin 81 ilindeki kamu hastaneleri için ülke geneli başlangıç kataloğu.
-- Kaynak taban: MHRS kamu sağlık tesisi verisi; projedeki daha yeni il kayıtları korunur.
-- Ağız ve diş sağlığı merkezleri bu tıp kliniği kataloğuna dahil değildir.
-- Standart klinik şablonu, projedeki mevcut il ekleme migrasyonlarıyla aynıdır.
-- İdempotenttir; aynı kurum/klinik ikinci kez eklenmez.

with hospital_seed(name, city, district, hospital_type) as (
  values
    ('Adana Ceyhan Devlet Hastanesi', 'Adana', 'Ceyhan', 'state_hospital'),
    ('Adana Dr. Ekrem Tok Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Adana', 'Çukurova', 'state_hospital'),
    ('Adana İmamoğlu Devlet Hastanesi', 'Adana', 'İmamoğlu', 'state_hospital'),
    ('Adana Karaisalı Devlet Hastanesi', 'Adana', 'Karaisalı', 'state_hospital'),
    ('Adana Kozan Devlet Hastanesi', 'Adana', 'Kozan', 'state_hospital'),
    ('Adana Pozantı 80.Yıl Devlet Hastanesi', 'Adana', 'Pozantı', 'state_hospital'),
    ('Adana Çukurova Dr. Aşkım Tüfekçi Devlet Hastanesi', 'Adana', 'Seyhan', 'state_hospital'),
    ('Adana Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Adana', 'Seyhan', 'state_hospital'),
    ('Adana Tufanbeyli Devlet Hastanesi', 'Adana', 'Tufanbeyli', 'state_hospital'),
    ('Adana Devlet Hastanesi', 'Adana', 'Yüreğir', 'state_hospital'),
    ('Adana Numune Eğitim Ve Araştırma Hastanesi', 'Adana', 'Yüreğir', 'training_and_research_hospital'),
    ('Afyonkarahisar Dr. Halil İbrahim Özsoy Bolvadin Devlet Hastanesi', 'Afyonkarahisar', 'Bolvadin', 'state_hospital'),
    ('Afyonkarahisar Çay Devlet Hastanesi', 'Afyonkarahisar', 'Çay', 'state_hospital'),
    ('Afyonkarahisar Dinar Devlet Hastanesi', 'Afyonkarahisar', 'Dinar', 'state_hospital'),
    ('Afyonkarahisar Emirdağ Devlet Hastanesi', 'Afyonkarahisar', 'Emirdağ', 'state_hospital'),
    ('Afyonkarahisar İscehisar Devlet Hastanesi', 'Afyonkarahisar', 'İscehisar', 'state_hospital'),
    ('Afyonkarahisar Devlet Hastanesi', 'Afyonkarahisar', 'Merkez', 'state_hospital'),
    ('Afyonkarahisar Zübeyde Hanım Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Afyonkarahisar', 'Merkez', 'state_hospital'),
    ('Afyonkarahisar Sandıklı Devlet Hastanesi', 'Afyonkarahisar', 'Sandıklı', 'state_hospital'),
    ('Afyonkarahisar Sinanpaşa İlçe Hastanesi', 'Afyonkarahisar', 'Sinanpaşa', 'state_hospital'),
    ('Afyonkarahisar Şuhut Devlet Hastanesi', 'Afyonkarahisar', 'Şuhut', 'state_hospital'),
    ('Ağrı Diyadin Devlet Hastanesi', 'Ağrı', 'Diyadin', 'state_hospital'),
    ('Ağrı Dr. Yaşar Eryılmaz Doğubeyazıt Devlet Hastanesi', 'Ağrı', 'Doğubeyazıt', 'state_hospital'),
    ('Ağrı Eleşkirt Devlet Hastanesi', 'Ağrı', 'Eleşkirt', 'state_hospital'),
    ('Ağrı Hamur İlçe Devlet Hastanesi', 'Ağrı', 'Hamur', 'state_hospital'),
    ('Ağrı Devlet Hastanesi', 'Ağrı', 'Merkez', 'state_hospital'),
    ('Ağrı Patnos Devlet Hastanesi', 'Ağrı', 'Patnos', 'state_hospital'),
    ('Ağrı Taşlıçay İlçe Devlet Hastanesi', 'Ağrı', 'Taşlıçay', 'state_hospital'),
    ('Ağrı Tutak Devlet Hastanesi', 'Ağrı', 'Tutak', 'state_hospital'),
    ('Aksaray Eskil Devlet Hastanesi', 'Aksaray', 'Eskil', 'state_hospital'),
    ('Aksaray Gülağaç İlçe Hastanesi', 'Aksaray', 'Gülağaç', 'state_hospital'),
    ('Aksaray Devlet Hastanesi', 'Aksaray', 'Merkez', 'state_hospital'),
    ('Aksaray Ortaköy Devlet Hastanesi', 'Aksaray', 'Ortaköy', 'state_hospital'),
    ('Amasya Gümüşhacıköy Devlet Hastanesi', 'Amasya', 'Gümüşhacıköy', 'state_hospital'),
    ('Amasya Sabuncuoğlu Şerefeddin Devlet Hastanesi', 'Amasya', 'Merkez', 'state_hospital'),
    ('Amasya Merzifon Kara Mustafa Paşa Devlet Hastanesi', 'Amasya', 'Merzifon', 'state_hospital'),
    ('Amasya Suluova Devlet Hastanesi', 'Amasya', 'Suluova', 'state_hospital'),
    ('Amasya Taşova Devlet Hastanesi', 'Amasya', 'Taşova', 'state_hospital'),
    ('Antalya Akseki Devlet Hastanesi', 'Antalya', 'Akseki', 'state_hospital'),
    ('Antalya Alanya Devlet Hastanesi', 'Antalya', 'Alanya', 'state_hospital'),
    ('Antalya Demre Devlet Hastanesi', 'Antalya', 'Demre', 'state_hospital'),
    ('Antalya Elmalı Devlet Hastanesi', 'Antalya', 'Elmalı', 'state_hospital'),
    ('Antalya Finike Devlet Hastanesi', 'Antalya', 'Finike', 'state_hospital'),
    ('Antalya Gazipaşa Devlet Hastanesi', 'Antalya', 'Gazipaşa', 'state_hospital'),
    ('Antalya Kaş Devlet Hastanesi', 'Antalya', 'Kaş', 'state_hospital'),
    ('Antalya Kemer Devlet Hastanesi', 'Antalya', 'Kemer', 'state_hospital'),
    ('Antalya Korkuteli Devlet Hastanesi', 'Antalya', 'Korkuteli', 'state_hospital'),
    ('Antalya Kumluca Devlet Hastanesi', 'Antalya', 'Kumluca', 'state_hospital'),
    ('Antalya Manavgat Devlet Hastanesi', 'Antalya', 'Manavgat', 'state_hospital'),
    ('Antalya Atatürk Devlet Hastanesi', 'Antalya', 'Muratpaşa', 'state_hospital'),
    ('Antalya Eğitim Ve Araştırma Hastanesi', 'Antalya', 'Muratpaşa', 'training_and_research_hospital'),
    ('Antalya Serik Devlet Hastanesi', 'Antalya', 'Serik', 'state_hospital'),
    ('Ardahan Göle Devlet Hastanesi', 'Ardahan', 'Göle', 'state_hospital'),
    ('Ardahan Devlet Hastanesi', 'Ardahan', 'Merkez', 'state_hospital'),
    ('Aydın Çine Devlet Hastanesi', 'Aydın', 'Çine', 'state_hospital'),
    ('Aydın Didim Devlet Hastanesi', 'Aydın', 'Didim', 'state_hospital'),
    ('Aydın Germencik Devlet Hastanesi', 'Aydın', 'Germencik', 'state_hospital'),
    ('Aydın Kuşadası Devlet Hastanesi', 'Aydın', 'Kuşadası', 'state_hospital'),
    ('Aydın Atatürk Devlet Hastanesi', 'Aydın', 'Merkez', 'state_hospital'),
    ('Aydın Devlet Hastanesi', 'Aydın', 'Merkez', 'state_hospital'),
    ('Aydın Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Aydın', 'Merkez', 'state_hospital'),
    ('Aydın Nazilli Devlet Hastanesi', 'Aydın', 'Nazilli', 'state_hospital'),
    ('Aydın Söke Fehime Faik Kocagöz Devlet Hastanesi', 'Aydın', 'Söke', 'state_hospital'),
    ('Balıkesir Ayvalık Devlet Hastanesi', 'Balıkesir', 'Ayvalık', 'state_hospital'),
    ('Balıkesir Bandırma Devlet Hastanesi', 'Balıkesir', 'Bandırma', 'state_hospital'),
    ('Balıkesir Bigadiç Devlet Hastanesi', 'Balıkesir', 'Bigadiç', 'state_hospital'),
    ('Balıkesir Burhaniye Devlet Hastanesi', 'Balıkesir', 'Burhaniye', 'state_hospital'),
    ('Balıkesir Dursunbey Devlet Hastanesi', 'Balıkesir', 'Dursunbey', 'state_hospital'),
    ('Balıkesir Edremit Devlet Hastanesi', 'Balıkesir', 'Edremit', 'state_hospital'),
    ('Balıkesir Erdek Neyyire Sıtkı Devlet Hastanesi', 'Balıkesir', 'Erdek', 'state_hospital'),
    ('Balıkesir Gönen Devlet Hastanesi', 'Balıkesir', 'Gönen', 'state_hospital'),
    ('Balıkesir Havran Devlet Hastanesi', 'Balıkesir', 'Havran', 'state_hospital'),
    ('Balıkesir İvrindi Devlet Hastanesi', 'Balıkesir', 'İvrindi', 'state_hospital'),
    ('Balıkesir Manyas Devlet Hastanesi', 'Balıkesir', 'Manyas', 'state_hospital'),
    ('Balıkesir Atatürk Devlet Hastanesi', 'Balıkesir', 'Merkez', 'state_hospital'),
    ('Balıkesir Devlet Hastanesi', 'Balıkesir', 'Merkez', 'state_hospital'),
    ('Balıkesir Göğüs Hastalıkları Hastanesi', 'Balıkesir', 'Merkez', 'state_hospital'),
    ('Balıkesir Savaştepe Devlet Hastanesi', 'Balıkesir', 'Savaştepe', 'state_hospital'),
    ('Balıkesir Sındırgı Devlet Hastanesi', 'Balıkesir', 'Sındırgı', 'state_hospital'),
    ('Balıkesir Susurluk Devlet Hastanesi', 'Balıkesir', 'Susurluk', 'state_hospital'),
    ('Bartın Devlet Hastanesi', 'Bartın', 'Merkez', 'state_hospital'),
    ('Batman Gercüş Devlet Hastanesi', 'Batman', 'Gercüş', 'state_hospital'),
    ('Batman Kozluk Devlet Hastanesi', 'Batman', 'Kozluk', 'state_hospital'),
    ('Batman Bölge Devlet Hastanesi', 'Batman', 'Merkez', 'state_hospital'),
    ('Batman Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Batman', 'Merkez', 'state_hospital'),
    ('Batman Sason Devlet Hastanesi', 'Batman', 'Sason', 'state_hospital'),
    ('Bayburt Devlet Hastanesi', 'Bayburt', 'Merkez', 'state_hospital'),
    ('Bingöl Genç Devlet Hastanesi', 'Bingöl', 'Genç', 'state_hospital'),
    ('Bingöl Karlıova İlçe Hastanesi', 'Bingöl', 'Karlıova', 'state_hospital'),
    ('Bingöl Devlet Hastanesi', 'Bingöl', 'Merkez', 'state_hospital'),
    ('Bingöl Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Bingöl', 'Merkez', 'state_hospital'),
    ('Bingöl Solhan Devlet Hastanesi', 'Bingöl', 'Solhan', 'state_hospital'),
    ('Bitlis Adilcevaz Onkoloji Hastanesi', 'Bitlis', 'Adilcevaz', 'state_hospital'),
    ('Bitlis Ahlat Devlet Hastanesi', 'Bitlis', 'Ahlat', 'state_hospital'),
    ('Bitlis Güroymak Devlet Hastanesi', 'Bitlis', 'Güroymak', 'state_hospital'),
    ('Bitlis Hizan İlçe Hastanesi', 'Bitlis', 'Hizan', 'state_hospital'),
    ('Bitlis Devlet Hastanesi', 'Bitlis', 'Merkez', 'state_hospital'),
    ('Bitlis Mutki İlçe Hastanesi', 'Bitlis', 'Mutki', 'state_hospital'),
    ('Bitlis Tatvan Devlet Hastanesi', 'Bitlis', 'Tatvan', 'state_hospital'),
    ('Bolu Gerede Devlet Hastanesi', 'Bolu', 'Gerede', 'state_hospital'),
    ('Bolu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Bolu', 'Merkez', 'state_hospital'),
    ('Bolu İzzet Baysal Devlet Hastanesi', 'Bolu', 'Merkez', 'state_hospital'),
    ('Bolu İzzet Baysal Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Bolu', 'Merkez', 'state_hospital'),
    ('Bolu Mudurnu İlçe Hastanesi', 'Bolu', 'Mudurnu', 'state_hospital'),
    ('Burdur Bucak Devlet Hastanesi', 'Burdur', 'Bucak', 'state_hospital'),
    ('Burdur Gölhisar Devlet Hastanesi', 'Burdur', 'Gölhisar', 'state_hospital'),
    ('Burdur Devlet Hastanesi', 'Burdur', 'Merkez', 'state_hospital'),
    ('Burdur Yeşilova Devlet Hastanesi', 'Burdur', 'Yeşilova', 'state_hospital'),
    ('Bursa Gemlik Muammer Ağım Devlet Hastanesi', 'Bursa', 'Gemlik', 'state_hospital'),
    ('Bursa İnegöl Devlet Hastanesi', 'Bursa', 'İnegöl', 'state_hospital'),
    ('Bursa İznik Devlet Hastanesi', 'Bursa', 'İznik', 'state_hospital'),
    ('Bursa Karacabey Devlet Hastanesi', 'Bursa', 'Karacabey', 'state_hospital'),
    ('Bursa M.Kemalpaşa Devlet Hastanesi', 'Bursa', 'M.kemalpaşa', 'state_hospital'),
    ('Bursa Mudanya Şaziye Rüştü Devlet Hastanesi', 'Bursa', 'Mudanya', 'state_hospital'),
    ('Bursa Dörtçelik Çocuk Hastalıkları Hastanesi', 'Bursa', 'Nilüfer', 'state_hospital'),
    ('Bursa Orhaneli Devlet Hastanesi', 'Bursa', 'Orhaneli', 'state_hospital'),
    ('Bursa Orhangazi Devlet Hastanesi', 'Bursa', 'Orhangazi', 'state_hospital'),
    ('Bursa Ali Osman Sönmez Onkoloji Hastanesi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Çekirge Devlet Hastanesi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Devlet Hastanesi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Dr. Ayten Bozkaya Spastik Çocuklar Hastanesi Ve Rehabilitasyon Merkezi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Zübeyde Hanım Doğumevi', 'Bursa', 'Osmangazi', 'state_hospital'),
    ('Bursa Yenişehir Devlet Hastanesi', 'Bursa', 'Yenişehir', 'state_hospital'),
    ('Bursa Prof.Dr. Türkan Akyol Göğüs Hastalıkları Hastanesi', 'Bursa', 'Yıldırım', 'state_hospital'),
    ('Bursa Şevket Yılmaz Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım', 'training_and_research_hospital'),
    ('Bursa Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım', 'training_and_research_hospital'),
    ('Çanakkale Ayvacık Devlet Hastanesi', 'Çanakkale', 'Ayvacık', 'state_hospital'),
    ('Çanakkale Bayramiç Devlet Hastanesi', 'Çanakkale', 'Bayramiç', 'state_hospital'),
    ('Çanakkale Biga Devlet Hastanesi', 'Çanakkale', 'Biga', 'state_hospital'),
    ('Çanakkale Çan Devlet Hastanesi', 'Çanakkale', 'Çan', 'state_hospital'),
    ('Çanakkale Ezine Devlet Hastanesi', 'Çanakkale', 'Ezine', 'state_hospital'),
    ('Çanakkale Gelibolu Devlet Hastanesi', 'Çanakkale', 'Gelibolu', 'state_hospital'),
    ('Çanakkale Gökçeada Devlet Hastanesi', 'Çanakkale', 'Gökçeada', 'state_hospital'),
    ('Çanakkale Lapseki Devlet Hastanesi', 'Çanakkale', 'Lapseki', 'state_hospital'),
    ('Çanakkale Devlet Hastanesi', 'Çanakkale', 'Merkez', 'state_hospital'),
    ('Çanakkale Yenice Devlet Hastanesi', 'Çanakkale', 'Yenice', 'state_hospital'),
    ('Çankırı Çerkeş Devlet Hastanesi', 'Çankırı', 'Çerkeş', 'state_hospital'),
    ('Çankırı Ilgaz Devlet Hastanesi', 'Çankırı', 'Ilgaz', 'state_hospital'),
    ('Çankırı Kurşunlu İlçe Hastanesi', 'Çankırı', 'Kurşunlu', 'state_hospital'),
    ('Çankırı Devlet Hastanesi', 'Çankırı', 'Merkez', 'state_hospital'),
    ('Çorum Alaca Devlet Hastanesi', 'Çorum', 'Alaca', 'state_hospital'),
    ('Çorum Bayat Devlet Hastanesi', 'Çorum', 'Bayat', 'state_hospital'),
    ('Çorum İskilip Devlet Hastanesi', 'Çorum', 'İskilip', 'state_hospital'),
    ('Çorum Kargı Devlet Hastanesi', 'Çorum', 'Kargı', 'state_hospital'),
    ('Çorum Mecitözü Devlet Hastanesi', 'Çorum', 'Mecitözü', 'state_hospital'),
    ('Çorum Göğüs Hastalıkları Hastanesi', 'Çorum', 'Merkez', 'state_hospital'),
    ('Çorum T.C. Sağlık Bakanlığı Hitit Üniversitesi Çorum Eğitim Ve Araştırma Hastanesi', 'Çorum', 'Merkez', 'university_hospital'),
    ('Çorum Osmancık Devlet Hastanesi', 'Çorum', 'Osmancık', 'state_hospital'),
    ('Çorum Sungurlu Devlet Hastanesi', 'Çorum', 'Sungurlu', 'state_hospital'),
    ('Denizli Acıpayam Devlet Hastanesi', 'Denizli', 'Acıpayam', 'state_hospital'),
    ('Denizli Buldan Göğüs Hastalıkları Hastanesi', 'Denizli', 'Buldan', 'state_hospital'),
    ('Denizli Çal Devlet Hastanesi', 'Denizli', 'Çal', 'state_hospital'),
    ('Denizli Çameli Devlet Hastanesi', 'Denizli', 'Çameli', 'state_hospital'),
    ('Denizli Çivril Devlet Hastanesi', 'Denizli', 'Çivril', 'state_hospital'),
    ('Denizli Honaz Devlet Hastanesi', 'Denizli', 'Honaz', 'state_hospital'),
    ('Denizli Kale Devlet Hastanesi', 'Denizli', 'Kale', 'state_hospital'),
    ('Denizli Devlet Hastanesi', 'Denizli', 'Merkez', 'state_hospital'),
    ('Denizli Servergazi Devlet Hastanesi', 'Denizli', 'Merkez', 'state_hospital'),
    ('Denizli Sarayköy Devlet Hastanesi', 'Denizli', 'Sarayköy', 'state_hospital'),
    ('Denizli Tavas Devlet Hastanesi', 'Denizli', 'Tavas', 'state_hospital'),
    ('Diyarbakır Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Bağlar', 'state_hospital'),
    ('Diyarbakır Bismil Devlet Hastanesi', 'Diyarbakır', 'Bismil', 'state_hospital'),
    ('Diyarbakır Çermik Devlet Hastanesi', 'Diyarbakır', 'Çermik', 'state_hospital'),
    ('Diyarbakır Çınar İlçe Hastanesi', 'Diyarbakır', 'Çınar', 'state_hospital'),
    ('Diyarbakır Dicle İlçe Hastanesi', 'Diyarbakır', 'Dicle', 'state_hospital'),
    ('Diyarbakır Eğil İlçe Hastanesi', 'Diyarbakır', 'Eğil', 'state_hospital'),
    ('Diyarbakır Ergani Devlet Hastanesi', 'Diyarbakır', 'Ergani', 'state_hospital'),
    ('Diyarbakır Hani İlçe Hastanesi', 'Diyarbakır', 'Hani', 'state_hospital'),
    ('Diyarbakır Eğitim Ve Araştırma Hastanesi', 'Diyarbakır', 'Kayapınar', 'training_and_research_hospital'),
    ('Diyarbakır Kulp İlçe Hastanesi', 'Diyarbakır', 'Kulp', 'state_hospital'),
    ('Diyarbakır Lice Halis Toprak Vakfı İlçe Hastanesi', 'Diyarbakır', 'Lice', 'state_hospital'),
    ('Diyarbakır Silvan Dr. Yusuf Azizoğlu Devlet Hastanesi', 'Diyarbakır', 'Silvan', 'state_hospital'),
    ('Diyarbakır Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Yenişehir', 'state_hospital'),
    ('Diyarbakır Devlet Hastanesi', 'Diyarbakır', 'Yenişehir', 'state_hospital'),
    ('Düzce Akçakoca Devlet Hastanesi', 'Düzce', 'Akçakoca', 'state_hospital'),
    ('Düzce Atatürk Devlet Hastanesi', 'Düzce', 'Merkez', 'state_hospital'),
    ('Edirne Keşan Devlet Hastanesi', 'Edirne', 'Keşan', 'state_hospital'),
    ('Edirne Devlet Hastanesi', 'Edirne', 'Merkez', 'state_hospital'),
    ('Edirne Uzunköprü Devlet Hastanesi', 'Edirne', 'Uzunköprü', 'state_hospital'),
    ('Elazığ Karakoçan Devlet Hastanesi', 'Elazığ', 'Karakoçan', 'state_hospital'),
    ('Elazığ Kovancılar Devlet Hastanesi', 'Elazığ', 'Kovancılar', 'state_hospital'),
    ('Elazığ Maden Devlet Hastanesi', 'Elazığ', 'Maden', 'state_hospital'),
    ('Elazığ Eğitim Ve Araştırma Hastanesi', 'Elazığ', 'Merkez', 'training_and_research_hospital'),
    ('Elazığ Harput Devlet Hastanesi', 'Elazığ', 'Merkez', 'state_hospital'),
    ('Elazığ Ruh Sağlıgı Ve Hastalıkları Hastanesi', 'Elazığ', 'Merkez', 'state_hospital'),
    ('Elazığ Palu Devlet Hastanesi', 'Elazığ', 'Palu', 'state_hospital'),
    ('Erzincan Mengücek Gazi Eğitim Ve Araştırma Hastanesi', 'Erzincan', 'Mengücek', 'training_and_research_hospital'),
    ('Erzincan Refahiye Dr. Fahrettin Uğur İlçe Hastanesi', 'Erzincan', 'Refahiye', 'state_hospital'),
    ('Erzincan Tercan Devlet Hastanesi', 'Erzincan', 'Tercan', 'state_hospital'),
    ('Erzurum Aşkale İlçe Hastanesi', 'Erzurum', 'Aşkale', 'state_hospital'),
    ('Erzurum Çat İlçe Hastanesi', 'Erzurum', 'Çat', 'state_hospital'),
    ('Erzurum Hınıs Devlet Hastanesi', 'Erzurum', 'Hınıs', 'state_hospital'),
    ('Erzurum Horasan Devlet Hastanesi', 'Erzurum', 'Horasan', 'state_hospital'),
    ('Erzurum İspir Devlet Hastanesi', 'Erzurum', 'İspir', 'state_hospital'),
    ('Erzurum Karaçoban İlçe Hastanesi', 'Erzurum', 'Karaçoban', 'state_hospital'),
    ('Erzurum Türk Eczacıları Birliği Karayazı İlçe Hastanesi', 'Erzurum', 'Karayazı', 'state_hospital'),
    ('Erzurum Oltu Devlet Hastanesi', 'Erzurum', 'Oltu', 'state_hospital'),
    ('Erzurum Nenehatun Kadın Doğum Hastanesi', 'Erzurum', 'Palandöken', 'state_hospital'),
    ('Erzurum Pasinler İbrahim Hakkı Devlet Hastanesi', 'Erzurum', 'Pasinler', 'state_hospital'),
    ('Erzurum Tekman Devlet Hastanesi', 'Erzurum', 'Tekman', 'state_hospital'),
    ('Erzurum Tortum İlçe Hastanesi', 'Erzurum', 'Tortum', 'state_hospital'),
    ('Erzurum Bölge Eğitim Ve Araştırma Hastanesi', 'Erzurum', 'Yakutiye', 'training_and_research_hospital'),
    ('Erzurum Palandöken Devlet Hastanesi', 'Erzurum', 'Yakutiye', 'state_hospital'),
    ('Eskişehir Çifteler Devlet Hastanesi', 'Eskişehir', 'Çifteler', 'state_hospital'),
    ('Eskişehir Günyüzü İlçe Hastanesi', 'Eskişehir', 'Günyüzü', 'state_hospital'),
    ('Eskişehir Mahmudiye İlçe Hastanesi', 'Eskişehir', 'Mahmudiye', 'state_hospital'),
    ('Eskişehir Mihalıççık Gün Sazak İlçe Hastanesi', 'Eskişehir', 'Mihalıççık', 'state_hospital'),
    ('Eskişehir Devlet Hastanesi', 'Eskişehir', 'Odunpazarı', 'state_hospital'),
    ('Eskişehir Sivrihisar Devlet Hastanesi', 'Eskişehir', 'Sivrihisar', 'state_hospital'),
    ('Eskişehir Yunus Emre Devlet Hastanesi', 'Eskişehir', 'Tepebaşı', 'state_hospital'),
    ('Gaziantep Araban İlçe Hastanesi', 'Gaziantep', 'Araban', 'state_hospital'),
    ('Gaziantep İslahiye Devlet Hastanesi', 'Gaziantep', 'İslahiye', 'state_hospital'),
    ('Gaziantep Nizip Devlet Hastanesi', 'Gaziantep', 'Nizip', 'state_hospital'),
    ('Gaziantep Nurdağı İlçe Hastanesi', 'Gaziantep', 'Nurdağı', 'state_hospital'),
    ('Gaziantep Oğuzeli İlçe Hastanesi', 'Gaziantep', 'Oğuzeli', 'state_hospital'),
    ('Gaziantep Dr. Ersin Arslan Devlet Hastanesi', 'Gaziantep', 'Şahinbey', 'state_hospital'),
    ('Gaziantep 25 Aralık Devlet Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Gaziantep Cengiz Gökçek Kadın Hastalıkları Ve Doğum Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Gaziantep Çocuk Hastalıkları Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Gaziantep Şehitkamil Devlet Hastanesi', 'Gaziantep', 'Şehitkamil', 'state_hospital'),
    ('Giresun Alucra İlçe Hastanesi', 'Giresun', 'Alucra', 'state_hospital'),
    ('Giresun Bulancak Devlet Hastanesi', 'Giresun', 'Bulancak', 'state_hospital'),
    ('Giresun Dereli İlçe Hastanesi', 'Giresun', 'Dereli', 'state_hospital'),
    ('Giresun Espiye Devlet Hastanesi', 'Giresun', 'Espiye', 'state_hospital'),
    ('Giresun Op.Dr. Ergun Özdemir Görele Devlet Hastanesi', 'Giresun', 'Görele', 'state_hospital'),
    ('Giresun Dr. A.İlhan Özdemir Devlet Hastanesi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Dr. Ali Menekşe Göğüs Hastalıkları Hastanesi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Giresun', 'Merkez', 'state_hospital'),
    ('Giresun Ş.Karahisar Devlet Hastanesi', 'Giresun', 'Şebinkarahisar', 'state_hospital'),
    ('Giresun Tirebolu Devlet Hastanesi', 'Giresun', 'Tirebolu', 'state_hospital'),
    ('Giresun Yağlıdere İlçe Hastanesi', 'Giresun', 'Yağlıdere', 'state_hospital'),
    ('Gümüşhane Kelkit Devlet Hastanesi', 'Gümüşhane', 'Kelkit', 'state_hospital'),
    ('Gümüşhane Devlet Hastanesi', 'Gümüşhane', 'Merkez', 'state_hospital'),
    ('Gümüşhane Şiran Devlet Hastanesi', 'Gümüşhane', 'Şiran', 'state_hospital'),
    ('Iğdır Devlet Hastanesi', 'Iğdır', 'Merkez', 'state_hospital'),
    ('Iğdır Tuzluca Devlet Hastanesi', 'Iğdır', 'Tuzluca', 'state_hospital'),
    ('Isparta Eğirdir Kemik Eklem Hastalıkları Tedavi Ve Rehabilitasyon Hastanesi', 'Isparta', 'Eğirdir', 'state_hospital'),
    ('Isparta Devlet Hastanesi', 'Isparta', 'Merkez', 'state_hospital'),
    ('Isparta Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Isparta', 'Merkez', 'state_hospital'),
    ('Isparta Şarkikaraağaç Devlet Hastanesi', 'Isparta', 'Şarkikaraağaç', 'state_hospital'),
    ('Isparta Yalvaç Devlet Hastanesi', 'Isparta', 'Yalvaç', 'state_hospital'),
    ('İzmir Aliağa Devlet Hastanesi', 'İzmir', 'Aliağa', 'state_hospital'),
    ('İzmir Bayındır Devlet Hastanesi', 'İzmir', 'Bayındır', 'state_hospital'),
    ('İzmir Dr. Faruk İlker Bergama Devlet Hastanesi', 'İzmir', 'Bergama', 'state_hospital'),
    ('İzmir Bornova Türkan Özilhan Devlet Hastanesi', 'İzmir', 'Bornova', 'state_hospital'),
    ('İzmir Buca Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'İzmir', 'Buca', 'state_hospital'),
    ('İzmir Buca Seyfi Demirsoy Devlet Hastanesi', 'İzmir', 'Buca', 'state_hospital'),
    ('İzmir Alper Çizgenakat Çeşme Devlet Hastanesi', 'İzmir', 'Çeşme', 'state_hospital'),
    ('İzmir Çiğli Devlet Hastanesi', 'İzmir', 'Çiğli', 'state_hospital'),
    ('İzmir Dikili Devlet Hastanesi', 'İzmir', 'Dikili', 'state_hospital'),
    ('İzmir Foça Devlet Hastanesi', 'İzmir', 'Foça', 'state_hospital'),
    ('İzmir Gaziemir Nevvar Salih İşgören Devlet Hastanesi', 'İzmir', 'Gaziemir', 'state_hospital'),
    ('İzmir Bozyaka Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Karabağlar', 'training_and_research_hospital'),
    ('İzmir Katip Çelebi Üniversitesi Atatürk Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Karabağlar', 'university_hospital'),
    ('İzmir Karşıyaka Devlet Hastanesi', 'İzmir', 'Karşıyaka', 'state_hospital'),
    ('İzmir Kemalpaşa Devlet Hastanesi', 'İzmir', 'Kemalpaşa', 'state_hospital'),
    ('İzmir Kiraz Devlet Hastanesi', 'İzmir', 'Kiraz', 'state_hospital'),
    ('İzmir Alsancak Nevvar Salih İşgören Devlet Hastanesi', 'İzmir', 'Konak', 'state_hospital'),
    ('İzmir Dr. Behçet Uz Çocuk Hastalıkları Ve Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Konak', 'training_and_research_hospital'),
    ('İzmir Dr. Suat Seren Göğüs Hastalıkları Ve Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Konak', 'training_and_research_hospital'),
    ('İzmir Eğitim Diş Hastanesi', 'İzmir', 'Konak', 'training_and_research_hospital'),
    ('İzmir Tepecik Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Konak', 'training_and_research_hospital'),
    ('İzmir Menemen Devlet Hastanesi', 'İzmir', 'Menemen', 'state_hospital'),
    ('İzmir Ödemiş Devlet Hastanesi', 'İzmir', 'Ödemiş', 'state_hospital'),
    ('İzmir Nejat Hepkon Seferihisar Devlet Hastanesi', 'İzmir', 'Seferihisar', 'state_hospital'),
    ('İzmir Selçuk Devlet Hastanesi', 'İzmir', 'Selçuk', 'state_hospital'),
    ('İzmir Tire Devlet Hastanesi', 'İzmir', 'Tire', 'state_hospital'),
    ('İzmir M.Enver Şenerdem Torbalı Devlet Hastanesi', 'İzmir', 'Torbalı', 'state_hospital'),
    ('İzmir Urla Devlet Hastanesi', 'İzmir', 'Urla', 'state_hospital'),
    ('Kahramanmaraş Afşin Devlet Hastanesi', 'Kahramanmaraş', 'Afşin', 'state_hospital'),
    ('Kahramanmaraş Andırın Devlet Hastanesi', 'Kahramanmaraş', 'Andırın', 'state_hospital'),
    ('Kahramanmaraş Çağlayancerit İlçe Hastanesi', 'Kahramanmaraş', 'Çağlayancerit', 'state_hospital'),
    ('Kahramanmaraş Elbistan Devlet Hastanesi', 'Kahramanmaraş', 'Elbistan', 'state_hospital'),
    ('Kahramanmaraş Dr. Süreyya Adanalı Göksun Devlet Hastanesi', 'Kahramanmaraş', 'Göksun', 'state_hospital'),
    ('Kahramanmaraş Necip Fazıl Şehir Devlet Hastanesi', 'Kahramanmaraş', 'Merkez', 'state_hospital'),
    ('Kahramanmaraş Pazarcık Devlet Hastanesi', 'Kahramanmaraş', 'Pazarcık', 'state_hospital'),
    ('Kahramanmaraş Türkoğlu Dr. Kemal Beyazıt Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Kahramanmaraş', 'Türkoğlu', 'state_hospital'),
    ('Karabük Sağlık Bakanlığı Karabük Üniversitesi Karabük Eğitim Ve Araştırma Hastanesi', 'Karabük', 'Merkez', 'university_hospital'),
    ('Karabük Safranbolu Devlet Hastanesi', 'Karabük', 'Safranbolu', 'state_hospital'),
    ('Karabük Yenice Devlet Hastanesi', 'Karabük', 'Yenice', 'state_hospital'),
    ('Karaman Ermenek Devlet Hastanesi', 'Karaman', 'Ermenek', 'state_hospital'),
    ('Karaman Devlet Hastanesi', 'Karaman', 'Merkez', 'state_hospital'),
    ('Kars Kağızman Devlet Hastanesi', 'Kars', 'Kağızman', 'state_hospital'),
    ('Kars Devlet Hastanesi', 'Kars', 'Merkez', 'state_hospital'),
    ('Kars Sarıkamış Devlet Hastanesi', 'Kars', 'Sarıkamış', 'state_hospital'),
    ('Kars Selim İlçe Hastanesi', 'Kars', 'Selim', 'state_hospital'),
    ('Kastamonu Araç İlçe Devlet Hastanesi', 'Kastamonu', 'Araç', 'state_hospital'),
    ('Kastamonu Azdavay İlçe Hastanesi', 'Kastamonu', 'Azdavay', 'state_hospital'),
    ('Kastamonu Bozkurt Devlet Hastanesi', 'Kastamonu', 'Bozkurt', 'state_hospital'),
    ('Kastamonu Cide Devlet Hastanesi', 'Kastamonu', 'Cide', 'state_hospital'),
    ('Kastamonu Daday Devlet Hastanesi', 'Kastamonu', 'Daday', 'state_hospital'),
    ('Kastamonu Devrekani Devlet Hastanesi', 'Kastamonu', 'Devrekani', 'state_hospital'),
    ('Kastamonu İnebolu Devlet Hastanesi', 'Kastamonu', 'İnebolu', 'state_hospital'),
    ('Kastamonu Dr. Münif İslamoğlu Devlet Hastanesi', 'Kastamonu', 'Merkez', 'state_hospital'),
    ('Kastamonu Rehabilitasyon Merkezi', 'Kastamonu', 'Merkez', 'state_hospital'),
    ('Kastamonu Taşköprü Devlet Hastanesi', 'Kastamonu', 'Taşköprü', 'state_hospital'),
    ('Kastamonu Tosya Devlet Hastanesi', 'Kastamonu', 'Tosya', 'state_hospital'),
    ('Kayseri Bünyan Devlet Hastanesi', 'Kayseri', 'Bünyan', 'state_hospital'),
    ('Kayseri Develi Devlet Hastanesi', 'Kayseri', 'Develi', 'state_hospital'),
    ('Kayseri İncesu İlçe Hastanesi', 'Kayseri', 'İncesu', 'state_hospital'),
    ('Kayseri Eğitim Ve Araştırma Hastanesi', 'Kayseri', 'Kocasinan', 'training_and_research_hospital'),
    ('Kayseri Pınarbaşı İlçe Hastanesi', 'Kayseri', 'Pınarbaşı', 'state_hospital'),
    ('Kayseri Tomarza Devlet Hastanesi', 'Kayseri', 'Tomarza', 'state_hospital'),
    ('Kayseri Yahyalı Devlet Hastanesi', 'Kayseri', 'Yahyalı', 'state_hospital'),
    ('Kayseri Yeşilhisarilçe Devlet Hastanesi', 'Kayseri', 'Yeşilhisar', 'state_hospital'),
    ('Kırıkkale Yüksek İhtisas Hastanesi', 'Kırıkkale', 'Merkez', 'state_hospital'),
    ('Kırklareli Babaeski Devlet Hastanesi', 'Kırklareli', 'Babaeski', 'state_hospital'),
    ('Kırklareli Lüleburgaz Devlet Hastanesi', 'Kırklareli', 'Lüleburgaz', 'state_hospital'),
    ('Kırklareli Devlet Hastanesi', 'Kırklareli', 'Merkez', 'state_hospital'),
    ('Kırklareli Pınarhisar Devlet Hastanesi', 'Kırklareli', 'Pınarhisar', 'state_hospital'),
    ('Kırklareli Vize Devlet Hastanesi', 'Kırklareli', 'Vize', 'state_hospital'),
    ('Kırşehir Kaman Devlet Hastanesi', 'Kırşehir', 'Kaman', 'state_hospital'),
    ('Kırşehir Ahi Evran Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Kırşehir', 'Merkez', 'university_hospital'),
    ('Kırşehir Mucur Devlet Hastanesi', 'Kırşehir', 'Mucur', 'state_hospital'),
    ('Kilis Devlet Hastanesi', 'Kilis', 'Merkez', 'state_hospital'),
    ('Kocaeli Darıca Farabi Devlet Hastanesi', 'Kocaeli', 'Darıca', 'state_hospital'),
    ('Kocaeli Derince Eğitim Ve Araştırma Hastanesi', 'Kocaeli', 'Derince', 'training_and_research_hospital'),
    ('Kocaeli Gebze Fatih Devlet Hastanesi', 'Kocaeli', 'Gebze', 'state_hospital'),
    ('Kocaeli Gölcük Necati Çelik Devlet Hastanesi', 'Kocaeli', 'Gölcük', 'state_hospital'),
    ('Kocaeli Devlet Hastanesi', 'Kocaeli', 'İzmit', 'state_hospital'),
    ('Kocaeli İzmit Seka Devlet Hastanesi', 'Kocaeli', 'İzmit', 'state_hospital'),
    ('Kocaeli Kandıra Kazım Dinç Devlet Hastanesi', 'Kocaeli', 'Kandıra', 'state_hospital'),
    ('Kocaeli Karamürsel Devlet Hastanesi', 'Kocaeli', 'Karamürsel', 'state_hospital'),
    ('Kocaeli Körfez Devlet Hastanesi', 'Kocaeli', 'Körfez', 'state_hospital'),
    ('Konya Akşehir Devlet Hastanesi', 'Konya', 'Akşehir', 'state_hospital'),
    ('Konya Beyşehir Devlet Hastanesi', 'Konya', 'Beyşehir', 'state_hospital'),
    ('Konya Bozkır Devlet Hastanesi', 'Konya', 'Bozkır', 'state_hospital'),
    ('Konya Cihanbeyli Devlet Hastanesi', 'Konya', 'Cihanbeyli', 'state_hospital'),
    ('Konya Çumra Devlet Hastanesi', 'Konya', 'Çumra', 'state_hospital'),
    ('Konya Doğanhisar Devlet Hastanesi', 'Konya', 'Doğanhisar', 'state_hospital'),
    ('Konya Ereğli Devlet Hastanesi', 'Konya', 'Ereğli', 'state_hospital'),
    ('Konya Hadim Devlet Hastanesi', 'Konya', 'Hadim', 'state_hospital'),
    ('Konya Hüyük Devlet Hastanesi', 'Konya', 'Hüyük', 'state_hospital'),
    ('Konya Dr. Vefa Tanır Ilgın Devlet Hastanesi', 'Konya', 'Ilgın', 'state_hospital'),
    ('Konya Kadınhanı Refik Saime Koyuncu Devlet Hastanesi', 'Konya', 'Kadınhanı', 'state_hospital'),
    ('Konya Karapınar Devlet Hastanesi', 'Konya', 'Karapınar', 'state_hospital'),
    ('Konya Kulu Devlet Hastanesi', 'Konya', 'Kulu', 'state_hospital'),
    ('Konya Eğitim Ve Araştırma Hastanesi', 'Konya', 'Meram', 'training_and_research_hospital'),
    ('Konya Sarayönü Devlet Hastanesi', 'Konya', 'Sarayönü', 'state_hospital'),
    ('Konya Beyhekim Devlet Hastanesi', 'Konya', 'Selçuklu', 'state_hospital'),
    ('Konya Dr. Faruk Sükan Doğum Ve Çocuk Bakımevi', 'Konya', 'Selçuklu', 'state_hospital'),
    ('Konya Numune Hastanesi', 'Konya', 'Selçuklu', 'state_hospital'),
    ('Konya Seydişehir Devlet Hastanesi', 'Konya', 'Seydişehir', 'state_hospital'),
    ('Konya Yunak Hacı İzzet Baysal Devlet Hastanesi', 'Konya', 'Yunak', 'state_hospital'),
    ('Kütahya Emet Devlet Hastanesi', 'Kütahya', 'Emet', 'state_hospital'),
    ('Kütahya Gediz Devlet Hastanesi', 'Kütahya', 'Gediz', 'state_hospital'),
    ('Kütahya D.P.Ü. Evliya Çelebi Eğitim Ve Araştırma Hastanesi', 'Kütahya', 'Merkez', 'training_and_research_hospital'),
    ('Kütahya Yoncalı Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Kütahya', 'Merkez', 'state_hospital'),
    ('Kütahya Doç.Dr. İsmail Karakuyu Simav Devlet Hastanesi', 'Kütahya', 'Simav', 'state_hospital'),
    ('Kütahya Doç.Dr. Mustafa Kalemli Tavşanlı Devlet Hastanesi', 'Kütahya', 'Tavşanlı', 'state_hospital'),
    ('Malatya Akçadağ 75.Yıl Devlet Hastanesi', 'Malatya', 'Akçadağ', 'state_hospital'),
    ('Malatya Arapgir İlçe Hastanesi', 'Malatya', 'Arapkir', 'state_hospital'),
    ('Malatya Darende Hulusi Efendi Devlet Hastanesi', 'Malatya', 'Darende', 'state_hospital'),
    ('Malatya Doğanşehir Devlet Hastanesi', 'Malatya', 'Doğanşehir', 'state_hospital'),
    ('Malatya Hekimhan Devlet Hastanesi', 'Malatya', 'Hekimhan', 'state_hospital'),
    ('Malatya Devlet Hastanesi', 'Malatya', 'Merkez', 'state_hospital'),
    ('Malatya Pötürge Devlet Hastanesi', 'Malatya', 'Pötürge', 'state_hospital'),
    ('Malatya Yeşilyurt Hasan Çalık Devlet Hastanesi', 'Malatya', 'Yeşilyurt', 'state_hospital'),
    ('Manisa Akhisar Devlet Hastanesi', 'Manisa', 'Akhisar', 'state_hospital'),
    ('Manisa Alaşehir Devlet Hastanesi', 'Manisa', 'Alaşehir', 'state_hospital'),
    ('Manisa Demirci Devlet Hastanesi', 'Manisa', 'Demirci', 'state_hospital'),
    ('Manisa Gördes Devlet Hastanesi', 'Manisa', 'Gördes', 'state_hospital'),
    ('Manisa Kırkağaç Devlet Hastanesi', 'Manisa', 'Kırkağaç', 'state_hospital'),
    ('Manisa Kula Devlet Hastanesi', 'Manisa', 'Kula', 'state_hospital'),
    ('Manisa Devlet Hastanesi', 'Manisa', 'Merkez', 'state_hospital'),
    ('Manisa Merkezefendi Devlet Hastanesi', 'Manisa', 'Merkez', 'state_hospital'),
    ('Manisa Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Manisa', 'Merkez', 'state_hospital'),
    ('Manisa Salihli Devlet Hastanesi', 'Manisa', 'Salihli', 'state_hospital'),
    ('Manisa Sarıgöl Devlet Hastanesi', 'Manisa', 'Sarıgöl', 'state_hospital'),
    ('Manisa Saruhanlı Devlet Hastanesi', 'Manisa', 'Saruhanlı', 'state_hospital'),
    ('Manisa Selendi Devlet Hastanesi', 'Manisa', 'Selendi', 'state_hospital'),
    ('Manisa Soma Devlet Hastanesi', 'Manisa', 'Soma', 'state_hospital'),
    ('Manisa Turgutlu Devlet Hastanesi', 'Manisa', 'Turgutlu', 'state_hospital'),
    ('Mardin Dargeçit İlçe Hastanesi', 'Mardin', 'Dargeçit', 'state_hospital'),
    ('Mardin Derik Devlet Hastanesi', 'Mardin', 'Derik', 'state_hospital'),
    ('Mardin Kızıltepe Devlet Hastanesi', 'Mardin', 'Kızıltepe', 'state_hospital'),
    ('Mardin Mazıdağı İlçe Hastanesi', 'Mardin', 'Mazıdağı', 'state_hospital'),
    ('Mardin Devlet Hastanesi', 'Mardin', 'Merkez', 'state_hospital'),
    ('Mardin Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Mardin', 'Merkez', 'state_hospital'),
    ('Mardin Midyat Devlet Hastanesi', 'Mardin', 'Midyat', 'state_hospital'),
    ('Mardin Nusaybin Devlet Hastanesi', 'Mardin', 'Nusaybin', 'state_hospital'),
    ('Mardin Savur İlçe Hastanesi', 'Mardin', 'Savur', 'state_hospital'),
    ('Mersin Devlet Hastanesi', 'Mersin', 'Akdeniz', 'state_hospital'),
    ('Mersin Toros Devlet Hastanesi', 'Mersin', 'Akdeniz', 'state_hospital'),
    ('Mersin Anamur Devlet Hastanesi', 'Mersin', 'Anamur', 'state_hospital'),
    ('Mersin Aydıncık Devlet Hastanesi', 'Mersin', 'Aydıncık', 'state_hospital'),
    ('Mersin Bozyazı Devlet Hastanesi', 'Mersin', 'Bozyazı', 'state_hospital'),
    ('Mersin Erdemli Devlet Hastanesi', 'Mersin', 'Erdemli', 'state_hospital'),
    ('Mersin Gülnar Devlet Hastanesi', 'Mersin', 'Gülnar', 'state_hospital'),
    ('Mersin Mut Devlet Hastanesi', 'Mersin', 'Mut', 'state_hospital'),
    ('Mersin Silifke Devlet Hastanesi', 'Mersin', 'Silifke', 'state_hospital'),
    ('Mersin Tarsus Devlet Hastanesi', 'Mersin', 'Tarsus', 'state_hospital'),
    ('Mersin Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Mersin', 'Toroslar', 'state_hospital'),
    ('Muğla Bodrum Devlet Hastanesi', 'Muğla', 'Bodrum', 'state_hospital'),
    ('Muğla Dalaman Devlet Hastanesi', 'Muğla', 'Dalaman', 'state_hospital'),
    ('Muğla Datça Devlet Hastanesi', 'Muğla', 'Datça', 'state_hospital'),
    ('Muğla Fethiye Devlet Hastanesi', 'Muğla', 'Fethiye', 'state_hospital'),
    ('Muğla Köyceğiz Devlet Hastanesi', 'Muğla', 'Köyceğiz', 'state_hospital'),
    ('Muğla Marmaris Devlet Hastanesi', 'Muğla', 'Marmaris', 'state_hospital'),
    ('Muğla T.C.Sağlık Bakanlığı Muğla Sıtkı Koçman Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Muğla', 'Merkez', 'university_hospital'),
    ('Muğla Milas 75.Yıl Devlet Hastanesi', 'Muğla', 'Milas', 'state_hospital'),
    ('Muğla Ortaca Devlet Hastanesi', 'Muğla', 'Ortaca', 'state_hospital'),
    ('Muğla Yatağan Devlet Hastanesi', 'Muğla', 'Yatağan', 'state_hospital'),
    ('Muş Bulanık Devlet Hastanesi', 'Muş', 'Bulanık', 'state_hospital'),
    ('Muş Hasköy Devlet Hastanesi', 'Muş', 'Hasköy', 'state_hospital'),
    ('Muş Korkut İlçe Hastanesi', 'Muş', 'Korkut', 'state_hospital'),
    ('Muş Malazgirt Devlet Hastanesi', 'Muş', 'Malazgirt', 'state_hospital'),
    ('Muş Devlet Hastanesi', 'Muş', 'Merkez', 'state_hospital'),
    ('Muş Varto Devlet Hastanesi', 'Muş', 'Varto', 'state_hospital'),
    ('Nevşehir Dr. İ.Şevki Atasagun Devlet Hastanesi', 'Nevşehir', 'Merkez', 'state_hospital'),
    ('Nevşehir Ürgüp Devlet Hastanesi', 'Nevşehir', 'Ürgüp', 'state_hospital'),
    ('Niğde Bor Devlet Hastanesi', 'Niğde', 'Bor', 'state_hospital'),
    ('Niğde Çiftlik İlçe Hastanesi', 'Niğde', 'Çiftlik', 'state_hospital'),
    ('Niğde Devlet Hastanesi', 'Niğde', 'Merkez', 'state_hospital'),
    ('Niğde Ulukışla İlçe Hastanesi', 'Niğde', 'Ulukışla', 'state_hospital'),
    ('Ordu Akkuş Devlet Hastanesi', 'Ordu', 'Akkuş', 'state_hospital'),
    ('Ordu Aybastı Devlet Hastanesi', 'Ordu', 'Aybastı', 'state_hospital'),
    ('Ordu Fatsa Devlet Hastanesi', 'Ordu', 'Fatsa', 'state_hospital'),
    ('Ordu Gölköy Devlet Hastanesi', 'Ordu', 'Gölköy', 'state_hospital'),
    ('Ordu Gürgentepe Devlet Hastanesi', 'Ordu', 'Gürgentepe', 'state_hospital'),
    ('Ordu Korgan Devlet Hastanesi', 'Ordu', 'Korgan', 'state_hospital'),
    ('Ordu Kumru Devlet Hastanesi', 'Ordu', 'Kumru', 'state_hospital'),
    ('Ordu Devlet Hastanesi', 'Ordu', 'Merkez', 'state_hospital'),
    ('Ordu Sağlık Bakanlığı-ordu Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Ordu', 'Merkez', 'university_hospital'),
    ('Ordu Ulubey Devlet Hastanesi', 'Ordu', 'Ulubey', 'state_hospital'),
    ('Ordu Ünye Devlet Hastanesi', 'Ordu', 'Ünye', 'state_hospital'),
    ('Osmaniye Düziçi Devlet Hastanesi', 'Osmaniye', 'Düziçi', 'state_hospital'),
    ('Osmaniye Kadirli Devlet Hastanesi', 'Osmaniye', 'Kadirli', 'state_hospital'),
    ('Osmaniye Devlet Hastanesi', 'Osmaniye', 'Merkez', 'state_hospital'),
    ('Rize İshakoğlu Çayeli Devlet Hastanesi', 'Rize', 'Çayeli', 'state_hospital'),
    ('Rize Fındıklı Bölge Guatr Araştırma Ve Tedavi Merkezi', 'Rize', 'Fındıklı', 'state_hospital'),
    ('Rize Güneysu Tenzile Erdoğan İlçe Hastanesi', 'Rize', 'Güneysu', 'state_hospital'),
    ('Rize Devlet Hastanesi', 'Rize', 'Merkez', 'state_hospital'),
    ('Rize T.C. Sağlık Bakanlığı Recep Tayyip Erdoğan Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Rize', 'Merkez', 'university_hospital'),
    ('Rize Kaçkar Devlet Hastanesi', 'Rize', 'Pazar', 'state_hospital'),
    ('Sakarya Doğum Ve Çocuk Bakımevi', 'Sakarya', 'Adapazarı', 'state_hospital'),
    ('Sakarya Sağlık Bakanlığı Sakarya Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Sakarya', 'Adapazarı', 'university_hospital'),
    ('Sakarya Yenikent Devlet Hastanesi', 'Sakarya', 'Adapazarı', 'state_hospital'),
    ('Sakarya Akyazı Devlet Hastanesi', 'Sakarya', 'Akyazı', 'state_hospital'),
    ('Sakarya Toyotasa Acil Yardım Hastanesi', 'Sakarya', 'Arifiye', 'state_hospital'),
    ('Sakarya Ferizli İlçe Hastanesi', 'Sakarya', 'Ferizli', 'state_hospital'),
    ('Sakarya Geyve Devlet Hastanesi', 'Sakarya', 'Geyve', 'state_hospital'),
    ('Sakarya Hendek Devlet Hastanesi', 'Sakarya', 'Hendek', 'state_hospital'),
    ('Sakarya Karasu Devlet Hastanesi', 'Sakarya', 'Karasu', 'state_hospital'),
    ('Sakarya Kaynarca İlçe Hastanesi', 'Sakarya', 'Kaynarca', 'state_hospital'),
    ('Sakarya Kocaali İlçe Hastanesi', 'Sakarya', 'Kocaali', 'state_hospital'),
    ('Sakarya Pamukova Devlet Hastanesi', 'Sakarya', 'Pamukova', 'state_hospital'),
    ('Sakarya Sapanca İlçe Hastanesi', 'Sakarya', 'Sapanca', 'state_hospital'),
    ('Samsun 19 Mayıs İlçe (Engiz) Hastanesi', 'Samsun', '19mayıs', 'state_hospital'),
    ('Samsun Alaçam Devlet Hastanesi', 'Samsun', 'Alaçam', 'state_hospital'),
    ('Samsun Asarcık İlçe Hastanesi', 'Samsun', 'Asarcık', 'state_hospital'),
    ('Samsun Ayvacık Devlet Hastanesi', 'Samsun', 'Ayvacık', 'state_hospital'),
    ('Samsun Bafra Devlet Hastanesi', 'Samsun', 'Bafra', 'state_hospital'),
    ('Samsun Çarşamba Devlet Hastanesi', 'Samsun', 'Çarşamba', 'state_hospital'),
    ('Samsun Havza Devlet Hastanesi', 'Samsun', 'Havza', 'state_hospital'),
    ('Samsun Eğitim Ve Araştırma Hastanesi', 'Samsun', 'İlkadım', 'training_and_research_hospital'),
    ('Samsun Fiziksel Tıp Rehabilitasyon Hastalıkları Hastanesi', 'Samsun', 'İlkadım', 'state_hospital'),
    ('Samsun Gazi Devlet Hastanesi', 'Samsun', 'İlkadım', 'state_hospital'),
    ('Samsun Göğüs Hastalıkları Ve Göğüs Cerrahisi Hastanesi', 'Samsun', 'İlkadım', 'state_hospital'),
    ('Samsun Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Samsun', 'İlkadım', 'state_hospital'),
    ('Samsun Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Samsun', 'İlkadım', 'state_hospital'),
    ('Samsun Kavak Devlet Hastanesi', 'Samsun', 'Kavak', 'state_hospital'),
    ('Samsun Ladik Devlet Hastanesi', 'Samsun', 'Ladik', 'state_hospital'),
    ('Samsun Salıpazarı İlçe Hastanesi', 'Samsun', 'Salıpazarı', 'state_hospital'),
    ('Samsun Terme Devlet Hastanesi', 'Samsun', 'Terme', 'state_hospital'),
    ('Samsun Vezirköprü Devlet Hastanesi', 'Samsun', 'Vezirköprü', 'state_hospital'),
    ('Siirt Baykan Devlet Hastanesi', 'Siirt', 'Baykan', 'state_hospital'),
    ('Siirt Eruh İlçe Hastanesi', 'Siirt', 'Eruh', 'state_hospital'),
    ('Siirt Kurtalan Devlet Hastanesi', 'Siirt', 'Kurtalan', 'state_hospital'),
    ('Siirt Devlet Hastanesi', 'Siirt', 'Merkez', 'state_hospital'),
    ('Siirt Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Siirt', 'Merkez', 'state_hospital'),
    ('Siirt Pervari İlçe Hastanesi', 'Siirt', 'Pervari', 'state_hospital'),
    ('Sinop Ayancık Devlet Hastanesi', 'Sinop', 'Ayancık', 'state_hospital'),
    ('Sinop Boyabat 75.Yıl Devlet Hastanesi', 'Sinop', 'Boyabat', 'state_hospital'),
    ('Sinop Durağan Devlet Hastanesi', 'Sinop', 'Durağan', 'state_hospital'),
    ('Sinop Gerze Devlet Hastanesi', 'Sinop', 'Gerze', 'state_hospital'),
    ('Sinop Atatürk Devlet Hastanesi', 'Sinop', 'Merkez', 'state_hospital'),
    ('Sinop Türkeli Devlet Hastanesi', 'Sinop', 'Türkeli', 'state_hospital'),
    ('Şanlıurfa Akçakale Devlet Hastanesi', 'Şanlıurfa', 'Akçakale', 'state_hospital'),
    ('Şanlıurfa Birecik Devlet Hastanesi', 'Şanlıurfa', 'Birecik', 'state_hospital'),
    ('Şanlıurfa Bozova İlçe Hastanesi', 'Şanlıurfa', 'Bozova', 'state_hospital'),
    ('Şanlıurfa Ceylanpınar Devlet Hastanesi', 'Şanlıurfa', 'Ceylanpınar', 'state_hospital'),
    ('Şanlıurfa Halfeti İlçe Hastanesi', 'Şanlıurfa', 'Halfeti', 'state_hospital'),
    ('Şanlıurfa Harran Devlet Hastanesi', 'Şanlıurfa', 'Harran', 'state_hospital'),
    ('Şanlıurfa Hilvan Devlet Hastanesi', 'Şanlıurfa', 'Hilvan', 'state_hospital'),
    ('Şanlıurfa Balıklıgöl Devlet Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('Şanlıurfa Çocuk Hastalıkları Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('Şanlıurfa Eğitim Ve Araştırma Hastanesi', 'Şanlıurfa', 'Merkez', 'training_and_research_hospital'),
    ('Şanlıurfa Kadın Hastalıkları Ve Doğum Hastanesi', 'Şanlıurfa', 'Merkez', 'state_hospital'),
    ('Şanlıurfa Siverek Devlet Hastanesi', 'Şanlıurfa', 'Siverek', 'state_hospital'),
    ('Şanlıurfa Suruç Devlet Hastanesi', 'Şanlıurfa', 'Suruç', 'state_hospital'),
    ('Şanlıurfa Viranşehir Devlet Hastanesi', 'Şanlıurfa', 'Viranşehir', 'state_hospital'),
    ('Tekirdağ Çerkezköy Devlet Hastanesi', 'Tekirdağ', 'Çerkezköy', 'state_hospital'),
    ('Tekirdağ Çorlu Devlet Hastanesi', 'Tekirdağ', 'Çorlu', 'state_hospital'),
    ('Tekirdağ Hayrabolu Devlet Hastanesi', 'Tekirdağ', 'Hayrabolu', 'state_hospital'),
    ('Tekirdağ Marmara Ereğlisi İlçe Devlet Hastanesi', 'Tekirdağ', 'M.ereğlisi', 'state_hospital'),
    ('Tekirdağ Malkara Devlet Hastanesi', 'Tekirdağ', 'Malkara', 'state_hospital'),
    ('Tekirdağ Devlet Hastanesi', 'Tekirdağ', 'Merkez', 'state_hospital'),
    ('Tekirdağ Muratlı Devlet Hastanesi', 'Tekirdağ', 'Muratlı', 'state_hospital'),
    ('Tekirdağ Saray Devlet Hastanesi', 'Tekirdağ', 'Saray', 'state_hospital'),
    ('Tekirdağ Şarköy Devlet Hastanesi', 'Tekirdağ', 'Şarköy', 'state_hospital'),
    ('Tokat Almus İlçe Hastanesi', 'Tokat', 'Almus', 'state_hospital'),
    ('Tokat Erbaa Devlet Hastanesi', 'Tokat', 'Erbaa', 'state_hospital'),
    ('Tokat Devlet Hastanesi', 'Tokat', 'Merkez', 'state_hospital'),
    ('Tokat Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Tokat', 'Merkez', 'state_hospital'),
    ('Tokat Niksar Devlet Hastanesi', 'Tokat', 'Niksar', 'state_hospital'),
    ('Tokat Reşadiye Devlet Hastanesi', 'Tokat', 'Reşadiye', 'state_hospital'),
    ('Tokat Turhal Devlet Hastanesi', 'Tokat', 'Turhal', 'state_hospital'),
    ('Tokat Zile Devlet Hastanesi', 'Tokat', 'Zile', 'state_hospital'),
    ('Trabzon Akçaabat Haçkalı Baba Devlet Hastanesi', 'Trabzon', 'Akçaabat', 'state_hospital'),
    ('Trabzon Araklı Bayram Halil Devlet Hastanesi', 'Trabzon', 'Araklı', 'state_hospital'),
    ('Trabzon Ataköy Ruh Ve Sinir Hastalıkları Hastanesi', 'Trabzon', 'Çaykara', 'state_hospital'),
    ('Trabzon Maçka Ömer Burhanoğlu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Maçka', 'state_hospital'),
    ('Trabzon Ahi Evren Göğüs Kalp Ve Damar Cerrahisi Eğitim Ve Araştırma Hastanesi', 'Trabzon', 'Merkez', 'training_and_research_hospital'),
    ('Trabzon Fatih Devlet Hastanesi', 'Trabzon', 'Merkez', 'state_hospital'),
    ('Trabzon Kanuni Eğitim Ve Araştırma Hastanesi', 'Trabzon', 'Merkez', 'training_and_research_hospital'),
    ('Trabzon Yavuz Selim Kemik Hastalıkları Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Merkez', 'state_hospital'),
    ('Trabzon Of Devlet Hastanesi', 'Trabzon', 'Of', 'state_hospital'),
    ('Trabzon Sürmene Devlet Hastanesi', 'Trabzon', 'Sürmene', 'state_hospital'),
    ('Trabzon Tonya Devlet Hastanesi', 'Trabzon', 'Tonya', 'state_hospital'),
    ('Trabzon Vakfıkebir Devlet Hastanesi', 'Trabzon', 'Vakfıkebir', 'state_hospital'),
    ('Tunceli Devlet Hastanesi', 'Tunceli', 'Merkez', 'state_hospital'),
    ('Uşak Banaz Devlet Hastanesi', 'Uşak', 'Banaz', 'state_hospital'),
    ('Uşak Eşme Devlet Hastanesi', 'Uşak', 'Eşme', 'state_hospital'),
    ('Uşak Devlet Hastanesi', 'Uşak', 'Merkez', 'state_hospital'),
    ('Uşak Sivaslı Devlet Hastanesi', 'Uşak', 'Sivaslı', 'state_hospital'),
    ('Van Bahçesaray İlçe Hastanesi', 'Van', 'Bahçesaray', 'state_hospital'),
    ('Van Başkale Devlet Hastanesi', 'Van', 'Başkale', 'state_hospital'),
    ('Van Çaldıran İlçe Hastanesi', 'Van', 'Çaldıran', 'state_hospital'),
    ('Van Çatak İlçe Hastanesi', 'Van', 'Çatak', 'state_hospital'),
    ('Van Erciş Devlet Hastanesi', 'Van', 'Erciş', 'state_hospital'),
    ('Van Gevaş Devlet Hastanesi', 'Van', 'Gevaş', 'state_hospital'),
    ('Van Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Van', 'İpekyolu', 'state_hospital'),
    ('Van Bölge Eğitim Ve Araştırma Hastanesi', 'Van', 'Merkez', 'training_and_research_hospital'),
    ('Van Muradiye Devlet Hastanesi', 'Van', 'Muradiye', 'state_hospital'),
    ('Van Özalp Devlet Hastanesi', 'Van', 'Özalp', 'state_hospital'),
    ('Yalova Çınarcık Devlet Hastanesi', 'Yalova', 'Çınarcık', 'state_hospital'),
    ('Yalova Devlet Hastanesi', 'Yalova', 'Merkez', 'state_hospital'),
    ('Yozgat Akdağmadeni Devlet Hastanesi', 'Yozgat', 'Akdağmadeni', 'state_hospital'),
    ('Yozgat Boğazlıyan Devlet Hastanesi', 'Yozgat', 'Boğazlıyan', 'state_hospital'),
    ('Yozgat Çekerek Devlet Hastanesi', 'Yozgat', 'Çekerek', 'state_hospital'),
    ('Yozgat Devlet Hastanesi', 'Yozgat', 'Merkez', 'state_hospital'),
    ('Yozgat Saraykent İlçe Hastanesi', 'Yozgat', 'Saraykent', 'state_hospital'),
    ('Yozgat Sarıkaya Devlet Hastanesi', 'Yozgat', 'Sarıkaya', 'state_hospital'),
    ('Yozgat Sorgun Devlet Hastanesi', 'Yozgat', 'Sorgun', 'state_hospital'),
    ('Yozgat Şefaatli Devlet Hastanesi', 'Yozgat', 'Şefaatli', 'state_hospital'),
    ('Yozgat Yerköy Devlet Hastanesi', 'Yozgat', 'Yerköy', 'state_hospital'),
    ('Zonguldak Alaplı Devlet Hastanesi', 'Zonguldak', 'Alaplı', 'state_hospital'),
    ('Zonguldak Çaycuma Devlet Hastanesi', 'Zonguldak', 'Çaycuma', 'state_hospital'),
    ('Zonguldak Devrek Devlet Hastanesi', 'Zonguldak', 'Devrek', 'state_hospital'),
    ('Zonguldak Karadeniz Ereğli Devlet Hastanesi', 'Zonguldak', 'Ereğli', 'state_hospital'),
    ('Zonguldak Gökçebey İlçe Hastanesi', 'Zonguldak', 'Gökçebey', 'state_hospital'),
    ('Zonguldak Atatürk Devlet Hastanesi', 'Zonguldak', 'Merkez', 'state_hospital'),
    ('Zonguldak Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Zonguldak', 'Merkez', 'state_hospital'),
    ('Zonguldak Uzun Mehmet Göğüs Ve Meslek Hastalıkları Hastanesi', 'Zonguldak', 'Merkez', 'state_hospital')
)
insert into public.hospitals (name, city, district, hospital_type)
select name, city, district, hospital_type::public.hospital_type
from hospital_seed s
where not exists (
  select 1 from public.hospitals h
  where lower(h.name)=lower(s.name) and h.city=s.city and h.district=s.district
);

with hospital_seed(name, city, district) as (
  values
    ('Adana Ceyhan Devlet Hastanesi', 'Adana', 'Ceyhan'),
    ('Adana Dr. Ekrem Tok Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Adana', 'Çukurova'),
    ('Adana İmamoğlu Devlet Hastanesi', 'Adana', 'İmamoğlu'),
    ('Adana Karaisalı Devlet Hastanesi', 'Adana', 'Karaisalı'),
    ('Adana Kozan Devlet Hastanesi', 'Adana', 'Kozan'),
    ('Adana Pozantı 80.Yıl Devlet Hastanesi', 'Adana', 'Pozantı'),
    ('Adana Çukurova Dr. Aşkım Tüfekçi Devlet Hastanesi', 'Adana', 'Seyhan'),
    ('Adana Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Adana', 'Seyhan'),
    ('Adana Tufanbeyli Devlet Hastanesi', 'Adana', 'Tufanbeyli'),
    ('Adana Devlet Hastanesi', 'Adana', 'Yüreğir'),
    ('Adana Numune Eğitim Ve Araştırma Hastanesi', 'Adana', 'Yüreğir'),
    ('Adıyaman Besni Devlet Hastanesi', 'Adıyaman', 'Besni'),
    ('Adıyaman Çelikhan Devlet Hastanesi', 'Adıyaman', 'Çelikhan'),
    ('Adıyaman Gölbaşı Devlet Hastanesi', 'Adıyaman', 'Gölbaşı'),
    ('Adıyaman Kahta Devlet Hastanesi', 'Adıyaman', 'Kahta'),
    ('Adıyaman T.C. Sağlık Bakanlığı Adıyaman Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Adıyaman', 'Merkez'),
    ('Afyonkarahisar Dr. Halil İbrahim Özsoy Bolvadin Devlet Hastanesi', 'Afyonkarahisar', 'Bolvadin'),
    ('Afyonkarahisar Çay Devlet Hastanesi', 'Afyonkarahisar', 'Çay'),
    ('Afyonkarahisar Dinar Devlet Hastanesi', 'Afyonkarahisar', 'Dinar'),
    ('Afyonkarahisar Emirdağ Devlet Hastanesi', 'Afyonkarahisar', 'Emirdağ'),
    ('Afyonkarahisar İscehisar Devlet Hastanesi', 'Afyonkarahisar', 'İscehisar'),
    ('Afyonkarahisar Devlet Hastanesi', 'Afyonkarahisar', 'Merkez'),
    ('Afyonkarahisar Zübeyde Hanım Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Afyonkarahisar', 'Merkez'),
    ('Afyonkarahisar Sandıklı Devlet Hastanesi', 'Afyonkarahisar', 'Sandıklı'),
    ('Afyonkarahisar Sinanpaşa İlçe Hastanesi', 'Afyonkarahisar', 'Sinanpaşa'),
    ('Afyonkarahisar Şuhut Devlet Hastanesi', 'Afyonkarahisar', 'Şuhut'),
    ('Ağrı Diyadin Devlet Hastanesi', 'Ağrı', 'Diyadin'),
    ('Ağrı Dr. Yaşar Eryılmaz Doğubeyazıt Devlet Hastanesi', 'Ağrı', 'Doğubeyazıt'),
    ('Ağrı Eleşkirt Devlet Hastanesi', 'Ağrı', 'Eleşkirt'),
    ('Ağrı Hamur İlçe Devlet Hastanesi', 'Ağrı', 'Hamur'),
    ('Ağrı Devlet Hastanesi', 'Ağrı', 'Merkez'),
    ('Ağrı Patnos Devlet Hastanesi', 'Ağrı', 'Patnos'),
    ('Ağrı Taşlıçay İlçe Devlet Hastanesi', 'Ağrı', 'Taşlıçay'),
    ('Ağrı Tutak Devlet Hastanesi', 'Ağrı', 'Tutak'),
    ('Aksaray Eskil Devlet Hastanesi', 'Aksaray', 'Eskil'),
    ('Aksaray Gülağaç İlçe Hastanesi', 'Aksaray', 'Gülağaç'),
    ('Aksaray Devlet Hastanesi', 'Aksaray', 'Merkez'),
    ('Aksaray Ortaköy Devlet Hastanesi', 'Aksaray', 'Ortaköy'),
    ('Amasya Gümüşhacıköy Devlet Hastanesi', 'Amasya', 'Gümüşhacıköy'),
    ('Amasya Sabuncuoğlu Şerefeddin Devlet Hastanesi', 'Amasya', 'Merkez'),
    ('Amasya Merzifon Kara Mustafa Paşa Devlet Hastanesi', 'Amasya', 'Merzifon'),
    ('Amasya Suluova Devlet Hastanesi', 'Amasya', 'Suluova'),
    ('Amasya Taşova Devlet Hastanesi', 'Amasya', 'Taşova'),
    ('Ankara Dışkapı Çocuk Sağlığı Ve Hastalıkları Hematoloji Onkoloji Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Dışkapı Yıldırım Beyazıt Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Dr. Sami Ulus Kadın Doğum Çocuk Sağlığı Ve Hastalıkları Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Dr. Zekai Tahir Burak Kadın Sağlığı Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Fizik Tedavi Ve Rehabilitasyon Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Numune Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Türkiye Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Ulucanlar Göz Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Ulus Devlet Hastanesi', 'Ankara', 'Altındağ'),
    ('Ankara Beypazarı Devlet Hastanesi', 'Ankara', 'Beypazarı'),
    ('Ankara Atatürk Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Çankaya'),
    ('Ankara Halil Şıvgın Çubuk Devlet Hastanesi', 'Ankara', 'Çubuk'),
    ('Ankara Dr. Hulusi Alataş Elmadağ Devlet Hastanesi', 'Ankara', 'Elmadağ'),
    ('Ankara Prof.Dr. Celal Ertuğ Etimesgut Devlet Hastanesi', 'Ankara', 'Etimesgut'),
    ('Ankara Gölbaşı Hasvak Devlet Hastanesi', 'Ankara', 'Gölbaşı'),
    ('Ankara Haymana Devlet Hastanesi', 'Ankara', 'Haymana'),
    ('Ankara Kazan Hamdi Eriş Devlet Hastanesi', 'Ankara', 'Kazan'),
    ('Ankara Atatürk Göğüs Hastalıkları Ve Göğüs Cerrahisi Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Etlik Zübeyde Hanım Kadın Hastalıkları Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Keçiören Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Meslek Hastalıkları Hastanesi', 'Ankara', 'Keçiören'),
    ('Ankara Kızılcahamam Devlet Hastanesi', 'Ankara', 'Kızılcahamam'),
    ('Ankara Nallıhan Devlet Hastanesi', 'Ankara', 'Nallıhan'),
    ('Ankara Polatlı Duatepe Devlet Hastanesi', 'Ankara', 'Polatlı'),
    ('Ankara Sincan Dr. Nafiz Körez Devlet Hastanesi', 'Ankara', 'Sincan'),
    ('Ankara Şereflikoçhisar Devlet Hastanesi', 'Ankara', 'Şereflikoçhisar'),
    ('Ankara Dr. Abdurrahman Yurtaslan Onkoloji Eğitim Ve Araştırma Hastanesi', 'Ankara', 'Yenimahalle'),
    ('Ankara Gazi Mustafa Kemal Devlet Hastanesi', 'Ankara', 'Yenimahalle'),
    ('Ankara Yenimahalle Devlet Hastanesi', 'Ankara', 'Yenimahalle'),
    ('Antalya Akseki Devlet Hastanesi', 'Antalya', 'Akseki'),
    ('Antalya Alanya Devlet Hastanesi', 'Antalya', 'Alanya'),
    ('Antalya Demre Devlet Hastanesi', 'Antalya', 'Demre'),
    ('Antalya Elmalı Devlet Hastanesi', 'Antalya', 'Elmalı'),
    ('Antalya Finike Devlet Hastanesi', 'Antalya', 'Finike'),
    ('Antalya Gazipaşa Devlet Hastanesi', 'Antalya', 'Gazipaşa'),
    ('Antalya Kaş Devlet Hastanesi', 'Antalya', 'Kaş'),
    ('Antalya Kemer Devlet Hastanesi', 'Antalya', 'Kemer'),
    ('Antalya Korkuteli Devlet Hastanesi', 'Antalya', 'Korkuteli'),
    ('Antalya Kumluca Devlet Hastanesi', 'Antalya', 'Kumluca'),
    ('Antalya Manavgat Devlet Hastanesi', 'Antalya', 'Manavgat'),
    ('Antalya Atatürk Devlet Hastanesi', 'Antalya', 'Muratpaşa'),
    ('Antalya Eğitim Ve Araştırma Hastanesi', 'Antalya', 'Muratpaşa'),
    ('Antalya Serik Devlet Hastanesi', 'Antalya', 'Serik'),
    ('Ardahan Göle Devlet Hastanesi', 'Ardahan', 'Göle'),
    ('Ardahan Devlet Hastanesi', 'Ardahan', 'Merkez'),
    ('Artvin Arhavi Devlet Hastanesi', 'Artvin', 'Arhavi'),
    ('Artvin Borçka Devlet Hastanesi', 'Artvin', 'Borçka'),
    ('Artvin Hopa Devlet Hastanesi', 'Artvin', 'Hopa'),
    ('Artvin Devlet Hastanesi', 'Artvin', 'Merkez'),
    ('Artvin Şavşat Devlet Hastanesi', 'Artvin', 'Şavşat'),
    ('Artvin Yusufeli Devlet Hastanesi', 'Artvin', 'Yusufeli'),
    ('Aydın Çine Devlet Hastanesi', 'Aydın', 'Çine'),
    ('Aydın Didim Devlet Hastanesi', 'Aydın', 'Didim'),
    ('Aydın Germencik Devlet Hastanesi', 'Aydın', 'Germencik'),
    ('Aydın Kuşadası Devlet Hastanesi', 'Aydın', 'Kuşadası'),
    ('Aydın Atatürk Devlet Hastanesi', 'Aydın', 'Merkez'),
    ('Aydın Devlet Hastanesi', 'Aydın', 'Merkez'),
    ('Aydın Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Aydın', 'Merkez'),
    ('Aydın Nazilli Devlet Hastanesi', 'Aydın', 'Nazilli'),
    ('Aydın Söke Fehime Faik Kocagöz Devlet Hastanesi', 'Aydın', 'Söke'),
    ('Balıkesir Ayvalık Devlet Hastanesi', 'Balıkesir', 'Ayvalık'),
    ('Balıkesir Bandırma Devlet Hastanesi', 'Balıkesir', 'Bandırma'),
    ('Balıkesir Bigadiç Devlet Hastanesi', 'Balıkesir', 'Bigadiç'),
    ('Balıkesir Burhaniye Devlet Hastanesi', 'Balıkesir', 'Burhaniye'),
    ('Balıkesir Dursunbey Devlet Hastanesi', 'Balıkesir', 'Dursunbey'),
    ('Balıkesir Edremit Devlet Hastanesi', 'Balıkesir', 'Edremit'),
    ('Balıkesir Erdek Neyyire Sıtkı Devlet Hastanesi', 'Balıkesir', 'Erdek'),
    ('Balıkesir Gönen Devlet Hastanesi', 'Balıkesir', 'Gönen'),
    ('Balıkesir Havran Devlet Hastanesi', 'Balıkesir', 'Havran'),
    ('Balıkesir İvrindi Devlet Hastanesi', 'Balıkesir', 'İvrindi'),
    ('Balıkesir Manyas Devlet Hastanesi', 'Balıkesir', 'Manyas'),
    ('Balıkesir Atatürk Devlet Hastanesi', 'Balıkesir', 'Merkez'),
    ('Balıkesir Devlet Hastanesi', 'Balıkesir', 'Merkez'),
    ('Balıkesir Göğüs Hastalıkları Hastanesi', 'Balıkesir', 'Merkez'),
    ('Balıkesir Savaştepe Devlet Hastanesi', 'Balıkesir', 'Savaştepe'),
    ('Balıkesir Sındırgı Devlet Hastanesi', 'Balıkesir', 'Sındırgı'),
    ('Balıkesir Susurluk Devlet Hastanesi', 'Balıkesir', 'Susurluk'),
    ('Bartın Devlet Hastanesi', 'Bartın', 'Merkez'),
    ('Batman Gercüş Devlet Hastanesi', 'Batman', 'Gercüş'),
    ('Batman Kozluk Devlet Hastanesi', 'Batman', 'Kozluk'),
    ('Batman Bölge Devlet Hastanesi', 'Batman', 'Merkez'),
    ('Batman Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Batman', 'Merkez'),
    ('Batman Sason Devlet Hastanesi', 'Batman', 'Sason'),
    ('Bayburt Devlet Hastanesi', 'Bayburt', 'Merkez'),
    ('Bilecik Bozüyük Devlet Hastanesi', 'Bilecik', 'Bozüyük'),
    ('Bilecik Devlet Hastanesi', 'Bilecik', 'Merkez'),
    ('Bilecik Osmaneli Devlet Hastanesi', 'Bilecik', 'Osmaneli'),
    ('Bilecik Söğüt Devlet Hastanesi', 'Bilecik', 'Söğüt'),
    ('Bingöl Genç Devlet Hastanesi', 'Bingöl', 'Genç'),
    ('Bingöl Karlıova İlçe Hastanesi', 'Bingöl', 'Karlıova'),
    ('Bingöl Devlet Hastanesi', 'Bingöl', 'Merkez'),
    ('Bingöl Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Bingöl', 'Merkez'),
    ('Bingöl Solhan Devlet Hastanesi', 'Bingöl', 'Solhan'),
    ('Bitlis Adilcevaz Onkoloji Hastanesi', 'Bitlis', 'Adilcevaz'),
    ('Bitlis Ahlat Devlet Hastanesi', 'Bitlis', 'Ahlat'),
    ('Bitlis Güroymak Devlet Hastanesi', 'Bitlis', 'Güroymak'),
    ('Bitlis Hizan İlçe Hastanesi', 'Bitlis', 'Hizan'),
    ('Bitlis Devlet Hastanesi', 'Bitlis', 'Merkez'),
    ('Bitlis Mutki İlçe Hastanesi', 'Bitlis', 'Mutki'),
    ('Bitlis Tatvan Devlet Hastanesi', 'Bitlis', 'Tatvan'),
    ('Bolu Gerede Devlet Hastanesi', 'Bolu', 'Gerede'),
    ('Bolu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Bolu', 'Merkez'),
    ('Bolu İzzet Baysal Devlet Hastanesi', 'Bolu', 'Merkez'),
    ('Bolu İzzet Baysal Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Bolu', 'Merkez'),
    ('Bolu Mudurnu İlçe Hastanesi', 'Bolu', 'Mudurnu'),
    ('Burdur Bucak Devlet Hastanesi', 'Burdur', 'Bucak'),
    ('Burdur Gölhisar Devlet Hastanesi', 'Burdur', 'Gölhisar'),
    ('Burdur Devlet Hastanesi', 'Burdur', 'Merkez'),
    ('Burdur Yeşilova Devlet Hastanesi', 'Burdur', 'Yeşilova'),
    ('Bursa Gemlik Muammer Ağım Devlet Hastanesi', 'Bursa', 'Gemlik'),
    ('Bursa İnegöl Devlet Hastanesi', 'Bursa', 'İnegöl'),
    ('Bursa İznik Devlet Hastanesi', 'Bursa', 'İznik'),
    ('Bursa Karacabey Devlet Hastanesi', 'Bursa', 'Karacabey'),
    ('Bursa M.Kemalpaşa Devlet Hastanesi', 'Bursa', 'M.kemalpaşa'),
    ('Bursa Mudanya Şaziye Rüştü Devlet Hastanesi', 'Bursa', 'Mudanya'),
    ('Bursa Dörtçelik Çocuk Hastalıkları Hastanesi', 'Bursa', 'Nilüfer'),
    ('Bursa Orhaneli Devlet Hastanesi', 'Bursa', 'Orhaneli'),
    ('Bursa Orhangazi Devlet Hastanesi', 'Bursa', 'Orhangazi'),
    ('Bursa Ali Osman Sönmez Onkoloji Hastanesi', 'Bursa', 'Osmangazi'),
    ('Bursa Çekirge Devlet Hastanesi', 'Bursa', 'Osmangazi'),
    ('Bursa Devlet Hastanesi', 'Bursa', 'Osmangazi'),
    ('Bursa Dr. Ayten Bozkaya Spastik Çocuklar Hastanesi Ve Rehabilitasyon Merkezi', 'Bursa', 'Osmangazi'),
    ('Bursa Zübeyde Hanım Doğumevi', 'Bursa', 'Osmangazi'),
    ('Bursa Yenişehir Devlet Hastanesi', 'Bursa', 'Yenişehir'),
    ('Bursa Prof.Dr. Türkan Akyol Göğüs Hastalıkları Hastanesi', 'Bursa', 'Yıldırım'),
    ('Bursa Şevket Yılmaz Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım'),
    ('Bursa Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Bursa', 'Yıldırım'),
    ('Çanakkale Ayvacık Devlet Hastanesi', 'Çanakkale', 'Ayvacık'),
    ('Çanakkale Bayramiç Devlet Hastanesi', 'Çanakkale', 'Bayramiç'),
    ('Çanakkale Biga Devlet Hastanesi', 'Çanakkale', 'Biga'),
    ('Çanakkale Çan Devlet Hastanesi', 'Çanakkale', 'Çan'),
    ('Çanakkale Ezine Devlet Hastanesi', 'Çanakkale', 'Ezine'),
    ('Çanakkale Gelibolu Devlet Hastanesi', 'Çanakkale', 'Gelibolu'),
    ('Çanakkale Gökçeada Devlet Hastanesi', 'Çanakkale', 'Gökçeada'),
    ('Çanakkale Lapseki Devlet Hastanesi', 'Çanakkale', 'Lapseki'),
    ('Çanakkale Devlet Hastanesi', 'Çanakkale', 'Merkez'),
    ('Çanakkale Yenice Devlet Hastanesi', 'Çanakkale', 'Yenice'),
    ('Çankırı Çerkeş Devlet Hastanesi', 'Çankırı', 'Çerkeş'),
    ('Çankırı Ilgaz Devlet Hastanesi', 'Çankırı', 'Ilgaz'),
    ('Çankırı Kurşunlu İlçe Hastanesi', 'Çankırı', 'Kurşunlu'),
    ('Çankırı Devlet Hastanesi', 'Çankırı', 'Merkez'),
    ('Çorum Alaca Devlet Hastanesi', 'Çorum', 'Alaca'),
    ('Çorum Bayat Devlet Hastanesi', 'Çorum', 'Bayat'),
    ('Çorum İskilip Devlet Hastanesi', 'Çorum', 'İskilip'),
    ('Çorum Kargı Devlet Hastanesi', 'Çorum', 'Kargı'),
    ('Çorum Mecitözü Devlet Hastanesi', 'Çorum', 'Mecitözü'),
    ('Çorum Göğüs Hastalıkları Hastanesi', 'Çorum', 'Merkez'),
    ('Çorum T.C. Sağlık Bakanlığı Hitit Üniversitesi Çorum Eğitim Ve Araştırma Hastanesi', 'Çorum', 'Merkez'),
    ('Çorum Osmancık Devlet Hastanesi', 'Çorum', 'Osmancık'),
    ('Çorum Sungurlu Devlet Hastanesi', 'Çorum', 'Sungurlu'),
    ('Denizli Acıpayam Devlet Hastanesi', 'Denizli', 'Acıpayam'),
    ('Denizli Buldan Göğüs Hastalıkları Hastanesi', 'Denizli', 'Buldan'),
    ('Denizli Çal Devlet Hastanesi', 'Denizli', 'Çal'),
    ('Denizli Çameli Devlet Hastanesi', 'Denizli', 'Çameli'),
    ('Denizli Çivril Devlet Hastanesi', 'Denizli', 'Çivril'),
    ('Denizli Honaz Devlet Hastanesi', 'Denizli', 'Honaz'),
    ('Denizli Kale Devlet Hastanesi', 'Denizli', 'Kale'),
    ('Denizli Devlet Hastanesi', 'Denizli', 'Merkez'),
    ('Denizli Servergazi Devlet Hastanesi', 'Denizli', 'Merkez'),
    ('Denizli Sarayköy Devlet Hastanesi', 'Denizli', 'Sarayköy'),
    ('Denizli Tavas Devlet Hastanesi', 'Denizli', 'Tavas'),
    ('Diyarbakır Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Bağlar'),
    ('Diyarbakır Bismil Devlet Hastanesi', 'Diyarbakır', 'Bismil'),
    ('Diyarbakır Çermik Devlet Hastanesi', 'Diyarbakır', 'Çermik'),
    ('Diyarbakır Çınar İlçe Hastanesi', 'Diyarbakır', 'Çınar'),
    ('Diyarbakır Dicle İlçe Hastanesi', 'Diyarbakır', 'Dicle'),
    ('Diyarbakır Eğil İlçe Hastanesi', 'Diyarbakır', 'Eğil'),
    ('Diyarbakır Ergani Devlet Hastanesi', 'Diyarbakır', 'Ergani'),
    ('Diyarbakır Hani İlçe Hastanesi', 'Diyarbakır', 'Hani'),
    ('Diyarbakır Eğitim Ve Araştırma Hastanesi', 'Diyarbakır', 'Kayapınar'),
    ('Diyarbakır Kulp İlçe Hastanesi', 'Diyarbakır', 'Kulp'),
    ('Diyarbakır Lice Halis Toprak Vakfı İlçe Hastanesi', 'Diyarbakır', 'Lice'),
    ('Diyarbakır Silvan Dr. Yusuf Azizoğlu Devlet Hastanesi', 'Diyarbakır', 'Silvan'),
    ('Diyarbakır Çocuk Hastalıkları Hastanesi', 'Diyarbakır', 'Yenişehir'),
    ('Diyarbakır Devlet Hastanesi', 'Diyarbakır', 'Yenişehir'),
    ('Düzce Akçakoca Devlet Hastanesi', 'Düzce', 'Akçakoca'),
    ('Düzce Atatürk Devlet Hastanesi', 'Düzce', 'Merkez'),
    ('Edirne Keşan Devlet Hastanesi', 'Edirne', 'Keşan'),
    ('Edirne Devlet Hastanesi', 'Edirne', 'Merkez'),
    ('Edirne Uzunköprü Devlet Hastanesi', 'Edirne', 'Uzunköprü'),
    ('Elazığ Karakoçan Devlet Hastanesi', 'Elazığ', 'Karakoçan'),
    ('Elazığ Kovancılar Devlet Hastanesi', 'Elazığ', 'Kovancılar'),
    ('Elazığ Maden Devlet Hastanesi', 'Elazığ', 'Maden'),
    ('Elazığ Eğitim Ve Araştırma Hastanesi', 'Elazığ', 'Merkez'),
    ('Elazığ Harput Devlet Hastanesi', 'Elazığ', 'Merkez'),
    ('Elazığ Ruh Sağlıgı Ve Hastalıkları Hastanesi', 'Elazığ', 'Merkez'),
    ('Elazığ Palu Devlet Hastanesi', 'Elazığ', 'Palu'),
    ('Erzincan Mengücek Gazi Eğitim Ve Araştırma Hastanesi', 'Erzincan', 'Mengücek'),
    ('Erzincan Refahiye Dr. Fahrettin Uğur İlçe Hastanesi', 'Erzincan', 'Refahiye'),
    ('Erzincan Tercan Devlet Hastanesi', 'Erzincan', 'Tercan'),
    ('Erzurum Aşkale İlçe Hastanesi', 'Erzurum', 'Aşkale'),
    ('Erzurum Çat İlçe Hastanesi', 'Erzurum', 'Çat'),
    ('Erzurum Hınıs Devlet Hastanesi', 'Erzurum', 'Hınıs'),
    ('Erzurum Horasan Devlet Hastanesi', 'Erzurum', 'Horasan'),
    ('Erzurum İspir Devlet Hastanesi', 'Erzurum', 'İspir'),
    ('Erzurum Karaçoban İlçe Hastanesi', 'Erzurum', 'Karaçoban'),
    ('Erzurum Türk Eczacıları Birliği Karayazı İlçe Hastanesi', 'Erzurum', 'Karayazı'),
    ('Erzurum Oltu Devlet Hastanesi', 'Erzurum', 'Oltu'),
    ('Erzurum Nenehatun Kadın Doğum Hastanesi', 'Erzurum', 'Palandöken'),
    ('Erzurum Pasinler İbrahim Hakkı Devlet Hastanesi', 'Erzurum', 'Pasinler'),
    ('Erzurum Tekman Devlet Hastanesi', 'Erzurum', 'Tekman'),
    ('Erzurum Tortum İlçe Hastanesi', 'Erzurum', 'Tortum'),
    ('Erzurum Bölge Eğitim Ve Araştırma Hastanesi', 'Erzurum', 'Yakutiye'),
    ('Erzurum Palandöken Devlet Hastanesi', 'Erzurum', 'Yakutiye'),
    ('Eskişehir Çifteler Devlet Hastanesi', 'Eskişehir', 'Çifteler'),
    ('Eskişehir Günyüzü İlçe Hastanesi', 'Eskişehir', 'Günyüzü'),
    ('Eskişehir Mahmudiye İlçe Hastanesi', 'Eskişehir', 'Mahmudiye'),
    ('Eskişehir Mihalıççık Gün Sazak İlçe Hastanesi', 'Eskişehir', 'Mihalıççık'),
    ('Eskişehir Devlet Hastanesi', 'Eskişehir', 'Odunpazarı'),
    ('Eskişehir Sivrihisar Devlet Hastanesi', 'Eskişehir', 'Sivrihisar'),
    ('Eskişehir Yunus Emre Devlet Hastanesi', 'Eskişehir', 'Tepebaşı'),
    ('Gaziantep Araban İlçe Hastanesi', 'Gaziantep', 'Araban'),
    ('Gaziantep İslahiye Devlet Hastanesi', 'Gaziantep', 'İslahiye'),
    ('Gaziantep Nizip Devlet Hastanesi', 'Gaziantep', 'Nizip'),
    ('Gaziantep Nurdağı İlçe Hastanesi', 'Gaziantep', 'Nurdağı'),
    ('Gaziantep Oğuzeli İlçe Hastanesi', 'Gaziantep', 'Oğuzeli'),
    ('Gaziantep Dr. Ersin Arslan Devlet Hastanesi', 'Gaziantep', 'Şahinbey'),
    ('Gaziantep 25 Aralık Devlet Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Gaziantep Cengiz Gökçek Kadın Hastalıkları Ve Doğum Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Gaziantep Çocuk Hastalıkları Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Gaziantep Şehitkamil Devlet Hastanesi', 'Gaziantep', 'Şehitkamil'),
    ('Giresun Alucra İlçe Hastanesi', 'Giresun', 'Alucra'),
    ('Giresun Bulancak Devlet Hastanesi', 'Giresun', 'Bulancak'),
    ('Giresun Dereli İlçe Hastanesi', 'Giresun', 'Dereli'),
    ('Giresun Espiye Devlet Hastanesi', 'Giresun', 'Espiye'),
    ('Giresun Op.Dr. Ergun Özdemir Görele Devlet Hastanesi', 'Giresun', 'Görele'),
    ('Giresun Dr. A.İlhan Özdemir Devlet Hastanesi', 'Giresun', 'Merkez'),
    ('Giresun Dr. Ali Menekşe Göğüs Hastalıkları Hastanesi', 'Giresun', 'Merkez'),
    ('Giresun Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Giresun', 'Merkez'),
    ('Giresun Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Giresun', 'Merkez'),
    ('Giresun Ş.Karahisar Devlet Hastanesi', 'Giresun', 'Şebinkarahisar'),
    ('Giresun Tirebolu Devlet Hastanesi', 'Giresun', 'Tirebolu'),
    ('Giresun Yağlıdere İlçe Hastanesi', 'Giresun', 'Yağlıdere'),
    ('Gümüşhane Kelkit Devlet Hastanesi', 'Gümüşhane', 'Kelkit'),
    ('Gümüşhane Devlet Hastanesi', 'Gümüşhane', 'Merkez'),
    ('Gümüşhane Şiran Devlet Hastanesi', 'Gümüşhane', 'Şiran'),
    ('Hakkari Devlet Hastanesi', 'Hakkâri', 'Merkez'),
    ('Hakkari Şemdinli Devlet Hastanesi', 'Hakkâri', 'Şemdinli'),
    ('Hakkari Yüksekova Devlet Hastanesi', 'Hakkâri', 'Yüksekova'),
    ('Hatay Altınözü Devlet Hastanesi', 'Hatay', 'Altınözü'),
    ('Hatay Antakya Devlet Hastanesi', 'Hatay', 'Antakya'),
    ('Hatay Doğum Ve Çocuk Bakımevi', 'Hatay', 'Antakya'),
    ('Hatay Dörtyol Devlet Hastanesi', 'Hatay', 'Dörtyol'),
    ('Hatay Erzin Devlet Hastanesi', 'Hatay', 'Erzin'),
    ('Hatay Hassa Devlet Hastanesi', 'Hatay', 'Hassa'),
    ('Hatay İskenderun Devlet Hastanesi', 'Hatay', 'İskenderun'),
    ('Hatay Kırıkhan Devlet Hastanesi', 'Hatay', 'Kırıkhan'),
    ('Hatay Reyhanlı Devlet Hastanesi', 'Hatay', 'Reyhanlı'),
    ('Hatay Samandağı Devlet Hastanesi', 'Hatay', 'Samandağ'),
    ('Iğdır Devlet Hastanesi', 'Iğdır', 'Merkez'),
    ('Iğdır Tuzluca Devlet Hastanesi', 'Iğdır', 'Tuzluca'),
    ('Isparta Eğirdir Kemik Eklem Hastalıkları Tedavi Ve Rehabilitasyon Hastanesi', 'Isparta', 'Eğirdir'),
    ('Isparta Devlet Hastanesi', 'Isparta', 'Merkez'),
    ('Isparta Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Isparta', 'Merkez'),
    ('Isparta Şarkikaraağaç Devlet Hastanesi', 'Isparta', 'Şarkikaraağaç'),
    ('Isparta Yalvaç Devlet Hastanesi', 'Isparta', 'Yalvaç'),
    ('İstanbul- (Avrupa)- Arnavutköy Devlet Hastanesi', 'İstanbul', 'Arnavutköy'),
    ('İstanbul- (Anadolu)- Ataşehir- Fatih Sultan Mehmet Eğitim Araştırma Hastanesi', 'İstanbul', 'Ataşehir'),
    ('İstanbul -(Avrupa)- Avcılar Murat Kölük Devlet Hastanesi', 'İstanbul', 'Avcılar'),
    ('İstanbul- (Avrupa)- Bağcılar Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Bağcılar'),
    ('İstanbul- (Avrupa)- Bahçelievler Devlet Hastanesi', 'İstanbul', 'Bahçelievler'),
    ('İstanbul- (Avrupa)- Bahçelievler- Fizik Tedavi Ve Rehabilitasyon Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Bahçelievler'),
    ('İstanbul- (Avrupa)- Bakırköy -Lepra Deri Ve Zührevi Hastalıkları Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Bakırköy Prof.Dr. Mazhar Osman Ruh Sağ. Ve Sinir Hast. Eğt. Ve Araş. Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Bakırköy- Deri Ve Tenasül Hastalıkları Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Bakırköy- Dr. Sadi Konuk Eğitim Araştırma Hastanesi', 'İstanbul', 'Bakırköy'),
    ('İstanbul- (Avrupa)- Başakşehir Devlet Hastanesi', 'İstanbul', 'Başakşehir'),
    ('İstanbul- (Avrupa)- Bayrampaşa Devlet Hastanesi', 'İstanbul', 'Bayrampaşa'),
    ('İstanbul- (Avrupa)- Beşiktaş- Sait Çiftçi Devlet Hastanesi', 'İstanbul', 'Beşiktaş'),
    ('İstanbul- (Anadolu)- Beykoz Devlet Hastanesi', 'İstanbul', 'Beykoz'),
    ('İstanbul- (Avrupa)- Prof.Dr. N.Reşat Belger Beyoğlu Göz Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Beyoğlu'),
    ('İstanbul- (Avrupa)- Büyükçekmece Devlet Hastanesi', 'İstanbul', 'Büyükçekmece'),
    ('İstanbul- (Avrupa)- Çatalca- İlyas Çokay Devlet Hastanesi', 'İstanbul', 'Çatalca'),
    ('İstanbul- (Avrupa)- Esenler Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'İstanbul', 'Esenler'),
    ('İstanbul- (Avrupa)- Esenyurt Devlet Hastanesi', 'İstanbul', 'Esenyurt'),
    ('İstanbul- (Avrupa)- Eyüp Devlet Hastanesi', 'İstanbul', 'Eyüp'),
    ('İstanbul- (Avrupa)- Fatih- İstanbul Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Fatih'),
    ('İstanbul- (Avrupa)- Fatih-haseki Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Fatih'),
    ('İstanbul- (Avrupa)- Gaziosmanpaşa Taksim Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Gaziosmanpaşa'),
    ('İstanbul- (Anadolu)- Kadıköy- Erenköy Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'İstanbul', 'Kadıköy'),
    ('İstanbul- (Anadolu)- Kadıköy- Erenköy Ruh Ve Sinir Hastalıkları Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kadıköy'),
    ('İstanbul- (Anadolu)- S.B. İstanbul Medeniyet Üniversitesi Göztepe Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kadıköy'),
    ('İstanbul- (Avrupa)- Kağıthane Devlet Hastanesi', 'İstanbul', 'Kağıthane'),
    ('İstanbul- (Anadolu)- Kartal- Dr. Lütfi Kırdar Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Anadolu)- Kartal- Koşuyolu Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Anadolu)- Kartal- Yakacık Doğum Ve Çocuk Hastalıkları Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Anadolu)- Kartal- Yavuz Selim Devlet Hastanesi', 'İstanbul', 'Kartal'),
    ('İstanbul- (Avrupa)- Küçükçekmece- Kanuni Sultan Süleyman Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Küçükçekmece'),
    ('İstanbul- (Avrupa)- Mehmet Akif Ersoy Göğüs Kalp Ve Damar Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Küçükçekmece'),
    ('İstanbul- (Anadolu)- Maltepe Devlet Hastanesi', 'İstanbul', 'Maltepe'),
    ('İstanbul- (Anadolu)- Meslek Hastalıkları Hastanesi', 'İstanbul', 'Maltepe'),
    ('İstanbul- (Anadolu)- Süreyyapaşa Göğüs Hastalıkları Ve Göğüs Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Maltepe'),
    ('İstanbul- (Anadolu)- Pendik Devlet Hastanesi', 'İstanbul', 'Pendik'),
    ('İstanbul- (Anadolu)- T.C.Sağlık Bakanlığı-marmara Üniversitesi Pendik Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Pendik'),
    ('İstanbul- (Avrupa)- Sarıyer- İsmail Akgün Devlet Hastanesi', 'İstanbul', 'Sarıyer'),
    ('İstanbul- (Avrupa)- Sarıyer- İstinye Devlet Hastanesi', 'İstanbul', 'Sarıyer'),
    ('İstanbul- (Avrupa)- Sarıyer- Metin Sabancı Baltalimanı Kemik Hastalıkları Eğitim Araştırma Hastanesi', 'İstanbul', 'Sarıyer'),
    ('İstanbul- (Avrupa)- Dr. Necmi Ayanoğlu Silivri Devlet Hastanesi', 'İstanbul', 'Silivri'),
    ('İstanbul- (Anadolu)- Tacirler Eğitim Vakfı Sultanbeyli Devlet Hastanesi', 'İstanbul', 'Sultanbeyli'),
    ('İstanbul- (Avrupa)- Sultangazi- Lütfiye Nuri Burat Devlet Hastanesi', 'İstanbul', 'Sultangazi'),
    ('İstanbul- (Anadolu)- Şile Devlet Hastanesi', 'İstanbul', 'Şile'),
    ('İstanbul- (Avrupa)- Şişli Etfal Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Şişli'),
    ('İstanbul- (Avrupa)- Şişli- Okmeydanı Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Şişli'),
    ('İstanbul- (Anadolu)- Tuzla Devlet Hastanesi', 'İstanbul', 'Tuzla'),
    ('İstanbul- (Anadolu)- Ümraniye Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Ümraniye'),
    ('İstanbul- (Anadolu)- Dr. Siyami Ersek Göğüs Kalp Ve Damar Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Anadolu)- Üsküdar Devlet Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Anadolu)- Üsküdar- Haydarpaşa Numune Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Anadolu)- Üsküdar- Zeynep Kamil Kadın Ve Çocuk Hastalıkları Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Üsküdar'),
    ('İstanbul- (Avrupa)- Süleymaniye Kadın Doğum Ve Çocuk Hastalıkları Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Zeytinburnu'),
    ('İstanbul- (Avrupa)- Yedikule Göğüs Hastalıkları Ve Göğüs Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İstanbul', 'Zeytinburnu'),
    ('İzmir Aliağa Devlet Hastanesi', 'İzmir', 'Aliağa'),
    ('İzmir Bayındır Devlet Hastanesi', 'İzmir', 'Bayındır'),
    ('İzmir Dr. Faruk İlker Bergama Devlet Hastanesi', 'İzmir', 'Bergama'),
    ('İzmir Bornova Türkan Özilhan Devlet Hastanesi', 'İzmir', 'Bornova'),
    ('İzmir Buca Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'İzmir', 'Buca'),
    ('İzmir Buca Seyfi Demirsoy Devlet Hastanesi', 'İzmir', 'Buca'),
    ('İzmir Alper Çizgenakat Çeşme Devlet Hastanesi', 'İzmir', 'Çeşme'),
    ('İzmir Çiğli Devlet Hastanesi', 'İzmir', 'Çiğli'),
    ('İzmir Dikili Devlet Hastanesi', 'İzmir', 'Dikili'),
    ('İzmir Foça Devlet Hastanesi', 'İzmir', 'Foça'),
    ('İzmir Gaziemir Nevvar Salih İşgören Devlet Hastanesi', 'İzmir', 'Gaziemir'),
    ('İzmir Bozyaka Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Karabağlar'),
    ('İzmir Katip Çelebi Üniversitesi Atatürk Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Karabağlar'),
    ('İzmir Karşıyaka Devlet Hastanesi', 'İzmir', 'Karşıyaka'),
    ('İzmir Kemalpaşa Devlet Hastanesi', 'İzmir', 'Kemalpaşa'),
    ('İzmir Kiraz Devlet Hastanesi', 'İzmir', 'Kiraz'),
    ('İzmir Alsancak Nevvar Salih İşgören Devlet Hastanesi', 'İzmir', 'Konak'),
    ('İzmir Dr. Behçet Uz Çocuk Hastalıkları Ve Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Konak'),
    ('İzmir Dr. Suat Seren Göğüs Hastalıkları Ve Cerrahisi Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Konak'),
    ('İzmir Eğitim Diş Hastanesi', 'İzmir', 'Konak'),
    ('İzmir Tepecik Eğitim Ve Araştırma Hastanesi', 'İzmir', 'Konak'),
    ('İzmir Menemen Devlet Hastanesi', 'İzmir', 'Menemen'),
    ('İzmir Ödemiş Devlet Hastanesi', 'İzmir', 'Ödemiş'),
    ('İzmir Nejat Hepkon Seferihisar Devlet Hastanesi', 'İzmir', 'Seferihisar'),
    ('İzmir Selçuk Devlet Hastanesi', 'İzmir', 'Selçuk'),
    ('İzmir Tire Devlet Hastanesi', 'İzmir', 'Tire'),
    ('İzmir M.Enver Şenerdem Torbalı Devlet Hastanesi', 'İzmir', 'Torbalı'),
    ('İzmir Urla Devlet Hastanesi', 'İzmir', 'Urla'),
    ('Kahramanmaraş Afşin Devlet Hastanesi', 'Kahramanmaraş', 'Afşin'),
    ('Kahramanmaraş Andırın Devlet Hastanesi', 'Kahramanmaraş', 'Andırın'),
    ('Kahramanmaraş Çağlayancerit İlçe Hastanesi', 'Kahramanmaraş', 'Çağlayancerit'),
    ('Kahramanmaraş Elbistan Devlet Hastanesi', 'Kahramanmaraş', 'Elbistan'),
    ('Kahramanmaraş Dr. Süreyya Adanalı Göksun Devlet Hastanesi', 'Kahramanmaraş', 'Göksun'),
    ('Kahramanmaraş Necip Fazıl Şehir Devlet Hastanesi', 'Kahramanmaraş', 'Merkez'),
    ('Kahramanmaraş Pazarcık Devlet Hastanesi', 'Kahramanmaraş', 'Pazarcık'),
    ('Kahramanmaraş Türkoğlu Dr. Kemal Beyazıt Fizik Tedavi Ve Rehabilitasyon Merkezi', 'Kahramanmaraş', 'Türkoğlu'),
    ('Karabük Sağlık Bakanlığı Karabük Üniversitesi Karabük Eğitim Ve Araştırma Hastanesi', 'Karabük', 'Merkez'),
    ('Karabük Safranbolu Devlet Hastanesi', 'Karabük', 'Safranbolu'),
    ('Karabük Yenice Devlet Hastanesi', 'Karabük', 'Yenice'),
    ('Karaman Ermenek Devlet Hastanesi', 'Karaman', 'Ermenek'),
    ('Karaman Devlet Hastanesi', 'Karaman', 'Merkez'),
    ('Kars Kağızman Devlet Hastanesi', 'Kars', 'Kağızman'),
    ('Kars Devlet Hastanesi', 'Kars', 'Merkez'),
    ('Kars Sarıkamış Devlet Hastanesi', 'Kars', 'Sarıkamış'),
    ('Kars Selim İlçe Hastanesi', 'Kars', 'Selim'),
    ('Kastamonu Araç İlçe Devlet Hastanesi', 'Kastamonu', 'Araç'),
    ('Kastamonu Azdavay İlçe Hastanesi', 'Kastamonu', 'Azdavay'),
    ('Kastamonu Bozkurt Devlet Hastanesi', 'Kastamonu', 'Bozkurt'),
    ('Kastamonu Cide Devlet Hastanesi', 'Kastamonu', 'Cide'),
    ('Kastamonu Daday Devlet Hastanesi', 'Kastamonu', 'Daday'),
    ('Kastamonu Devrekani Devlet Hastanesi', 'Kastamonu', 'Devrekani'),
    ('Kastamonu İnebolu Devlet Hastanesi', 'Kastamonu', 'İnebolu'),
    ('Kastamonu Dr. Münif İslamoğlu Devlet Hastanesi', 'Kastamonu', 'Merkez'),
    ('Kastamonu Rehabilitasyon Merkezi', 'Kastamonu', 'Merkez'),
    ('Kastamonu Taşköprü Devlet Hastanesi', 'Kastamonu', 'Taşköprü'),
    ('Kastamonu Tosya Devlet Hastanesi', 'Kastamonu', 'Tosya'),
    ('Kayseri Bünyan Devlet Hastanesi', 'Kayseri', 'Bünyan'),
    ('Kayseri Develi Devlet Hastanesi', 'Kayseri', 'Develi'),
    ('Kayseri İncesu İlçe Hastanesi', 'Kayseri', 'İncesu'),
    ('Kayseri Eğitim Ve Araştırma Hastanesi', 'Kayseri', 'Kocasinan'),
    ('Kayseri Pınarbaşı İlçe Hastanesi', 'Kayseri', 'Pınarbaşı'),
    ('Kayseri Tomarza Devlet Hastanesi', 'Kayseri', 'Tomarza'),
    ('Kayseri Yahyalı Devlet Hastanesi', 'Kayseri', 'Yahyalı'),
    ('Kayseri Yeşilhisarilçe Devlet Hastanesi', 'Kayseri', 'Yeşilhisar'),
    ('Kırıkkale Yüksek İhtisas Hastanesi', 'Kırıkkale', 'Merkez'),
    ('Kırklareli Babaeski Devlet Hastanesi', 'Kırklareli', 'Babaeski'),
    ('Kırklareli Lüleburgaz Devlet Hastanesi', 'Kırklareli', 'Lüleburgaz'),
    ('Kırklareli Devlet Hastanesi', 'Kırklareli', 'Merkez'),
    ('Kırklareli Pınarhisar Devlet Hastanesi', 'Kırklareli', 'Pınarhisar'),
    ('Kırklareli Vize Devlet Hastanesi', 'Kırklareli', 'Vize'),
    ('Kırşehir Kaman Devlet Hastanesi', 'Kırşehir', 'Kaman'),
    ('Kırşehir Ahi Evran Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Kırşehir', 'Merkez'),
    ('Kırşehir Mucur Devlet Hastanesi', 'Kırşehir', 'Mucur'),
    ('Kilis Devlet Hastanesi', 'Kilis', 'Merkez'),
    ('Kocaeli Darıca Farabi Devlet Hastanesi', 'Kocaeli', 'Darıca'),
    ('Kocaeli Derince Eğitim Ve Araştırma Hastanesi', 'Kocaeli', 'Derince'),
    ('Kocaeli Gebze Fatih Devlet Hastanesi', 'Kocaeli', 'Gebze'),
    ('Kocaeli Gölcük Necati Çelik Devlet Hastanesi', 'Kocaeli', 'Gölcük'),
    ('Kocaeli Devlet Hastanesi', 'Kocaeli', 'İzmit'),
    ('Kocaeli İzmit Seka Devlet Hastanesi', 'Kocaeli', 'İzmit'),
    ('Kocaeli Kandıra Kazım Dinç Devlet Hastanesi', 'Kocaeli', 'Kandıra'),
    ('Kocaeli Karamürsel Devlet Hastanesi', 'Kocaeli', 'Karamürsel'),
    ('Kocaeli Körfez Devlet Hastanesi', 'Kocaeli', 'Körfez'),
    ('Konya Akşehir Devlet Hastanesi', 'Konya', 'Akşehir'),
    ('Konya Beyşehir Devlet Hastanesi', 'Konya', 'Beyşehir'),
    ('Konya Bozkır Devlet Hastanesi', 'Konya', 'Bozkır'),
    ('Konya Cihanbeyli Devlet Hastanesi', 'Konya', 'Cihanbeyli'),
    ('Konya Çumra Devlet Hastanesi', 'Konya', 'Çumra'),
    ('Konya Doğanhisar Devlet Hastanesi', 'Konya', 'Doğanhisar'),
    ('Konya Ereğli Devlet Hastanesi', 'Konya', 'Ereğli'),
    ('Konya Hadim Devlet Hastanesi', 'Konya', 'Hadim'),
    ('Konya Hüyük Devlet Hastanesi', 'Konya', 'Hüyük'),
    ('Konya Dr. Vefa Tanır Ilgın Devlet Hastanesi', 'Konya', 'Ilgın'),
    ('Konya Kadınhanı Refik Saime Koyuncu Devlet Hastanesi', 'Konya', 'Kadınhanı'),
    ('Konya Karapınar Devlet Hastanesi', 'Konya', 'Karapınar'),
    ('Konya Kulu Devlet Hastanesi', 'Konya', 'Kulu'),
    ('Konya Eğitim Ve Araştırma Hastanesi', 'Konya', 'Meram'),
    ('Konya Sarayönü Devlet Hastanesi', 'Konya', 'Sarayönü'),
    ('Konya Beyhekim Devlet Hastanesi', 'Konya', 'Selçuklu'),
    ('Konya Dr. Faruk Sükan Doğum Ve Çocuk Bakımevi', 'Konya', 'Selçuklu'),
    ('Konya Numune Hastanesi', 'Konya', 'Selçuklu'),
    ('Konya Seydişehir Devlet Hastanesi', 'Konya', 'Seydişehir'),
    ('Konya Yunak Hacı İzzet Baysal Devlet Hastanesi', 'Konya', 'Yunak'),
    ('Kütahya Emet Devlet Hastanesi', 'Kütahya', 'Emet'),
    ('Kütahya Gediz Devlet Hastanesi', 'Kütahya', 'Gediz'),
    ('Kütahya D.P.Ü. Evliya Çelebi Eğitim Ve Araştırma Hastanesi', 'Kütahya', 'Merkez'),
    ('Kütahya Yoncalı Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Kütahya', 'Merkez'),
    ('Kütahya Doç.Dr. İsmail Karakuyu Simav Devlet Hastanesi', 'Kütahya', 'Simav'),
    ('Kütahya Doç.Dr. Mustafa Kalemli Tavşanlı Devlet Hastanesi', 'Kütahya', 'Tavşanlı'),
    ('Malatya Akçadağ 75.Yıl Devlet Hastanesi', 'Malatya', 'Akçadağ'),
    ('Malatya Arapgir İlçe Hastanesi', 'Malatya', 'Arapkir'),
    ('Malatya Darende Hulusi Efendi Devlet Hastanesi', 'Malatya', 'Darende'),
    ('Malatya Doğanşehir Devlet Hastanesi', 'Malatya', 'Doğanşehir'),
    ('Malatya Hekimhan Devlet Hastanesi', 'Malatya', 'Hekimhan'),
    ('Malatya Devlet Hastanesi', 'Malatya', 'Merkez'),
    ('Malatya Pötürge Devlet Hastanesi', 'Malatya', 'Pötürge'),
    ('Malatya Yeşilyurt Hasan Çalık Devlet Hastanesi', 'Malatya', 'Yeşilyurt'),
    ('Manisa Akhisar Devlet Hastanesi', 'Manisa', 'Akhisar'),
    ('Manisa Alaşehir Devlet Hastanesi', 'Manisa', 'Alaşehir'),
    ('Manisa Demirci Devlet Hastanesi', 'Manisa', 'Demirci'),
    ('Manisa Gördes Devlet Hastanesi', 'Manisa', 'Gördes'),
    ('Manisa Kırkağaç Devlet Hastanesi', 'Manisa', 'Kırkağaç'),
    ('Manisa Kula Devlet Hastanesi', 'Manisa', 'Kula'),
    ('Manisa Devlet Hastanesi', 'Manisa', 'Merkez'),
    ('Manisa Merkezefendi Devlet Hastanesi', 'Manisa', 'Merkez'),
    ('Manisa Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Manisa', 'Merkez'),
    ('Manisa Salihli Devlet Hastanesi', 'Manisa', 'Salihli'),
    ('Manisa Sarıgöl Devlet Hastanesi', 'Manisa', 'Sarıgöl'),
    ('Manisa Saruhanlı Devlet Hastanesi', 'Manisa', 'Saruhanlı'),
    ('Manisa Selendi Devlet Hastanesi', 'Manisa', 'Selendi'),
    ('Manisa Soma Devlet Hastanesi', 'Manisa', 'Soma'),
    ('Manisa Turgutlu Devlet Hastanesi', 'Manisa', 'Turgutlu'),
    ('Mardin Dargeçit İlçe Hastanesi', 'Mardin', 'Dargeçit'),
    ('Mardin Derik Devlet Hastanesi', 'Mardin', 'Derik'),
    ('Mardin Kızıltepe Devlet Hastanesi', 'Mardin', 'Kızıltepe'),
    ('Mardin Mazıdağı İlçe Hastanesi', 'Mardin', 'Mazıdağı'),
    ('Mardin Devlet Hastanesi', 'Mardin', 'Merkez'),
    ('Mardin Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Mardin', 'Merkez'),
    ('Mardin Midyat Devlet Hastanesi', 'Mardin', 'Midyat'),
    ('Mardin Nusaybin Devlet Hastanesi', 'Mardin', 'Nusaybin'),
    ('Mardin Savur İlçe Hastanesi', 'Mardin', 'Savur'),
    ('Mersin Devlet Hastanesi', 'Mersin', 'Akdeniz'),
    ('Mersin Toros Devlet Hastanesi', 'Mersin', 'Akdeniz'),
    ('Mersin Anamur Devlet Hastanesi', 'Mersin', 'Anamur'),
    ('Mersin Aydıncık Devlet Hastanesi', 'Mersin', 'Aydıncık'),
    ('Mersin Bozyazı Devlet Hastanesi', 'Mersin', 'Bozyazı'),
    ('Mersin Erdemli Devlet Hastanesi', 'Mersin', 'Erdemli'),
    ('Mersin Gülnar Devlet Hastanesi', 'Mersin', 'Gülnar'),
    ('Mersin Mut Devlet Hastanesi', 'Mersin', 'Mut'),
    ('Mersin Silifke Devlet Hastanesi', 'Mersin', 'Silifke'),
    ('Mersin Tarsus Devlet Hastanesi', 'Mersin', 'Tarsus'),
    ('Mersin Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Mersin', 'Toroslar'),
    ('Muğla Bodrum Devlet Hastanesi', 'Muğla', 'Bodrum'),
    ('Muğla Dalaman Devlet Hastanesi', 'Muğla', 'Dalaman'),
    ('Muğla Datça Devlet Hastanesi', 'Muğla', 'Datça'),
    ('Muğla Fethiye Devlet Hastanesi', 'Muğla', 'Fethiye'),
    ('Muğla Köyceğiz Devlet Hastanesi', 'Muğla', 'Köyceğiz'),
    ('Muğla Marmaris Devlet Hastanesi', 'Muğla', 'Marmaris'),
    ('Muğla T.C.Sağlık Bakanlığı Muğla Sıtkı Koçman Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Muğla', 'Merkez'),
    ('Muğla Milas 75.Yıl Devlet Hastanesi', 'Muğla', 'Milas'),
    ('Muğla Ortaca Devlet Hastanesi', 'Muğla', 'Ortaca'),
    ('Muğla Yatağan Devlet Hastanesi', 'Muğla', 'Yatağan'),
    ('Muş Bulanık Devlet Hastanesi', 'Muş', 'Bulanık'),
    ('Muş Hasköy Devlet Hastanesi', 'Muş', 'Hasköy'),
    ('Muş Korkut İlçe Hastanesi', 'Muş', 'Korkut'),
    ('Muş Malazgirt Devlet Hastanesi', 'Muş', 'Malazgirt'),
    ('Muş Devlet Hastanesi', 'Muş', 'Merkez'),
    ('Muş Varto Devlet Hastanesi', 'Muş', 'Varto'),
    ('Nevşehir Dr. İ.Şevki Atasagun Devlet Hastanesi', 'Nevşehir', 'Merkez'),
    ('Nevşehir Ürgüp Devlet Hastanesi', 'Nevşehir', 'Ürgüp'),
    ('Niğde Bor Devlet Hastanesi', 'Niğde', 'Bor'),
    ('Niğde Çiftlik İlçe Hastanesi', 'Niğde', 'Çiftlik'),
    ('Niğde Devlet Hastanesi', 'Niğde', 'Merkez'),
    ('Niğde Ulukışla İlçe Hastanesi', 'Niğde', 'Ulukışla'),
    ('Ordu Akkuş Devlet Hastanesi', 'Ordu', 'Akkuş'),
    ('Ordu Aybastı Devlet Hastanesi', 'Ordu', 'Aybastı'),
    ('Ordu Fatsa Devlet Hastanesi', 'Ordu', 'Fatsa'),
    ('Ordu Gölköy Devlet Hastanesi', 'Ordu', 'Gölköy'),
    ('Ordu Gürgentepe Devlet Hastanesi', 'Ordu', 'Gürgentepe'),
    ('Ordu Korgan Devlet Hastanesi', 'Ordu', 'Korgan'),
    ('Ordu Kumru Devlet Hastanesi', 'Ordu', 'Kumru'),
    ('Ordu Devlet Hastanesi', 'Ordu', 'Merkez'),
    ('Ordu Sağlık Bakanlığı-ordu Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Ordu', 'Merkez'),
    ('Ordu Ulubey Devlet Hastanesi', 'Ordu', 'Ulubey'),
    ('Ordu Ünye Devlet Hastanesi', 'Ordu', 'Ünye'),
    ('Osmaniye Düziçi Devlet Hastanesi', 'Osmaniye', 'Düziçi'),
    ('Osmaniye Kadirli Devlet Hastanesi', 'Osmaniye', 'Kadirli'),
    ('Osmaniye Devlet Hastanesi', 'Osmaniye', 'Merkez'),
    ('Rize İshakoğlu Çayeli Devlet Hastanesi', 'Rize', 'Çayeli'),
    ('Rize Fındıklı Bölge Guatr Araştırma Ve Tedavi Merkezi', 'Rize', 'Fındıklı'),
    ('Rize Güneysu Tenzile Erdoğan İlçe Hastanesi', 'Rize', 'Güneysu'),
    ('Rize Devlet Hastanesi', 'Rize', 'Merkez'),
    ('Rize T.C. Sağlık Bakanlığı Recep Tayyip Erdoğan Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Rize', 'Merkez'),
    ('Rize Kaçkar Devlet Hastanesi', 'Rize', 'Pazar'),
    ('Sakarya Doğum Ve Çocuk Bakımevi', 'Sakarya', 'Adapazarı'),
    ('Sakarya Sağlık Bakanlığı Sakarya Üniversitesi Eğitim Ve Araştırma Hastanesi', 'Sakarya', 'Adapazarı'),
    ('Sakarya Yenikent Devlet Hastanesi', 'Sakarya', 'Adapazarı'),
    ('Sakarya Akyazı Devlet Hastanesi', 'Sakarya', 'Akyazı'),
    ('Sakarya Toyotasa Acil Yardım Hastanesi', 'Sakarya', 'Arifiye'),
    ('Sakarya Ferizli İlçe Hastanesi', 'Sakarya', 'Ferizli'),
    ('Sakarya Geyve Devlet Hastanesi', 'Sakarya', 'Geyve'),
    ('Sakarya Hendek Devlet Hastanesi', 'Sakarya', 'Hendek'),
    ('Sakarya Karasu Devlet Hastanesi', 'Sakarya', 'Karasu'),
    ('Sakarya Kaynarca İlçe Hastanesi', 'Sakarya', 'Kaynarca'),
    ('Sakarya Kocaali İlçe Hastanesi', 'Sakarya', 'Kocaali'),
    ('Sakarya Pamukova Devlet Hastanesi', 'Sakarya', 'Pamukova'),
    ('Sakarya Sapanca İlçe Hastanesi', 'Sakarya', 'Sapanca'),
    ('Samsun 19 Mayıs İlçe (Engiz) Hastanesi', 'Samsun', '19mayıs'),
    ('Samsun Alaçam Devlet Hastanesi', 'Samsun', 'Alaçam'),
    ('Samsun Asarcık İlçe Hastanesi', 'Samsun', 'Asarcık'),
    ('Samsun Ayvacık Devlet Hastanesi', 'Samsun', 'Ayvacık'),
    ('Samsun Bafra Devlet Hastanesi', 'Samsun', 'Bafra'),
    ('Samsun Çarşamba Devlet Hastanesi', 'Samsun', 'Çarşamba'),
    ('Samsun Havza Devlet Hastanesi', 'Samsun', 'Havza'),
    ('Samsun Eğitim Ve Araştırma Hastanesi', 'Samsun', 'İlkadım'),
    ('Samsun Fiziksel Tıp Rehabilitasyon Hastalıkları Hastanesi', 'Samsun', 'İlkadım'),
    ('Samsun Gazi Devlet Hastanesi', 'Samsun', 'İlkadım'),
    ('Samsun Göğüs Hastalıkları Ve Göğüs Cerrahisi Hastanesi', 'Samsun', 'İlkadım'),
    ('Samsun Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Samsun', 'İlkadım'),
    ('Samsun Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Samsun', 'İlkadım'),
    ('Samsun Kavak Devlet Hastanesi', 'Samsun', 'Kavak'),
    ('Samsun Ladik Devlet Hastanesi', 'Samsun', 'Ladik'),
    ('Samsun Salıpazarı İlçe Hastanesi', 'Samsun', 'Salıpazarı'),
    ('Samsun Terme Devlet Hastanesi', 'Samsun', 'Terme'),
    ('Samsun Vezirköprü Devlet Hastanesi', 'Samsun', 'Vezirköprü'),
    ('Siirt Baykan Devlet Hastanesi', 'Siirt', 'Baykan'),
    ('Siirt Eruh İlçe Hastanesi', 'Siirt', 'Eruh'),
    ('Siirt Kurtalan Devlet Hastanesi', 'Siirt', 'Kurtalan'),
    ('Siirt Devlet Hastanesi', 'Siirt', 'Merkez'),
    ('Siirt Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Siirt', 'Merkez'),
    ('Siirt Pervari İlçe Hastanesi', 'Siirt', 'Pervari'),
    ('Sinop Ayancık Devlet Hastanesi', 'Sinop', 'Ayancık'),
    ('Sinop Boyabat 75.Yıl Devlet Hastanesi', 'Sinop', 'Boyabat'),
    ('Sinop Durağan Devlet Hastanesi', 'Sinop', 'Durağan'),
    ('Sinop Gerze Devlet Hastanesi', 'Sinop', 'Gerze'),
    ('Sinop Atatürk Devlet Hastanesi', 'Sinop', 'Merkez'),
    ('Sinop Türkeli Devlet Hastanesi', 'Sinop', 'Türkeli'),
    ('Sivas Divriği Sadık Özgür Devlet Hastanesi', 'Sivas', 'Divriği'),
    ('Sivas Gemerek Devlet Hastanesi', 'Sivas', 'Gemerek'),
    ('Sivas Gürün Devlet Hastanesi', 'Sivas', 'Gürün'),
    ('Sivas Kangal Devlet Hastanesi', 'Sivas', 'Kangal'),
    ('Sivas Devlet Hastanesi', 'Sivas', 'Merkez'),
    ('Sivas Numune Hastanesi', 'Sivas', 'Merkez'),
    ('Sivas Suşehri Devlet Hastanesi', 'Sivas', 'Suşehri'),
    ('Sivas Şarkışla Devlet Hastanesi', 'Sivas', 'Şarkışla'),
    ('Sivas Yıldızeli Devlet Hastanesi', 'Sivas', 'Yıldızeli'),
    ('Sivas Zara Devlet Hastanesi', 'Sivas', 'Zara'),
    ('Şanlıurfa Akçakale Devlet Hastanesi', 'Şanlıurfa', 'Akçakale'),
    ('Şanlıurfa Birecik Devlet Hastanesi', 'Şanlıurfa', 'Birecik'),
    ('Şanlıurfa Bozova İlçe Hastanesi', 'Şanlıurfa', 'Bozova'),
    ('Şanlıurfa Ceylanpınar Devlet Hastanesi', 'Şanlıurfa', 'Ceylanpınar'),
    ('Şanlıurfa Halfeti İlçe Hastanesi', 'Şanlıurfa', 'Halfeti'),
    ('Şanlıurfa Harran Devlet Hastanesi', 'Şanlıurfa', 'Harran'),
    ('Şanlıurfa Hilvan Devlet Hastanesi', 'Şanlıurfa', 'Hilvan'),
    ('Şanlıurfa Balıklıgöl Devlet Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('Şanlıurfa Çocuk Hastalıkları Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('Şanlıurfa Eğitim Ve Araştırma Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('Şanlıurfa Kadın Hastalıkları Ve Doğum Hastanesi', 'Şanlıurfa', 'Merkez'),
    ('Şanlıurfa Siverek Devlet Hastanesi', 'Şanlıurfa', 'Siverek'),
    ('Şanlıurfa Suruç Devlet Hastanesi', 'Şanlıurfa', 'Suruç'),
    ('Şanlıurfa Viranşehir Devlet Hastanesi', 'Şanlıurfa', 'Viranşehir'),
    ('Şırnak Beytüşşebap Devlet Hastanesi', 'Şırnak', 'Beytüşşebap'),
    ('Şırnak Cizre Dr. Selahattin Cizrelioğlu Devlet Hastanesi', 'Şırnak', 'Cizre'),
    ('Şırnak İdil Devlet Hastanesi', 'Şırnak', 'İdil'),
    ('Şırnak Devlet Hastanesi', 'Şırnak', 'Merkez'),
    ('Şırnak Silopi Devlet Hastanesi', 'Şırnak', 'Silopi'),
    ('Şırnak Uludere Devlet Hastanesi', 'Şırnak', 'Uludere'),
    ('Tekirdağ Çerkezköy Devlet Hastanesi', 'Tekirdağ', 'Çerkezköy'),
    ('Tekirdağ Çorlu Devlet Hastanesi', 'Tekirdağ', 'Çorlu'),
    ('Tekirdağ Hayrabolu Devlet Hastanesi', 'Tekirdağ', 'Hayrabolu'),
    ('Tekirdağ Marmara Ereğlisi İlçe Devlet Hastanesi', 'Tekirdağ', 'M.ereğlisi'),
    ('Tekirdağ Malkara Devlet Hastanesi', 'Tekirdağ', 'Malkara'),
    ('Tekirdağ Devlet Hastanesi', 'Tekirdağ', 'Merkez'),
    ('Tekirdağ Muratlı Devlet Hastanesi', 'Tekirdağ', 'Muratlı'),
    ('Tekirdağ Saray Devlet Hastanesi', 'Tekirdağ', 'Saray'),
    ('Tekirdağ Şarköy Devlet Hastanesi', 'Tekirdağ', 'Şarköy'),
    ('Tokat Almus İlçe Hastanesi', 'Tokat', 'Almus'),
    ('Tokat Erbaa Devlet Hastanesi', 'Tokat', 'Erbaa'),
    ('Tokat Devlet Hastanesi', 'Tokat', 'Merkez'),
    ('Tokat Ruh Sağlığı Ve Hastalıkları Hastanesi', 'Tokat', 'Merkez'),
    ('Tokat Niksar Devlet Hastanesi', 'Tokat', 'Niksar'),
    ('Tokat Reşadiye Devlet Hastanesi', 'Tokat', 'Reşadiye'),
    ('Tokat Turhal Devlet Hastanesi', 'Tokat', 'Turhal'),
    ('Tokat Zile Devlet Hastanesi', 'Tokat', 'Zile'),
    ('Trabzon Akçaabat Haçkalı Baba Devlet Hastanesi', 'Trabzon', 'Akçaabat'),
    ('Trabzon Araklı Bayram Halil Devlet Hastanesi', 'Trabzon', 'Araklı'),
    ('Trabzon Ataköy Ruh Ve Sinir Hastalıkları Hastanesi', 'Trabzon', 'Çaykara'),
    ('Trabzon Maçka Ömer Burhanoğlu Fizik Tedavi Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Maçka'),
    ('Trabzon Ahi Evren Göğüs Kalp Ve Damar Cerrahisi Eğitim Ve Araştırma Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Fatih Devlet Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Kanuni Eğitim Ve Araştırma Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Yavuz Selim Kemik Hastalıkları Ve Rehabilitasyon Hastanesi', 'Trabzon', 'Merkez'),
    ('Trabzon Of Devlet Hastanesi', 'Trabzon', 'Of'),
    ('Trabzon Sürmene Devlet Hastanesi', 'Trabzon', 'Sürmene'),
    ('Trabzon Tonya Devlet Hastanesi', 'Trabzon', 'Tonya'),
    ('Trabzon Vakfıkebir Devlet Hastanesi', 'Trabzon', 'Vakfıkebir'),
    ('Tunceli Devlet Hastanesi', 'Tunceli', 'Merkez'),
    ('Uşak Banaz Devlet Hastanesi', 'Uşak', 'Banaz'),
    ('Uşak Eşme Devlet Hastanesi', 'Uşak', 'Eşme'),
    ('Uşak Devlet Hastanesi', 'Uşak', 'Merkez'),
    ('Uşak Sivaslı Devlet Hastanesi', 'Uşak', 'Sivaslı'),
    ('Van Bahçesaray İlçe Hastanesi', 'Van', 'Bahçesaray'),
    ('Van Başkale Devlet Hastanesi', 'Van', 'Başkale'),
    ('Van Çaldıran İlçe Hastanesi', 'Van', 'Çaldıran'),
    ('Van Çatak İlçe Hastanesi', 'Van', 'Çatak'),
    ('Van Erciş Devlet Hastanesi', 'Van', 'Erciş'),
    ('Van Gevaş Devlet Hastanesi', 'Van', 'Gevaş'),
    ('Van Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Van', 'İpekyolu'),
    ('Van Bölge Eğitim Ve Araştırma Hastanesi', 'Van', 'Merkez'),
    ('Van Muradiye Devlet Hastanesi', 'Van', 'Muradiye'),
    ('Van Özalp Devlet Hastanesi', 'Van', 'Özalp'),
    ('Yalova Çınarcık Devlet Hastanesi', 'Yalova', 'Çınarcık'),
    ('Yalova Devlet Hastanesi', 'Yalova', 'Merkez'),
    ('Yozgat Akdağmadeni Devlet Hastanesi', 'Yozgat', 'Akdağmadeni'),
    ('Yozgat Boğazlıyan Devlet Hastanesi', 'Yozgat', 'Boğazlıyan'),
    ('Yozgat Çekerek Devlet Hastanesi', 'Yozgat', 'Çekerek'),
    ('Yozgat Devlet Hastanesi', 'Yozgat', 'Merkez'),
    ('Yozgat Saraykent İlçe Hastanesi', 'Yozgat', 'Saraykent'),
    ('Yozgat Sarıkaya Devlet Hastanesi', 'Yozgat', 'Sarıkaya'),
    ('Yozgat Sorgun Devlet Hastanesi', 'Yozgat', 'Sorgun'),
    ('Yozgat Şefaatli Devlet Hastanesi', 'Yozgat', 'Şefaatli'),
    ('Yozgat Yerköy Devlet Hastanesi', 'Yozgat', 'Yerköy'),
    ('Zonguldak Alaplı Devlet Hastanesi', 'Zonguldak', 'Alaplı'),
    ('Zonguldak Çaycuma Devlet Hastanesi', 'Zonguldak', 'Çaycuma'),
    ('Zonguldak Devrek Devlet Hastanesi', 'Zonguldak', 'Devrek'),
    ('Zonguldak Karadeniz Ereğli Devlet Hastanesi', 'Zonguldak', 'Ereğli'),
    ('Zonguldak Gökçebey İlçe Hastanesi', 'Zonguldak', 'Gökçebey'),
    ('Zonguldak Atatürk Devlet Hastanesi', 'Zonguldak', 'Merkez'),
    ('Zonguldak Kadın Doğum Ve Çocuk Hastalıkları Hastanesi', 'Zonguldak', 'Merkez'),
    ('Zonguldak Uzun Mehmet Göğüs Ve Meslek Hastalıkları Hastanesi', 'Zonguldak', 'Merkez')
), branch_seed(branch) as (
  values
    ('Pratisyen Hekim Görevi'),
    ('Acil Tıp'),
    ('Adli Tıp'),
    ('Aile Hekimliği'),
    ('Anesteziyoloji ve Reanimasyon'),
    ('Beyin ve Sinir Cerrahisi'),
    ('Çocuk Cerrahisi'),
    ('Çocuk Sağlığı ve Hastalıkları'),
    ('Çocuk ve Ergen Ruh Sağlığı ve Hastalıkları'),
    ('Çocuk Alerji ve İmmünoloji'),
    ('Çocuk Endokrinolojisi'),
    ('Çocuk Enfeksiyon Hastalıkları'),
    ('Çocuk Gastroenterolojisi'),
    ('Çocuk Göğüs Hastalıkları'),
    ('Çocuk Hematolojisi ve Onkolojisi'),
    ('Çocuk Kardiyolojisi'),
    ('Çocuk Nefrolojisi'),
    ('Çocuk Nörolojisi'),
    ('Çocuk Romatolojisi'),
    ('Çocuk Yoğun Bakım'),
    ('Deri ve Zührevi Hastalıkları'),
    ('Endokrinoloji ve Metabolizma Hastalıkları'),
    ('Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji'),
    ('Fiziksel Tıp ve Rehabilitasyon'),
    ('Gastroenteroloji'),
    ('Genel Cerrahi'),
    ('Geriatri'),
    ('Göğüs Cerrahisi'),
    ('Göğüs Hastalıkları'),
    ('Göz Hastalıkları'),
    ('Halk Sağlığı'),
    ('Hematoloji'),
    ('İç Hastalıkları'),
    ('Jinekolojik Onkoloji Cerrahisi'),
    ('Kadın Hastalıkları ve Doğum'),
    ('Kalp ve Damar Cerrahisi'),
    ('Kardiyoloji'),
    ('Kulak Burun Boğaz Hastalıkları'),
    ('Nefroloji'),
    ('Neonatoloji'),
    ('Nöroloji'),
    ('Nükleer Tıp'),
    ('Ortopedi ve Travmatoloji'),
    ('Perinatoloji'),
    ('Plastik, Rekonstrüktif ve Estetik Cerrahi'),
    ('Psikiyatri'),
    ('Radyasyon Onkolojisi'),
    ('Radyoloji'),
    ('Romatoloji'),
    ('Tıbbi Biyokimya'),
    ('Tıbbi Genetik'),
    ('Tıbbi Mikrobiyoloji'),
    ('Tıbbi Onkoloji'),
    ('Tıbbi Patoloji'),
    ('Üroloji'),
    ('Yoğun Bakım')
), target_hospitals as (
  select id from public.hospitals
)
insert into public.clinics (hospital_id, branch)
select th.id, bs.branch
from target_hospitals th cross join branch_seed bs
where not exists (
  select 1 from public.clinics c
  where c.hospital_id=th.id and c.branch=bs.branch
);
